### ISSUE TITLE
Question - Set nested object state 

### ISSUE THREAD

**Issue by kkomaz** [avkonst/hookstate#103]
Hello!  First of all... great library!  I really feel like your tackling an issue a lot of people aren't thinking about!

Just had a quick question about updating nested object state.  Is there a better way to perform updates than what I show below?  

In this case, I want to keep the same contents of the `specialInfo` while just changing the age value from 28 to 29.

Or is this a bad pattern in general?  Is it better to have 2 states in this case that utilize the `useState` for `basicInfo` and `specialInfo`?

This example is a bit contrived but I am imaging a global object that contains information about user and it's session.

Some of the keys may be nested and was curious if there is a more efficient way to do it.

```js
function App() {
  const userState = useState({
    basicInfo: {
      name: 'Alex',
      age: 28,
    },
    specialInfo: {
      military: true, 
    }
  });

  return (
    <>
      <div>
        <p>
          {userState.get().basicInfo.name}
        </p>
        <p>
          {userState.get().basicInfo.age}
        </p>

        <button onClick={() => userState.set(p => {
          return {
            ...p,
            basicInfo: {
              name: 'Alex',
              age: 29,
            }
          }
        })}>
          set age in basicInfo
        </button>
      </div>
    </>
  )
}
```

**Comment by avkonst** [comment]
There is more efficient way of doing nested prop set. Here is more information: https://hookstate.js.org/docs/nested-state#updating-existing-property

**Comment by avkonst** [comment]
In this case the most efficient would be:

```tsx
        <button onClick={() => userState.basicInfo.age.set(29)}>
          set age in basicInfo
        </button>
```

**Comment by avkonst** [comment]
> Would this be more efficient then?
> 
> ```
>         <button onClick={() => userState.basicInfo.set(p => {
>           return { ...p, age: 29 }
>         })}>
>           set age in basicInfo
>         </button>
> ```

Yes, more efficient, but not the most efficient. Better way is see my previous comment

**Comment by kkomaz** [comment]
Thank you!
