### ISSUE TITLE
Error: HOOKSTATE-107 when using useState

### ISSUE THREAD

**Issue by pho3nixf1re** [avkonst/hookstate#105]
I am newly integrating hookstate into a fairly fresh and simple project. Going of the global state example I setup a state object and then called `useState` on it. The `useState` call is throwing error 107, however, that error looks like it would happen when _using_ the state values incorrectly. It's never actually getting there. See example code at

The state: https://github.com/pho3nixf1re/cookbooks/blob/main/src/states/screen-title.ts
Error at: https://github.com/pho3nixf1re/cookbooks/blob/main/src/components/AppHeader/index.tsx#L19

Hookstate version is `3.0.1`.

**Comment by avkonst** [comment]
I think you have got react dev tools hitting this. It is known issue.

**Comment by avkonst** [comment]
see https://github.com/avkonst/hookstate/issues/90

**Comment by pho3nixf1re** [comment]
Confirmed, duplicated of #90 




On Oct 12, 2020 16:01, Andrey <notifications@github.com> wrote: 

see #90

**Comment by avkonst** [comment]
Fixed in 3.0.4
