### ISSUE TITLE
unwanted re-render behavior

### ISSUE THREAD

**Issue by jpodpro** [avkonst/hookstate#107]
i was initially very excited about this libarary. but in practice i've found that it simply does not deliver on its promise. as a result i've spent the last month fighting with it in my project. i have discovered that while simple examples seem to work, a larger global state results in a lot of incorrect and unwanted updates. it simply does not work the way i would expect. at this point i'm pretty close to the point of giving up on this entirely which is a shame from the hours of work i have spent. something tells me, despite wanting to avoid the FB koolaid, recoil is likely a better option.

in the following provided example i have 2 scenarios that trigger unwanted updates for no apparent reason:

in one situation i am setting a state property array to a new value which results in re-rendering all the objects that are hooked to a completely different state property's keys.

in another situation i am updating only one of a state's sub-properties and reading the rest. it still triggers updates to all of them even though it's only setting one. 

note that the unwanted updates can be seen in the console.

https://codesandbox.io/s/keen-christian-brxn9?file=/src/App.js

**Comment by avkonst** [comment]
I am not sure what exactly you wanted your action handlers to do, but I have tried to guess it and updated the code sample so it rerenders only what is necessary. Have a look here: https://codesandbox.io/s/vigorous-dawn-l3i6m
In my sample I pass the state to the child component and use the **scoped state** hook technique to achieve the most efficient rerendering: https://hookstate.js.org/docs/scoped-state

Note 1: There is still a way to do the same but keeping the handler functions in the App component (like you had), but the code would become a bit longer.

Note 2: There is also a way to pass a value of the item state to the child component and not use useState hook at all in the child component and still have only the affected fragments rerendered. It is possible with help of https://hookstate.js.org/docs/using-without-statehook

Regarding your concerns:
" i've found that it simply does not deliver on its promise"
> it delivers on promise and the promise about rerendering optimisation is documented here: https://hookstate.js.org/docs/performance-intro

> Your App component is rerendered because you "use" the entire state via `state` variable either during rerendering or in action callback handler. So, updating any of the variables would correctly cause the App component to rerender.

> Your code sample mirrors the pattern largely influenced by redux, where children component receive ids (paths to nested states) in props and hooks to the global state. Although it is possible and even documented how it would rerender in the https://hookstate.js.org/docs/performance-intro , I have given you the example of far more efficient and concise code.


"something tells me, despite wanting to avoid the FB koolaid, recoil is likely a better option"
> you have got the freedom choose. I can tell you that recoil rerenders more. In fact recoil would also rerender your App component in the similar way if you coded to hook to all state properties in the root App component. Recoil optimises relying effectively on selector functions, which reduce the scope of "used" data for each hook. Hookstate automates this and does not require selector functions. What recoil does not definitely give to you is the ability to pass state to children in props and effectively rehook to it in children components. See more here: https://hookstate.js.org/docs/scoped-state#it-is-unique

I can see your code is influenced by Redux like samples (for example - passing ids to children and requiring a child to hook to the global state again - this is very much like Redux forces you to do). Have a look a bit more into Hookstate code samples and you will start coding more elegant and more efficient code without battling much. Good luck.

**Comment by jpodpro** [comment]
first of all, your codesandbox link is identical to mine. i guess you didn't save your changes. my handlers aren't doing anything other than attempting to set a single state property and showing updates for all the unrelated states. i realize that doing this in the App component is causing itself to re-render thus rendering all the DateItems. I will have to add more detail.

indeed i have read over your docs MANY times. your examples are all well and good but in practice i find all sorts of confusing re-render behavior for components when i KNOW their states haven't actually changed. i've also never used redux. regardless, our record store is designed to efficiently use memory which means reduced lists of IDs instead of copying their large related objects in multiple places. this along with a global state should be no problem for a client state manager that works properly.

i will try to get a better working example. but i assure you there are all sorts of oddities happening. this may mean i'm not using hookstate properly, but the claim that it is a simple and obvious library is not the case in my project anyway.

**Comment by avkonst** [comment]
I checked it now in my phone. It is what I saved in pc. Could you please
check the sample once again?

Passing IDs is ok. I use IDs somewhere in my apps too.
