### ISSUE TITLE
Not compatible with hot reload?

### ISSUE THREAD

**Issue by parisholley** [avkonst/hookstate#109]
I haven't quite figured out a way to avoid error `HOOKSTATE-106`.

React will keep a component around that still has a reference to an old hookstate instance (eg: onClick), and cause problems. Is there a recommended way to deal with this? Obviously can't nest useState inside memo, etc...

**Comment by avkonst** [comment]
Hi,

This is react's limitation. I think react prints warning when you call `React.useState[1] - setState callback` for unmounted state. I think Hookstate should not throw but should print warning instead. It will make the behavior consistent with React native state hook. Would you be happy to make such a change and submit pull request?

**Comment by parisholley** [comment]
I'm not sure that it is a react limitation? This is how something would be implemented natively:

```react
const [state, setState] = useState(false);

return <MyComponent onClick={() => setState(true)} />;
```

In the above, i'd expect "state" to persist across hot reloads (and it works just fine). However doing it with hookstate:

```react
const state = useState(false);

return <MyComponent onClick={() => state.set(true)} />;
```

returns that error..

**Comment by avkonst** [comment]
Hi,

Hookstate uses useEffect which detects component unmount, which happens
sometimes on reload. This is causing the .set method to detect deleted
state.
I will have a look at what can be done about this, but after new year
holidays. In the meantime, please consider patching it by replacing the
exception by logging to console.warn.

**Comment by avkonst** [comment]
Release in 3.0.2

**Comment by avkonst** [comment]
Thanks for contribution.

**Comment by waleedshkt** [comment]
`106` **Error** still stems up randomly and occassionally in `v4.0.1` when `set`ting state on unmount component.
 
As you, @avkonst, proposed, I have pathed the code to prevent this error getting thrown and instead `log`ged it. I believe there is this to-do remaining as commented in the file.
