### ISSUE TITLE
Map function does not wait for promise resolution

### ISSUE THREAD

**Issue by sprucely** [avkonst/hookstate#117]
There is no easy way to register mutation actions when state is a Promise. The async encapsulation is nice. A simple fix could be to expose the promise as a State property, which could serve as a decent escape hatch for such needs.

**Comment by avkonst** [comment]
You can execute an action on promise resolution using this technique: https://hookstate.js.org/docs/asynchronous-state/#executing-an-action-when-state-is-loaded

**Comment by sprucely** [comment]
I considered that, but ultimately went with checking the isPromised property in an effect. An edge case where keeping a reference to the promise wouldn't work is when state comes from a third-party library.

**Comment by avkonst** [comment]
I am on leave. Will get back to it later

**Comment by avkonst** [comment]
"An edge case where keeping a reference to the promise wouldn't work is when state comes from a third-party library"
Could you please elaborate more on the usecase which you see does not work? Maybe code sample?

**Comment by avkonst** [comment]
Closing as there is no progress in the discussion.
