### ISSUE TITLE
INPUT loses focus onChange

### ISSUE THREAD

**Issue by zmagickap** [avkonst/hookstate#121]
I've implemented hookstate and imported it into a component.

The Input sets value and onchange to get and set of the state.

But every keypress causes the Input box to lose focus. It does SET the state and it shows up in another component. But, I have to click back into the Input after every keystroke.

I swapped out hookstate with react's useState and it works fine, without the Input losing focus.

Can you see where I've gone wrong here?

```
import React from 'react';
import { Input, InputGroup, InputLeftElement, Icon } from '@chakra-ui/react';
import { BsFillPersonFill } from 'react-icons/bs';

// States
import { useEmployeeState } from '../../States/EmployeeState';

// Components

function Username() {
  const employeeState = useEmployeeState();

  const handleOnChange = e => {
    employeeState.nbr.set(e.target.value);
  };

  return (
    <InputGroup>
      <InputLeftElement
        pointerEvents="none"
        children={<Icon as={BsFillPersonFill} color="gray.400" />}
      />
      <Input
        placeholder="Username"
        variant="Filled"
        borderColor="gray.500"
        size="md"
        width="100%"
        mb="3"
        value={employeeState.nbr.get()}  // <<<----- HERE
        onChange={handleOnChange}  // <<<----- HERE
      />
    </InputGroup>
  );
}
```

**Comment by zmagickap** [comment]
Is it because the page is re-rendering onChange?

Maybe I need to set up hookstate differently to keep that from happening?

But, I can't find anything in the docs that explain this.

If it helps, here's my createState code:

```
import { createState, useState } from '@hookstate/core';

const employeeState = createState({
  id: '',
  nbr: 'Hello',
  empName: '',
  remember: false,
});

export function useEmployeeState() {
  return useState(employeeState);
}
```

**Comment by zmagickap** [comment]
My pages have nested components, but I didn't think that mattered.

I enter the Employee Name here (though I have to click back in the Input box after each character). And it retains the values entered so far.

![hookstate1](https://user-images.githubusercontent.com/55907892/102960413-24092500-449f-11eb-814b-ef103d45b4a5.png)

And the state shows up on the following page (after a ROUTER link):

![hookstate2](https://user-images.githubusercontent.com/55907892/102960465-3e430300-449f-11eb-9589-0500cd094515.png)

**Comment by zmagickap** [comment]
I got it working, but I don't understand why the way I was doing it before didn't work. 

The sample project showed exporting useState of the createState, which is what I did (or tried to do).

I changed the code to export the state directly, and now it works. 

```
import { createState, useState } from '@hookstate/core';

const employeeState = createState({
  id: '',
  nbr: 'Hello',
  empName: '',
  remember: false,
});

export function useEmployeeState() {
  return employeeState; // <<<< ---- this is the change
}
```

and in the component:

```
import React from 'react';
import { Input, InputGroup, InputLeftElement, Icon } from '@chakra-ui/react';
import { BsFillPersonFill } from 'react-icons/bs';
import { createState, useState } from '@hookstate/core'; // <<<--- ADDED THIS

// States
import { useEmployeeState } from '../../States/EmployeeState';

// Components

function Username() {
  const employeeState = useState(useEmployeeState()); // <<<--- CHANGED TO THIS

  const handleOnChange = e => {
    employeeState.nbr.set(e.target.value);
  };
```

Can anyone see what I did wrong in the first set of code?

**Comment by avkonst** [comment]
You need to open react development tools and see re-rendering happening on keystroke. It is likely you have got a parent component which uses the same global state and it triggers rerendering for the entire page/app/parent component. 
Usually changes in form inputs should not be propagated to global state until they are confirmed, ie. intermediate state per form input field component might be a way to go.
