### ISSUE TITLE
Sagas for hookstate

### ISSUE THREAD

**Issue by hadynz** [avkonst/hookstate#122]
I've started playing around with hookstate in an application that I am currently building. I was off to a blitzing start as I was creating new states for many parts of my apps. 

However, as I started working on some more complex flows I ran into the following error:
`"Cannot flush updates when React is already rendering"`

As some commentators have [pointed out][1], this type of error happens when a change in state triggers update the dom before render cycle completes. In essence, I believe I fell into the trap of using hookstate to manage both state and side effects. For example, given this hypothetical hookstate state:

```js
const INITIAL_STATE = {
  status: 'idle',
  books: [],
};

const myState = createState(INITIAL_STATE);

export const useMyState = () => {
  const state = useState(myState);

  return {
    get books() {
      return state.books.get();
    },

    fetchBooks(){
      state.status.set('loading');
      service.getBooks()
        .then(books => {
          state.books.set(books);
          state.status.set('successful');
        });
    }
  }
};
```

In previous projects, I've managed to not get myself in such a situation by using something like Redux and [Redux-Sagas][2] together. The former is all about storing and manage state. And the latter is solely responsible for side effects (e.g. `fetchBooks` or network calls, logging, etc).

Has this project considered creating an interface to plug and play with Redux-Sagas, or creating something equivalent?

[1]: https://stackoverflow.com/a/58290679/80427
[2]: https://redux-saga.js.org/

**Comment by avkonst** [comment]
Hi, I use async load for state in lots of places and never seen a problem like this. I do it using this technique: https://hookstate.js.org/docs/asynchronous-state/

However, I seen such an error in 2 cases:

1. when async function, like `service.getBooks` resolves the promise immediately, ie. not an async really. In this case I fixed an async function with `setTimeout(0)`. But this is likely not your case.
2. when you set the state within render function. This is your case: `state.status.set('loading');`  You would have exactly the same problem with standard React useState hook too. Setting the state on render is not the right pattern for react. However, if you need to do this, you can simply wrap the state set action in `setTimeout(() => state.status.set('loading'), 0)`.

**Comment by hadynz** [comment]
Sure. `setTimeout` will resolve these types of issues for [known reasons][0]. But it won't be conducive for the long term health of my app.

Just a suggestion for you as a maintainer of this library, to consider something in the roadmap to facilitate asynchronous flow similar to what Redux-Sagas or [MobX-state-tree async-actions][1] do. This issue is considerable enough for my use case that I am looking to move off hookstate to something more opinionated that will ensure I don't mix up state management with async flow, and won't end up down the track of tactical solutions such as `setTimeout` and `useEffect` that would solve the immediate problem for longer term maintainability. 

[0]: https://stackoverflow.com/a/779785/80427
[1]: https://mobx-state-tree.js.org/concepts/async-actions

**Comment by avkonst** [comment]
Sure. You can achieve the same with Hookstate. If you do not like setting the state to a promise directly, actions and whatever background jobs you want to associate with a state can be attached to the state using plugins interface: https://hookstate.js.org/docs/writing-plugin 
In any case what you need to make sure is that the state is not set on render. This is why mobx flow is all about async functions. Notice, that setting the state status to loading is done in an async function, for example `fetchProjects: flow(function* fetchProjects() {...}`, which is not not done on render cycle. Make your `fetchBooks()` function body invoked asynchronously, like mobx flow does, and you are all served in the similar way. I do not see Hookstate needs to deliver something special to achieve this. If you see it needs, I think it can be done in a plugin. You are welcome to experiment and contribute such a plugin

In general, I see that the rendered component (view) should follow changes in the state (model), which is mutated on actions / events such as user interactions, network data, etc.. The fact that something is triggered for rendering is not a reactive event, it is the other way - rerendering follows state changes, which is triggered by actions. This is React one-way flow, I think. Did they call it Flux architecture?
