### ISSUE TITLE
Nested state selectors

### ISSUE THREAD

**Issue by rjkz808** [avkonst/hookstate#129]
Awesome library, going to try it out in the near future.
I have a question about state selectors - in `react-redux`, it was possible to do something like that:

```js
const nestedValue = useSelector(state => state.a.b.c.d);
```

`useSelector` guaranteed that the component will not re-render if `d` value remains the same after some state update.

My question is: how the same thing could be done with `hookstate` library?

**Comment by avkonst** [comment]
Hookstate does not need selectors, because it tracks what fields are used by a component automatically. And optimizes rerendering accordingly, ie. skips rerendering those components which do not use an update field.

**Comment by avkonst** [comment]
More here https://hookstate.js.org/docs/nested-state, here https://hookstate.js.org/docs/scoped-state and here https://hookstate.js.org/docs/performance-intro

**Comment by avkonst** [comment]
Reopen if you have got more related questions.
