### ISSUE TITLE
merge() breaks previous/current state comparison in onSet() callback

### ISSUE THREAD

**Issue by ryanwillis** [avkonst/hookstate#132]
Howdy! Thanks for this amazing library.

To reproduce the issue: [https://codesandbox.io/s/hookstate-merge-issue-50u04](https://codesandbox.io/s/hookstate-merge-issue-50u04)

If you update a state using `merge()`, the `previous` value will match the `state` value in the `onSet()` callback. I'm assuming this isn't desired behavior but please correct me if I'm wrong. Thanks in advance!

**Comment by avkonst** [comment]
Hi. First of all plugin id should be a global variable: `id: Symbol("MyCustomPlugin")`. Otherwise you will create lots of plugins with different ids (although all of them will have the same debug representation).

Regarding your issue: yes, `previous` and `state` will be the same object but there is one more argument indicating if it was a merge and what value it merged in:

```
onSet: (p: any) => {
            if ("state" in p && "previous" in p) {
              console.log("PREVIOUS", p.previous);
              console.log("CURRENT", p.state);
              console.log("MERGED", p.merged);
            }
          }
```

**Comment by avkonst** [comment]
I think it was done this way to avoid copy of an object (which is potentially compute expensive operation and not strictly defined in JS). I guess the current behaviour limits the access to the real previous value for a plugin, if you want to trace it.... Not sure if it should be changed. What is your use case?

**Comment by ryanwillis** [comment]
Thanks for you response! Plugin ID is global in my local code but I just threw it in there for the example code, my bad.

Use case: I'm throwing together a persistence plugin that uses Capacitor's Storage and allows you to pick and choose which values to persist via an allow/block list. The plugin pares down the previous and current state to only the values specified in the list and compares them. If they're different, the changes are stored.

The idea being that I can have a global state that also includes notices or other temporary values used by many components but that don't have to be persisted.

**Comment by ryanwillis** [comment]
I was hoping to avoid having to pull the existing value from storage to compare. The `merge` value tells me what was set but doesn't tell me if those values were different than what was there before.

**Comment by avkonst** [comment]
Understand. I think it is impossible to guarantee that previous value is not modified in a general case. Merge() like the following:

```tsx
state.merge({
    field: 'new value for field',
    fieldToDelete: none
})
```

is only a syntax sugar for (roughly):
```tsx
state.set(p => {
    p.field = 'new value for field';
    delete p.fieldToDelete;
    return p;
})
```

As you can see a user can write any sort of state mutations which will get passed as previous. Maybe it is unfortunate side-effect but it was done mutable to allow for better performance.

You can workaround it by using only `immutable style` of state update in your source code. For example the same thing can be written as:

```tsx
state.set(p => {
    let copy = p.clone(); /// here it is up to you to define how to clone the current state
    copy.field = 'new value for field';
    delete copy.fieldToDelete;
    return copy;
})
```

If you would like to optimise re-rendering (for example your state includes lots of fields, which are used in may other components and you are merging only two), you can do it like this:
```tsx
state.batch(s => {
    s.field.set('new value for field')
    s.fieldToDelete.set(none)
})
```
This way you cherry pick what you update and it will let you to access the previous state correctly.

Will it work for you?

**Comment by avkonst** [comment]
... and batch actions also have got callbacks in a plugin

**Comment by avkonst** [comment]
and if you like the library, please, spread few words about it or write a blog or twitter post. It will help the project to grow. Thanks

**Comment by ryanwillis** [comment]
Ahh I had not considered mutability here. What you say makes sense and using the immutable-style `set` will allow me to continue with my project.

A note in your API docs about this effect may be worthwhile as the `merge` context seems to render the `previous` value pretty much moot.

This has been a great state management implementation experience otherwise, I'll definitely be spreading the word.

**Comment by avkonst** [comment]
Ok. I will keep it open until the docs are updated. Feel free to contribute the update to the website docs (written in markdown) and typescript docs. I will merge your pull request.
