### ISSUE TITLE
Can't use state object in React Hooks dependencies.

### ISSUE THREAD

**Issue by anirudh-wal** [avkonst/hookstate#133]
@avkonst This library is awesome and recently, I started using it in a project. But, I found a huge issue that could break my usecase.

When I am trying to use the state in react hooks dependencies, it is still calling the dependency on every re-render. I need to find a solution to this.

**NOTE: Please do bear in mind that the example could be a bit naive.**

Eg: 
```
import {useState as useHookState} from "@hookstate/core"

const Item = () => {
  const {itemId, items} = props;
  const itemsState = useHookState(items);
  
  // This useEffect will trigger for every re-render
  useEffect(() => {
    console.log("setting item here")
    setItem(itemsState.get().find(item => item.id === itemId))
  }, [itemsState])
  
  return(
    // Rendering the item data here
  )
}
```

**Comment by avkonst** [comment]
It is a bit unclear from your example what setItem function is and what type of `items` variable is, so I can not be sure with my answer, but why do not you use the following instead?

```tsx
import {useState as useHookState} from "@hookstate/core"

const Item = () => {
  const {itemId, items} = props;
  const itemsState = useHookState(items);
  
  // This useEffect will trigger ONLY when 
  let itemsStateValue = itemsState.value;
  useEffect(() => {
    console.log("setting item here")
    setItem(itemsStateValue.find(item => item.id === itemId)) 
  }, [itemsStateValue])
  
  return(
    // Rendering the item data here
  )
}
```

**Comment by anirudh-wal** [comment]
@avkonst 
The items would be an array and we can assume setItem as a normal React.useState.
Updated Example: 
```
import React from "react";
import {useState as useHookState} from "@hookstate/core";

const Item = () => {
  const {itemId, items} = props;
  const [item, setItem] = React.useState();
  const itemsState = useHookState(items);
  
  // Still have to add itemState.value in dependenct list of useMemo, which would do an infinite loop
  let itemsStateValue = useMemo(() => itemsState.value, []);

  useEffect(() => {
    console.log("setting item here")
    setItem(itemsStateValue.find(item => item.id === itemId)) 
  }, [itemsStateValue])
  
  return(
    // Rendering the item data here
  )
}
```
The above thing works, but the `itemsState.value` should also be wrapped inside a useMemo for the above to work, which might need me to add that state in the useMemo dependency list.
If I don't wrap it, the useEffect is being trigged every time and going into an infinite loop somehow.

**Comment by anirudh-wal** [comment]
@avkonst 
If we consider React useState hook, it returns a setter, which need not be added to any dependency, because it will get initialized on the initial render. I assumed the same for this state object/interface that the hookstate returns, but it looks like that's not the case. I have a use-case where, I have a global state which I am initializing locally and I need to set some other state only if the value of some nested object changes. 
The example above can be considered as a crude one and almost suits my use-case.

**Comment by anirudh-wal** [comment]
@avkonst 
Basically, what I am trying to say is, I want to listen to changes made in the state(nested), but adding them in dependency hooks to listen, is not working and going to infinite loops somehow. 😞

**Comment by avkonst** [comment]
Try this: `let itemsStateValue = itemsState.attach(Downgraded).value`

**Comment by anirudh-wal** [comment]
@avkonst The above thing works like a charm. Looks like my use case is a little more complex than the example here.
But there is one use-case and it's causing me confusion. If I have a nested state and I scoped it, I still need to downgrade it before using its value like above, if I want to use that in the dependency array.

**Comment by avkonst** [comment]
That is correct. You scope it to prevent rerendering than other props change outside of your component with the effect. And you attach downgraded to the scoped state. This way you get the original object behind the state which is not wrapped in a proxy. Please notice that react does shallow compare for dependency list. It means your object for dependency may or may not be the same, depending how you update it.

**Comment by avkonst** [comment]
See related https://github.com/avkonst/hookstate/issues/140
