### ISSUE TITLE
React Hook useEffect has a missing dependency

### ISSUE THREAD

**Issue by TroyJoachim** [avkonst/hookstate#137]
```
import { useState } from "@hookstate/core";
import { useEffect } from "react";

export default function App() {
  const state = useState("whatever");

  useEffect(() => {
    state.set("foobar");
  }, []);

  return (<></>);
}
```
Linter warning:
`React Hook useEffect has a missing dependency: 'state'. Either include it or remove the dependency array. (react-hooks/exhaustive-deps)`

The reason I'm updating the state in the effect is because I'm fetching data and updating the state when it comes back. I just didn't include that in the code above.

I don't want to pass in state into the array because I don't want it to re-render every time the state changes. Is there a way to do this without disabling the linting rule?

**Comment by avkonst** [comment]
It is React thing. You can ask the same question about any other variable, not necessary state variable. As far as I know you can disable a specific lint rule per line.

**Comment by cristi-shoreline** [comment]
@TroyJoachim Why don't you just set the state on fetch success? Give to the state or a property of the state some initial values, and the set the state whenever needed.

**Comment by avkonst** [comment]
Please notice that hookstate supports asynchronously loaded states. Check the docs. It is all very easy to use

**Comment by avkonst** [comment]
Please see above the updated answer on how to stabilize set method across rerender cycles.

**Comment by avkonst** [comment]
Leave it open to think if this request can be addressed by a more generic plugin.

**Comment by avkonst** [comment]
"Is there a way to do this without disabling the linting rule?" as @TroyJoachim suggested, set the state when it is fetched. You can also check if hookstate's built in support for async state would help in your case.
