### ISSUE TITLE
Merge persisted state with the initial state

### ISSUE THREAD

**Issue by cristi-shoreline** [avkonst/hookstate#138]
I think I just encountered an interesting scenario with the Persistence plugin, as described below.

Let's say I have a state that's persisted in the LocalStorage:
```js
const state = createState({
  part1: { some: 'field' }
})
```

And I'm passing the state's `part1` to a component, that's using `useState(state).part1`, and then I change the state's structure to have a `part2` nested state:
```js
const state = createState({
  part1: { some: 'field' },
  part2: { some: 'field2' },
})
```

When I pass the state's `part2` to the same component (I'm using the component twice), I'm getting a `Cannot read property 'part2' of undefined`.

I assume that's because of setting the state here https://github.com/avkonst/hookstate/blob/master/plugins/Persistence/src/Persistence.ts#L13 (with `set`) instead of probably merging it with the initial one.

This is just a small example, but it can bring a lot of trouble in production for users having a different state shape in the LocalStorage, set by a previous version of the software that suffered changes with a new version.

Maybe a validation against the current state could be handy, even if it means that the state is reset to the initial one if the validation fails.

Any thoughts?

_I'd be more than happy to provide a broader example._

**Comment by avkonst** [comment]
Hi,

Fetch of a state (previously persisted by old software) by new software is a typical problem in software engineering. Usually the solution is easy and may require to use only `version` field. Although version handling can be moved down to the plugin level, it can also be handled by an application.

If it is on the plugin level, it could require a migrate function (like for the IndexedDB). I actually written in the past a plugin to persist into IndexedDB (persist very large state with frequent changes) and with migration function callback and version handling on a plugin level, but never published it to open source as it was more coupled with other non-generic code. But a generic version can be done to have more high performance and more feature rich persistence plugin.

If version handling is on the application level, you could simply achieve it with the following structure:

```tsx
interface PersistedValue {
    version1: Option<PersistedValueV1>,
    version2: Option<PersistedValueV1>
    ....
}

// to use it, for example:
let myState = createState<null | PersistedValue>(null);

interface PersistedValueV1 {
    part1: whatever,
}

interface PersistedValueV2 extends PersistedValueV1 {
    part2: whatever,
}
```
Once your app reads the state, it could detect if it is written by version 1 or version 2 and use the corresponding typesafe structure accordingly. You app could also migrate the state from version 1 to version 2 on app load, for example.

**Comment by cristi-shoreline** [comment]
Thanks, @avkonst! It makes sense, so we actually have a couple of options here:

One would be to have a granular persisted state, like `part1State.attach(Persistence('app-part1'))` and `part2State.attach(Persistence('app-part2'))`, and whenever a smaller part of the state is not used anymore, it will simply not break the functionality as it will not be read from the LocalStorage.

The second option could be a custom persistence plugin, written for the app needs, where to handle different versions, a custom merge, migration functions, validations, and/or whatever else is needed to make sure it does not break the functionality.

**Comment by avkonst** [comment]
A plugin is attached once per state root. I do not think it will work with
attaching the plugin twice to substates

**Comment by cristi-shoreline** [comment]
Not even for such an example?

```js
const appState = createState({
  part1: { title: 'Part 1' },
  part2: { title: 'Part 2' }
});

const Component = ({ state, persistenceKey }) => {
  const localState = useState(state); // Hookstate's
  localState.attach(Persistence(persistenceKey));
  
  return <>{localState.title.value}</>
}

const Wrapper = () => {
  const app = useState(appState);  // Hookstate's
  return (
    <Component state={app.part1} persistenceKey="app-part-1" />
    <Component state={app.part2} persistenceKey="app-part-2" />
  );
}
```

**Comment by avkonst** [comment]
Sorry, I misunderstood your previous proposal. This last example seems ok
and should work.

**Comment by cristi-shoreline** [comment]
Thanks a lot for the clarification, @avkonst! I appreciate your effort!
