### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by filipzava** [avkonst/hookstate#142]
Hi, 
since v3.0.2 I get this error: `index.es.js:195 Uncaught ReferenceError: process is not defined`
For bundling I am using `parcel` if it is related. 

![image](https://user-images.githubusercontent.com/12759049/109027224-dab49c00-76c0-11eb-92a3-c29ab5277aa5.png)

**Comment by avkonst** [comment]
Hi, you need to adjust your webpack config. See details here: https://github.com/avkonst/hookstate/issues/118
This issue is duplicate.

**Comment by avkonst** [comment]
Please reopen if 118 does not answer your question. Although you might research how to configure webpack in your environment as I am not familiar with it.

**Comment by avkonst** [comment]
https://github.com/avkonst/hookstate/issues/193

**Comment by avkonst** [comment]
https://github.com/avkonst/hookstate/pull/207
