### ISSUE TITLE
Little grammar mistake on the Demo App

### ISSUE THREAD

**Issue by jctaveras** [avkonst/hookstate#148]
I was just reading the documentation and I have to say this State Manager is simple and easy to set up with minimal boilerplate. However, I can't help but notice that there is a small grammar error on this line.

https://github.com/avkonst/hookstate/blob/5e4debae01447bde510f604d006c3e810d548f8a/docs/demos/todolist/src/components/TasksTotal.tsx#L7

I just wanna say thanks for this awesome package and hope I can integrate it into future production projects 🚀

**Comment by avkonst** [comment]
Thank you for your contribution
