### ISSUE TITLE
How to listen a state change ?

### ISSUE THREAD

**Issue by avovetisa** [avkonst/hookstate#153]
Hi !

First of all, thanks you very much for this awesome library ! This lib solves the problem of the time consuming use of Redux ! It also make me think of the VueJs way of managing state.

I have a question, is it possible to listen for a state change ?

Im implementing a dialog, with a "Yes, No" question. My Dialog component is at the top Level of my app and I set the answer in the global state of the app using hookstate, and in a child component I would like to listen when the state change, to know when the user click on yes or no.

Do you know how Is it possible to achieve this ?

Thanks you very much.
Marc.

**Comment by avkonst** [comment]
It is easily possible: https://hookstate.js.org/docs/writing-plugin
This is the callback you are interested in particular: https://hookstate.js.org/docs/typedoc-hookstate-core#optional-readonly-onset
