### ISSUE TITLE
Removing item on array return "TypeError: Cannot read property 'key' of undefined"

### ISSUE THREAD

**Issue by edsulaiman** [avkonst/hookstate#155]
### Description
I am using the [fluent UI package](https://github.com/microsoft/fluentui) to display the table and the data comes from the state. Initially, I thought this was a bug in the fluent UI, but when I did the troubleshooting, I found that deleting items in the array using "hookstate" gave an error whereas using "useState from react" gave no errors at all. I conclude that this is a bug in the hookstate package

### Steps to Reproduce

1.  Copy this code
```
import {
  DetailsList,
  IColumn,
  PrimaryButton,
  SelectionMode,
} from "@fluentui/react";
import { useHookstate } from "@hookstate/core";
import { useState } from "react";

function ItemPage() {
  interface IItem {
    itemName: string | undefined;
    barcode: string | undefined;
    stock: number | undefined;
  }

  let columns: IColumn[] = [
    {
      key: "column1",
      name: "Item Name",
      fieldName: "itemName",
      minWidth: 75,
      maxWidth: 250,
      isResizable: true,
    },
    {
      key: "column2",
      name: "Barcode",
      fieldName: "barcode",
      minWidth: 75,
      maxWidth: 250,
      isResizable: true,
    },
    {
      key: "column3",
      name: "On Hand",
      fieldName: "stock",
      minWidth: 75,
      maxWidth: 150,
      isResizable: true,
    },
  ];

  // HookState
  const itemsHookState = useHookstate<IItem[]>([
    {
      itemName: "Item 1",
      barcode: undefined,
      stock: 0,
    },
  ]);

  // React useState
  const [itemState, setItemState] = useState<IItem[]>([
    {
      itemName: "Item 1",
      barcode: undefined,
      stock: 0,
    },
  ]);

  const clearItem = () => {
    itemsHookState.set([]);
    setItemState([]);
  };

  return (
    <>
      <PrimaryButton onClick={clearItem}>Clear Item</PrimaryButton>

      {/* HookState */}
      <DetailsList
        items={itemsHookState.get()}
        columns={columns}
        selectionMode={SelectionMode.none}
      ></DetailsList>

      {/* React useState */}
      <DetailsList
        items={itemState}
        columns={columns}
        selectionMode={SelectionMode.none}
      ></DetailsList>
    </>
  );
}

export default ItemPage;
```
2. click the "Clear Item" button
3. try to comment DetailList  which use hookstate
4. click the "Clear Item" button

### Expected Behavior
Item will be removed from the table 

### Actual Behavior
Hook state return TypeError: Cannot read property 'key' of undefined

### Basic Information

- NPM Package: 
1. "@hookstate/core": "^3.0.6", 
2. "@fluentui/react": "^8.5.0"

### Environment
1. Visual Studio Code 1.54.3
2. NPM 7.5.3
3. Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by edsulaiman** [comment]
After many trials I found a solution, the problem is that the get function on the hookstate does not return the actual object value, in some packages, it will give an error. 

To solve this problem we can use the following function to retrieve the actual value from the state. see #136 
````itemsHookState.attach(Downgraded).get()````

the same problem also occurs if we change the property whose value is passed down from the parent component using the hookstate, for example:

````

interface INumber {
  numberValue: number;
}

function ParentComponent() {
  const numberState = useHookstate<INumber>({numberValue: 0});
  return (
    <ChildComponent numberProps={numberState.get()}/>
  );
}

function ChildComponent({ numberProps }: { numberProps: INumber }) {
  return (
    <button
      onClick={() => {
        numberProps.numberValue += 1;
        console.log(numberProps.numberValue);
      }}
    >
      Click Me
    </button>
  );
}
````

when we click the button, it will give us this error: 
`Error: HOOKSTATE-202 [path: /]. See https://hookstate.js.org/docs/exceptions#hookstate-202`

**Comment by avkonst** [comment]
Update the state object directly is incorrect operation as it is not observed by state management library and it would not rerender.
