### ISSUE TITLE
Exporting state duplicates

### ISSUE THREAD

**Issue by aldintalic** [avkonst/hookstate#156]
Hello there
 
I'm currently running in a problem when exporting my state. The wrapper creates new instances for every "useSmallStateContext" in the components. Therefor the useEffect is triggered four times, one for every component. 
This problem does not occur in Version 2 where we would use the wrapper in the map function. What am I missing here? I cannot use useMemo and every other way I tried I either ran into "hooks can only be used in function components or custom hooks"(invalid-hook-call) 
There probably is some easy way to do this as I do not think I'm the first one to run into this problem. 
Or is that working as intend?
 
Greetings, and thx for this awesome lib!

```tsx
import { createState, State, useState as useHookState } from "@hookstate/core"
import React, { useEffect } from "react"
 
const TestPageContent: React.FunctionComponent = (props) => {
 
    return (
        <>
            <SmallStateComponent />
            <SmallStateComponent />
            <SmallStateComponent />
            <SmallStateComponent />
        </>
    )
}
 
export default TestPageContent
 
function SmallStateComponent() {
    const smallStateContext = useSmallStateContext()
 
    return <div>Count: {smallStateContext.getCount()} <button onClick={() => smallStateContext.incCount()}>Inc Count</button></div>
}
 
interface SmallStateValues {
    count: number
}
 
const getSmallStartValues = (): SmallStateValues => {
    return {
        count: 0
    }
}
const smallState = createState<SmallStateValues>(getSmallStartValues())
 
export interface SmallStateContext {
    getCount: () => number
    incCount: () => void
}
 
const useSmallStateWrapper = (state: State<SmallStateValues>) => {
    const blub = state.value.count
    useEffect(() => {
        console.log("smallStateWrapper", blub)
    }, [blub])
 
    return ({
        getCount: () => {
            return state.value.count
        },
        incCount: () => {
            state.set(prev => {
                prev.count++
                return prev
            })
        }
    })
}
 
const useSmallStateContext = (): SmallStateContext => useSmallStateWrapper(useHookState(smallState))
```

**Comment by avkonst** [comment]
Sorry, I am a bit lost. You are using the custom hook in you component. The custom hook wraps useEffect hook. You mount the component 2 times, so you get 4 times used custom hook, so 4 times underlying useEffect. What is wrong?
How do you want it to work exactly?

**Comment by aldintalic** [comment]
Thx for the fast answer 
Let's see, english is not my native tongue, so it's a bit difficult to phrase my thoughts.
What I want/need is a single wrapper beeing used by all custom hook usages, as was the case in V2 (at least my tests showed that)

`const useSmallStateContext = (): SmallStateContext => useHookState(smallState)[self].map(useSmallStateWrapper)`

When I think of a "global state", I don't want multiple "wrapper" doing the same stuff, but only one. Like e.g. in the example code I'd only want to have a single reaction(useeffect trigger) to the counter reaching a specific amount. Not for every usage of the custom hook. That defeats the purpose of "global state". 
Sure, it may be possible to have the useeffect somewhere outside of the customhook, but I'd like to have this in one place.

**Comment by avkonst** [comment]
"Like e.g. in the example code I'd only want to have a single reaction(useeffect trigger) to the counter reaching a specific amount. Not for every usage of the custom hook. "

> you can manipulate the global state or run actions outside of the custom hook

"Sure, it may be possible to have the useeffect somewhere outside of the customhook, but I'd like to have this in one place."

> So you want things to be in one place and does not want this place to be executed in each component, right? then the options for you is not to call this from the places where you do not want it to be used...

**Comment by aldintalic** [comment]
Maybe it's more helpful to describe what we want to achieve. We have a site where we can do a search with different parameters. The parameters can be changed in different components. And the results can also be used in different components (e.g. listing and number of results separately).
My idea was to use a hookstate as a central place to handle this parameter/result handling. I'm exporting things like "nextPage" and "getResults" or "getResultCount".
The useEffect then should be dependent on the parameters and handle the request. Currently those requests, because of the problem mentioned above, are done multiple times (e.g. for every component where we want to show those results.)
We also looked into nested state, but the components are on very different parts of the hiearchy.
 
Maybe that's the wrong aproach altogether and doesn't have to do with hookstate. We are kinda new to the react kind of way.

**Comment by avkonst** [comment]
What you are trying to achieve is very usual use case in frontend development. Of course, React and Hookstate can deal with it easily. Here is the short guideline:

Define the state where you will hold your mapping of input params to search results, for example:

```tsx
// I assume search param is a string, and search result is an array of strings
// and I set the initial state to empty results
let state = createState<Record<String, Array<String>>>({})
```

In your render component, say it is named `SearchResultsList` and input parameter is `searchBy` string.
- mount the state using useHookState
- check if the state already includes the entry for the given search params
- if it does, use it to render the list and return
- if it does not, render another custom component, let's name it `FetchSearchResult`

Your `FetchSearchResult` component would need to do the following:
- useEffect to spawn async call to get the search results. OR better and simpler use ***local*** state with async state support by Hookstate: https://hookstate.js.org/docs/asynchronous-state
- return render result the string like 'Searching...'
- once the fetch is completed, update the global state with new search result entry. This will trigger rerender for `SearchResultsList`, which will render the list instead of calling `FetchSearchResult` again

Hope it helps.

**Comment by aldintalic** [comment]
@avkonst Sorry for a late answer, I was on a vacation.. I just want to thank you for nice and detail explanation. I am sure it will help me to solve my problem. I really appreaciate your help, thanks 👍 

Best regards.
