### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [avkonst/hookstate#161]
Any performance difference to this?

https://github.com/dai-shi/react-tracked

**Comment by avkonst** [comment]
I did not measure. But as far as I know
1. it deals with immutable data, which requires data clone on set and it is more expensive operation than just a property assignment done by Hookstate.
2. identification of updated parts of a state involves deep nested comparison of 2 objects, old and new state values, which does not scale well with the growth of the state. Hookstate identifies updated segments with nearly `O(1)` speed/scalability (which means takes the same amount of computation regardless of a size of a state) as `.set()` operation directly points to the updated part of the state and Hookstate uses this information.

Hope it helps.

**Comment by avkonst** [comment]
cc: @dai-shi

**Comment by dai-shi** [comment]
For controlled benchmark, https://github.com/krausest/js-framework-benchmark is something you can see.

I investigated the first version of hookstate, but it looks like it's changed a lot, so I'm not confident to say anything about it.

For my projects, which are also changed a lot, here's random comments:
- react-tracked is for "automatic" render optimization for react context, react-redux, zustand and possibly others.
- react-tracked is based on immutable data model the same as bare react.
- react-tracked for react context is based on [use-context-selector](https://github.com/dai-shi/use-context-selector), so without render optimization, it might be more comparable with hookstate.
- however, use-context-selector does some extra work for concurrent mode compatibility, so its benchmark result may not be very good. Our hope is eventually react itself will provide the similar api.
- for O(1) updates, I'm working on [jotai](https://github.com/pmndrs/jotai) lately.


Finally, performance is a hard topic and it depends on requirements, so it's best to measure.

**Comment by hp8wvvvgnj6asjm7** [comment]
Well interesting! Thank you all.

Anyone looked into DOD?
It seems that certain Patterns from game development are entering the web.

https://m.youtube.com/watch?v=yy8jQgmhbAU

Hope it's useful info.

Cheers

**Comment by avkonst** [comment]
I am data architect at my job. I know about data. Data oriented design is a pattern, you may or may not apply / use. Hokstate hook is an utility which you may or may not use regardless of what pattern you choose to manage (load, process, share, etc.) your data and complexity of your software.

You do not need to wait for anything specific done for the web to start using the DOD pattern now. Many tools are already there. And many tools which offload high CPU demanding tasks down to the lower layers on the stack, most are done transparently for you by the browser engine.

I also doubt you will see a significant impact by optimizing your app at the pure JavaScript level when React (or other similar framework) will drain most of compute resources anyway. At least any optimization without measurements would be considered as a premature optimization, which is better to avoid.

Regarding lower level optimizations at the level of below JSVM/JVM, I like what Rust programming language gives to users as well as it fixes a lot of flaws of C/C++ languages.

Good luck.
