### ISSUE TITLE
transitioning from useContext

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [avkonst/hookstate#162]
Hi, 

I'm using `useWebsocket` in my current Project and had the return callback `sendJsonMessage` inside my global state like

```
export default () => {
 const {sendJsonMessage} = useWebsocket() // this should be used only one time
 return <SomeProvider value={sendJsonMessage}>
}


---

SomeCompoent = () => {
 const {sendJsonMessage} = useContext()

 ... sendJsonMessage('hookMyState!')
}
```

what's your recommended way of making this function available to multiple components?

My Solution:

What I'm did now is a weird workaround by using a component to SET the callback inside `useEffect( ,[])` into the global state so it can be used anywhere. 

---

**Comment by avkonst** [comment]
Context for accessing websocket is the perfect solution. What is wrong with?

**Comment by hp8wvvvgnj6asjm7** [comment]
hmm, now that you say it.. nothing wrong with it lol

**Comment by avkonst** [comment]
No, it will not rerender the whole tree as you are not modifying the state. You only use the state value, which is a function.
Hookstate can hold functions as data with help of `Downgraded` plugin, and you can put websocket function into a global state, but I do not see a point, if this piece of data does not change in the app and just forwarded to children.
