### ISSUE TITLE
question: how is state stored globally?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [avkonst/hookstate#164]
I'm really fascinated by this library and making it a default for all my react projects.
How do consumers find the provider they have to subscribe to? 

In React `createContext` you need to wrap everything around a Provider, yet in `hookstate` we don't need this anymore.
How is the connection being made? Where is the state stored in order to be found by its consumers?

**Comment by avkonst** [comment]
1. there is no need for a provider, so NO needs to do createContext and mount a provider in the root of an app
2. the state is store in a variable behind the object which you get as a result of `createState`. Components or any other code just needs to have access to this variable to use / update the state, like any other global variable in JavaScript.

**Comment by hp8wvvvgnj6asjm7** [comment]
love the simplicity.
