### ISSUE TITLE
Hookstate vs MobX vs Recoil

### ISSUE THREAD

**Issue by qwertie** [avkonst/hookstate#167]
I'm trying to choose a state-management library and wondering: what are the differences, pros and cons of Hookstate vs other reactive state management libraries?

My first impression is that Hookstate is more intuitive and slightly easier to use than Recoil, but Recoil has a concept of "selectors" (dependent/computed state—can't imagine why they don't call it "computed" or "dependent") and I haven't seen that feature in the Hookstate docs. Hookstate and Recoil both appear to be React-specific while MobX is not (I count that as a point for MobX).

But I haven't researched MobX and Immer enough to understand the differences between them and other options.

**Comment by avkonst** [comment]
The fact that Mobx is not react specific does not give you any bonus, really. Switching the UI framework gives far more problems than porting state management. Last time I checked, Mobx did not have decent performing hooks for React. It was great with traditional class-based react components, which gradually disappear now.

Apart from being easier than Recoil, Hookstate supports the most notable concepts of "writable component props" and "scoped state" which makes handling of deeply nested state very easy and efficient. There is no other state management library offering this. Hookstate has got a pending ticket https://github.com/avkonst/hookstate/issues/140 which might be important in some cases, but it is rare thing (note: useEffect, memo, etc are supported for hookstate state values, the ticket is about supporting the hookstate state objects itself). Hookstate supports devtools. As far as I know there are no devtools for Recoil, but things might changed recently. Hookstate does not support concurrent updates yet, but it will once React API becomes stable for this feature.

Hookstate does not need selectors as it tracks automatically what parts of a state you used ("selected") during rendering. It is another advantage of the Hookstate over Recoil. Also, state selectors can scale with `O(n)` scalability at best, when number of subscribed components grows. Hookstate automatic state usage tracking delivers nearly `O(1)` performance (here are 10000 cells subscribed to the table state):  https://hookstate.js.org/docs/scoped-state and this one: https://hookstate.js.org/docs/performance-frequent-updates

Hope it helps.

**Comment by avkonst** [comment]
Also see this: https://areknawo.com/top-5-react-state-management-libraries-in-late-2020/

**Comment by qwertie** [comment]
> Hookstate does not need selectors as it tracks automatically what parts of a state you used

This does not imply that a dependent/computed state concept is unnecessary.

Other libraries I am aware of that automatically figure out which components to update (MobX and Recoil for JS, Update Controls and Assisticant for C#) all have some kind of mechanism to represent dependent/computed state.

**Comment by avkonst** [comment]
If you need computed state, just compute it and assign to a variable,
Hookstate will figure out what you used for computed state automatically.
Other libraries complicate  things for various reasons, it is not necessary
that Hookstate should copy it.
