### ISSUE TITLE
Sorting in hookstate

### ISSUE THREAD

**Issue by wrb94** [avkonst/hookstate#175]
I've been checking out this library and tried to implement Todo app with sorting but I have faced a problem. Where sorting should be implemented? In parent/displaing component or maybe in `*State.js`?

1. I assumed it should be done in latter but I had problems with returning correct Proxy wrapper. I only wanted to override `get` method to do sorting for me (sort method was saved in another state) and I wanted to leave other methods untouched. It wasn't possible with rest operator and  yours example on exposing state indirectly [(example)](https://github.com/avkonst/hookstate/blob/master/docs/demos/todolist/src/components/SettingsState.ts) only provides primitive state. Can you provide some suggestion on where sorting should be implemented and example for indirectly exposed nested state?

2. I've implemented sorting in my display component like this `[...todosState.get()] .sort(getSortingFunction(sortByState.get()))`.  I believe it is not the best way or expected to do it. Do you have any propositions how it should be done for now and any plans how to improve this in future?

Thanks for good work in creating this library. I really appreciate this!!!

**Comment by avkonst** [comment]
"sort method was saved in another state"

> As of today you can not save functions in the state object. See: https://hookstate.js.org/docs/nested-state/#limitations-for-state-values

"I believe it is not the best way or expected to do it."

> Why do you think it is not the best way? State of an array is an array of states. Since it is an array, you can sort it.

**Comment by wrb94** [comment]
1. I didn't mean sort function but enum that distinguish which sorting method to use

2. I previously used `redux-toolkit` and they provide `sortComparer` for sorting in `EntityState` (is how they operate on arrays) or you can also sort elements before getting in component by creating custom selector. In that case logic for sorting is separated from the view. In my case when I do `[...todosState.get()]` it's no longer array of states but simple array. If I'd like to sort an array of state, it would go into multiple rerenders due to swapping. Below is part of my code that I'm talking about:
```javascript
function compareByUpdated(todoA, todoB) {
    return todoB.updated - todoA.updated;
}

return (
        <ul>
            {[...todosState.get()]
                .sort(compareByUpdated)
                .map((todo) => (
                    <li key={todo.id}>
                        <input
                            type='checkbox'
                            checked={todo.completed}
                            onChange={toggleTodoToStore(
                                todo.id,
                                !todo.completed
                            )}
                        />{' '}
                        {todo.name}{' '}
                        <button onClick={removeTodoFromStore(todo.id)}>
                            Usuń
                        </button>
                    </li>
                ))}
        </ul>
    );
```

My questions may seem complicated but I just want to see a proper way to sort elements in nested state in `Hookstate`.

**Comment by avkonst** [comment]
The way you do it is one way. There are other options. But what exactly do not you like about the current variant?

**Comment by wrb94** [comment]
I've been comparing some state management library last few weeks (`redux`, `redux-toolkit`, `recoil`, `hookstate`) and other libs allow to separate sorting logic from view. For `redux` it's in reducer and for `redux-toolkit` and `recoil` it's in selector. In my opinion for `hookstate` the best way to do it is via exposing state indirectly but since I couldn't achieve that I wanted to hear library author comment for that.

Thanks for answering and feel free to close the issue.

**Comment by avkonst** [comment]
Ok. Now I understand what you want. You can achieve the similar to `recoil selector` or `redux actions` feature with help of state usage _wrapping_ by a custom hook. Example can be found here: https://hookstate.js.org/docs/exporting-state

**Comment by avkonst** [comment]
Instead of using the state like this:
```
let todosState = useState(....)
```
use it like this:
```
let todosState = useSortedTodosState()
```
where:
```
function useSortedTodosState() {
    let todosState = useState(...);
    return {
        // example of getting sorted state
        get: () => [...todosState.get()].sort(...),
        // example of custom action
        markDone: (id) => todosState.find(todoItem => todoItem.id === id).isDone.set(true)
    }
}
```

**Comment by avkonst** [comment]
Does it give you what you would like to achieve?

**Comment by wrb94** [comment]
It solves my problem. Thanks for your help. Keep up the good work. Closing the issue.
