### ISSUE TITLE
More detailed documentation for `Persistence`

### ISSUE THREAD

**Issue by mxdi9i7** [avkonst/hookstate#176]
Right now the persistence extension docs is limited to local state, it would be helpful for hookstate beginners like me to see a global state usage of the Persistence extension.

When using persistence for a global state, do you attach the Persistence state key in global state declaration/initial set/or every instance of usage?

**Comment by avkonst** [comment]
> "When using persistence for a global state, do you attach the Persistence state key in global state declaration/initial set/or every instance of usage?"

Attach to the instance of global state once.

**Comment by mxdi9i7** [comment]
But I've found that to not work, as in it either doesn't read the correct value from persist or gives a JSON token error due to undefined value being stored and read, as a workaround I'm attaching the persistence in local scope every instance

**Comment by avkonst** [comment]
Sorry, I need a reproducer in a git repo or codesandbox to advise further. It is hard to know what you are doing and what does not work. Thanks
