### ISSUE TITLE
Allow plugins to intercept state set?

### ISSUE THREAD

**Issue by dphuang2** [avkonst/hookstate#179]
Should plugins be allowed to intercept `set` / `merge` / `batch` updates to state?

It would be useful when you only want to allow certain values for a state. One example could be a phone number input where only `[0-9\-\ ]` characters should be accepted.

**Comment by avkonst** [comment]
Thanks for the suggestion. I was considered in the past.

There are 2 problems to implement it via a plugin call back.

1. Let's say you have got an array of integers as a state and you would like to ensure that each number is positive. If there was a plugin call back, like onPreset, it would need to check the new state value when it is set like this:
```
let state = useState([0, 1, 3])
state[0].set(-1)
```
and when it is set like this:
```
state.set(p => { p[0] = -1; return p })
```
The last does not scale well. And if you do not check the bad value can escape into the state.

2. It was not clear how to validate the initial state:
```
let state = useState([-1, 1, 3])
```
One option I though about it to reject plugin attachment which validates the entire state when it is attached. But it does not prevent the state from actually having bad state for a moment.

Finally, I have discovered that any type of state validation (for my apps at least) can be achieved by exporting custom state set actions. In the example on this page: https://hookstate.js.org/docs/exporting-state, if the `increment` function had an argument (for example how much to increment by), the validation could have place in the implementation of the `increment` function (for example, you could check the argument is only positive addition). This way all your actions to mutate the state could take care of ensuring the correct state. I understand it is not as flexible as using `set` and `merge` functions on the nested states, but it was good enough for me. If it is not enough for, I am happy to consider this request further. We would need to have answers for the 2 above mentioned problems.

**Comment by dphuang2** [comment]
(1) setting single element in array like this seems like an anti-pattern anyways
(2) I don't see this as a problem. Plugin promises to intercept state mutations and nothing more.

Wrapping state as a validation pattern seems like a "hard-coded" solution as opposed to a framework driven approach:

This is much more succinct/easier to read:
```typescript
state.attach(MyPlugin)
const rule = (val: number) => val >= 0 ? val : val; // updates state only if >= 0
MyPlugin(state.subState).accept(rule)
MyPlugin(state).accept(rule)
state.set(-2) // does nothing
state.subState.set(-2) // does nothing
```

Than this:
```javascript
const wrapState = (s: State<StateValueAtPath>) = ({
    update: (val: number) => {if (val >= 0) s.set(val)}, // hard-coded action
    updateSubState: (val: number) => {if (val >= 0) s.subState.set(val)}
)}
const wrapped = wrapState(state);
wrapped.update(-2) // does nothing
wrapped.updateSubState(-2) // does nothing
```

Notice how in the latter example we have to code "hard-code" actions as opposed to applying a rule describing "how" this state works.

Just my opinions. I haven't done enough diving into the source code to understand how hard this would be to implement but I just wanted to throw the idea out there. Of course the plugin will have to deal with edge cases such as entire array mutations but the general gist is there.

**Comment by avkonst** [comment]
> (1) setting single element in array like this seems like an anti-pattern anyways
why?
Please note that setting nested properties is better for Hookstate performance and rerendering optimization.

What you suggest for the plugin syntax is doable. Hookstate needs to expose onPreset callback similarly to onSet callback for the Plugin api.

> state.set(-2) // does nothing
It can not do nothing, it should either set of throw an exception. Basically, if a plugin throws onPreset the Hookstate does not reach to state mutation logic and onSet callback does not happen.

**Comment by dphuang2** [comment]
I was referring to this example as an anti-pattern:
`state.set(p => { p[0] = -1; return p })` because former example is more performant like you said.

> It can not do nothing, it should either set of throw an exception. Basically, if a plugin throws onPreset the Hookstate does not reach to state mutation logic and onSet callback does not happen.

makes sense.

**Comment by avkonst** [comment]
Ok. Would you be able to submit pull request with the addition of onPreset callback to the @hookstate/core? I estimate it should be relatively easy task - just search for where onSet is used and add the same for onPreset. The difference is: the onPreset would get the current state instead of onSet getting the new state in callback arguments, but I did not check the details. It is coming from the top of head...

**Comment by dphuang2** [comment]
I have a workaround that is a layer above hookstate for now but will refer to this ticket if push comes to shove and this feature is needed :) Thanks for the pointers on where to make the changes!

**Comment by avkonst** [comment]
Hookstate-4 has onPreset and andPremerge callbacks for Extensions (new plugins engine for Hoosktate 4). It will be released and the documentation will get updated soon.
