### ISSUE TITLE
Cannot change property value

### ISSUE THREAD

**Issue by danielkv** [avkonst/hookstate#180]
I have a state object, and initially, some of the properties are undefined. I can set the property for first time, but when I if I need to change, using "set" again, I get the error: HOOKSTATE-202.

I'm on this big project, need help!

**Comment by avkonst** [comment]
Unfortunately I am not able to help without more information provided.

Could you please reduce the problem and submit a reproducer?

**Comment by danielkv** [comment]
Sure!
I have a state like this:
```ts
export class ServiceInput {
    appointmentId?: string;
    name: string;
    serviceId: string;
    price: ServicePriceType;

    date_info: DateInfoType;
    company?: CompanyModel;
    professional?: ProfessionalModel | NoPreference;
}

export type ServiceQueueType = {
    index?: number;
    queue: ServiceInput[];
};

export const serviceQueueState = createState<ServiceQueueType>({ queue: [] });
```

As you can see some of the properties are initally `undefined`. I can **set** these properties when they are `undefined`:

```ts
serviceQueueState.queue[index].professional.set(SOME_PROFESSIONAL);
```

But when I try to **change** the **professional** of this same `index` it throws the error HOOKSTATE-202.
In this case it cannot be, because I'm using the `set` suggested in the Exception page.

**Comment by avkonst** [comment]
What you are doing seems correct. I have tried to put a unit test with similar state structure and could not reproduce the problem. Would you be able to submit a git repo or codesandbox repo which I could clone/visit and debug the reproducible problem?

**Comment by danielkv** [comment]
The project is in development yet cannot share the entire code. I'll try to reproduce a smaller repository tomorrow. Thanks for the fast response. I'll be back with the repository!

**Comment by avkonst** [comment]
yes, I do not need the big project. The smaller the better.

**Comment by danielkv** [comment]
I think I figure it out. I have a **queue** of services, at some point I was including some services in the queue, but later I need to include those services again in the queue. But since javascript, by default, use object references for objects, it was instanciating the same service objects.

To fix it I cloned the objects when I add to the queue:
```ts
 addToQueue(services: ServiceInput | ServiceInput[]): void {
    const servicesToAdd = Array.isArray(services) ? services : [services];

    const queueState = {
        queue: JSON.parse(JSON.stringify(servicesToAdd)), // CLONE OBJECTS PARSING THE JSON AGAIN
    };

    serviceQueueState.set(queueState);
}
```
