### ISSUE TITLE
how to use and extract values from a state into another state without changing the original data of the state

### ISSUE THREAD

**Issue by codeidiotpro** [avkonst/hookstate#181]
I want to extract values from a state and set it in another state. However, I want the state's values to remain intact.
Take a look at the code below

```js
function component() {
  const state1 = useState(state);
  const state2 = useState(state1);
  
  // the reason to put state1 in state2 is to preserve the value of state1
  // and extract only the values needed
  
  // example: something like
  state2.set(state1.filter(e => e.bool === true)) // extract values from state1 and store it in state2 so to preserve
                                                  // the original values of state1. If new values are needed from state1
                                                  // then extract it again, override values in state2 and add the new values
                                                  // from state1
  
  return <div></div>
}
```

this is my project https://codesandbox.io/s/todolist-with-hookstate-n5m37?file=/src/components/TodoList.js

**Comment by avkonst** [comment]
1. You need to obtain the value behind the state (`.get()` or `.value`), which is opted out from tracking (`.attach(Downgraded)`):

```
state2.set(state1.filter(e => e.bool === true).attach(Downgraded).get()) 
``` 

2. You also should not set the state during rendering. `state2.set(...)` should happen in a callback, action callback, useEffect or something. Otherwise you get recursive rerendering.

**Comment by codeidiotpro** [comment]
im getting a TypeError: stateTodoData.filter(...).attach is not a function

**Comment by avkonst** [comment]
Right, filter returns a clone array. So, attach earlier:
```
state2.set(state1.attach(Downgraded).get().filter(e => e.bool === true)) 
```

**Comment by codeidiotpro** [comment]
two problems.
1 it works but it modifies the values in state1 when it should not. only the values in state2 should be changed and overwritten.
2 my useEffect re-renders the component forever.

im sorry im new to coding as you can probably tell so there is a lot of terminologies I dont understand. ive tried fixing the issue myself but with little success

**Comment by avkonst** [comment]
1. ok. you need to get true deep clone copy of the state1 array. One way to do this: `JSON.parse(JSON.stringify(state1.attach(Downgraded).value))`. Then you can do filter, etc. There are better ways for true deep clone copy, using lodash library for example.

2. switch to typescript it will help you to get rid of many problems
3. I have answered regarding rerender in your other ticket.

**Comment by codeidiotpro** [comment]
Thanks for your help bro. I will try to fix the issues base on the information you gave me. I'll keep you updated

**Comment by codeidiotpro** [comment]
I was able to solve all the issues! Thanks for you help and this amazing library that you created
here is my completed project, check it out: https://n5m37.csb.app/

**Comment by avkonst** [comment]
Congratulations! I think this app can be done without state1 copy to state2. Just use the current state of filter to show only what is required. I do not get why you needed a copy.

**Comment by avkonst** [comment]
If you like the library, please share your feelings in the dev community. it will help the project to grow. Thanks

**Comment by avkonst** [comment]
Answered
