### ISSUE TITLE
Untracked for plugin onSet callback?

### ISSUE THREAD

**Issue by iamjoshua** [avkonst/hookstate#183]
Untracked allows for state modification without triggering renders, but it doesn't seem to stop the plugin callbacks from firing.  I'm writing several plugins that modify meta fields (such as 'updatedAt')  for entries in the global store, but doing so causes the onSet callback for each of the attached plugins to be called. 

Is there a way to avoid this and allow certain updates to the state without triggering any attached plugin callbacks?

**Comment by avkonst** [comment]
Hi, sorry for late reply. Yes, there is a way to update properties without exposing it to other plugins. You need to use symbol properties. You can add a symbol property to your data instance behind the state object like this:

```
let mySymbol = Symbol('my_symbol');
let state = useState(....)
state.value[mySymbol] = 'my data';
```

**Comment by avkonst** [comment]
Please let me know it it help and can be closed.

**Comment by iamjoshua** [comment]
That's not exactly what I had in mind. I wanted to update the actual fields in the store, not special fields with symbols as keys.I I was, however, able to rework my strategy using this approach, but I'm still curious if there is a way to modify the actual store content without triggering other plugins.

**Comment by avkonst** [comment]
Are the mentioned plugins written by you and under your control? Yes, plugins observe data modification, but if you control it, you can skip processing unwanted updates (eg. by inspecting update `path` property). There is also `batch` action, which has context argument. This argument can be used to capture more client's context information about an update, including those which can be used by plugins to skip processing.
