### ISSUE TITLE
[question] Are there any Hookstate alternative to AtomFamily concept in Recoil?

### ISSUE THREAD

**Issue by KestutisMa** [avkonst/hookstate#184]
Hi, are there any Hookstate alternative to AtomFamily concept in Recoil.js? I think it is called _dynamically created state_.
e.g., I have many curves that belong to groups, and I want to plot groups in separate plots, and if I update single curve, I want corresponding group's plot to be updated, but not all plots. I have component Plots, that contain several Plot components.

**Comment by KestutisMa** [comment]
I found this https://hookstate.js.org/docs/dynamic-states-store/ but it is empty

**Comment by avkonst** [comment]
Hi, Hookstate does not need this concept as it optimizes rerendering automatically. You achieve what you need without doing something special, if each of your plot component calls useState individually. You can do it with a global state (see: https://hookstate.js.org/docs/global-state) or for a state coming from your parent Plots component (see https://hookstate.js.org/docs/scoped-state)

**Comment by KestutisMa** [comment]
Thanks, interesting concept, from your posts in github I formed impression that you think Hookstate *currently* is better (faster/more intuitive/less code) than Recoil? Or are there any notes on use cases where Hookstate is not preferred at the moment?

**Comment by avkonst** [comment]
Hookstate has got the limitation currently related to useeffect and memo
dependency lists. Find an open ticket. This is rarely needed and i have got
a solution for this, but do not have time to finish it. Also there is
ongoing work in react to give api for state management libs to handle
concurrent rerendering. I did not look into this, but recoil probably did.
I am not sure where it is not preferred, i just use it and improve when
needed.

**Comment by KestutisMa** [comment]
Thanks for info, i think that writing about limitations in documentation would make framework feel more mature impression. Yes, i have read about useEffect in Hookstate, i will try proposed workaround.
Recoil.js states that it `have the possibility of compatibility with Concurrent Mode and other new React features as they become available.`, anyway it is still in beta. Could React Concurrent mode help avoid UI blocking when some components takes long time to render (e. g. plot with many points)?

**Comment by avkonst** [comment]
I am not too sure. I did not look into this yet, but i doubt it will help
to mitigate busy js scripts as these all are executed in a single thread
anyway.
