### ISSUE TITLE
Documentation/website could use a bit more info

### ISSUE THREAD

**Issue by c0dezer019** [avkonst/hookstate#189]
Your documentation states that this is an alternative to Formik among the others. Formik is a React library for building React Forms, and has nothing to do with state beyond form state and is not intended for global state management. Your website mentions nothing about implementing a tool for developing forms. This is like comparing tomatoes to aliens imo. How will this be an alternative to Formik?

**Comment by avkonst** [comment]
You are probably right. Documentation can be improved.
Initially the project was started as a tool for editable forms (and Formik was an initial choice in my project before it was displaced by custom React and Hookstate - although it was not named Hookstate then). It was in the ages before it grown to the state management.
If it is not an alternative to Formik, you still can use Hookstate for building forms easily.

**Comment by avkonst** [comment]
removed reference to formik
