### ISSUE TITLE
Why use useState for global states?

### ISSUE THREAD

**Issue by andrashatvani** [avkonst/hookstate#190]
The docs state:

> The result value is an instance of State, which can be used directly to get and set the state value outside of a React component.

If the global state resulting from _createState_ **can** be used for writing and reading state, then why would/should one use _useState_ in addition in every function component?

**Comment by LoganArnett** [comment]
I believe that `createState` returns a more complex `State` object that you can use to handle more dynamic use cases for globalState while `useState` still provides a `State` object but overall it creates less overhead in your code and does not have all of the options that `createState` offers. This makes it lighter weight for your local state within functional components. If you do not need the additional features that `useState` from `Hookstate` then you can still default back to `React.useState`

**Comment by avkonst** [comment]
> why would/should one use useState in addition in every function component?

because something should tell react that components should be rerendered when a global state is updated

> I believe that createState returns a more complex State object that you can use to handle more dynamic use cases for globalState while useState still provides a State object but overall it creates less overhead in your code and does not have all of the options that createState offers. This makes it lighter weight for your local state within functional components.

No, the returned object has got the same API and scope of functionality. There are 2 differences not visible to a client code: 1) useState State triggers component rerender on used state update and 2) useState automatically calls dispose on a state, if it was used for a locally created state.

**Comment by avkonst** [comment]
> If you do not need the additional features that useState from Hookstate then you can still default back to React.useState

Correct

**Comment by avkonst** [comment]
If it answers your questions, please close the ticket
