### ISSUE TITLE
Add explicit API to toggle development/production mode (WAS: process is not defined)

### ISSUE THREAD

**Issue by ALMaclaine** [avkonst/hookstate#193]
ReferenceError: process is not defined
```
> 182 | var isDevelopmentMode = process !== undefined && process !== null && typeof process === 'object' &&
  183 |     process.env !== undefined && process.env !== null && typeof process.env === 'object' &&
  184 |     process.env.NODE_ENV === 'development';
  185 | var self = Symbol('self');
```
I looked in the index.es.js file and process is never defined, when I set it to true or false everything works fine.

**Comment by avkonst** [comment]
Could you please have a look through the closed tickets? There was one or
two similar. The issue is in the settings for webpack for your project. If
still can not find, let me know

**Comment by ALMaclaine** [comment]
@avkonst 

I see some solutions but I also see this comment made by you:

https://github.com/avkonst/hookstate/issues/118#issuecomment-748330000

I have an idea.

you can do:

```
var isDevelopmentMode = false;
if(typeof global !== "undefined") {
  if(type global.require !== "undefined") {
    isDevelopmentMode = require('_processvar.js');
  }
}
```

where _processvar.js is the line above:
```
module.exports = process !== undefined && process !== null && typeof process === 'object' &&
process.env !== undefined && process.env !== null && typeof process.env === 'object' &&
process.env.NODE_ENV === 'development'
```

**Comment by avkonst** [comment]
Thanks for the idea. How would it fix it? I suppose require('_processvar.js') would throw the same issue.

Also, I am a not quite sure how `require` would be handled by app bundlers and all possible runtimes? If it is compiled in, it would make the _processvar.js embedded into the main code. If it is not compiled in, it would do a network call?

**Comment by avkonst** [comment]
I am transforming this to the feature request. The new major version of Hookstate would better to include an explicit API to toggle development/production mode.

**Comment by ALMaclaine** [comment]
> Thanks for the idea. How would it fix it? I suppose require('_processvar.js') would throw the same issue.
> 
> Also, I am a not quite sure how `require` would be handled by app bundlers and all possible runtimes? If it is compiled in, it would make the _processvar.js embedded into the main code. If it is not compiled in, it would do a network call?

my bad, it would need to be global.require since we had demonstrated it was on global. I don't know the implications for bundlers. But I see you're going to look into some other kind of solution. Thank you.

**Comment by avkonst** [comment]
https://github.com/avkonst/hookstate/pull/207

**Comment by avkonst** [comment]
please keep it open, as it is a feature I still want to add

**Comment by ALMaclaine** [comment]
Sorry, I misunderstood the relevance of the last comment.
