### ISSUE TITLE
Does Hookstate/Persistance work on React Native ?

### ISSUE THREAD

**Issue by emmanuel-D** [avkonst/hookstate#194]
I am about to start a new **React Native** project and I would like to know if the package `@hookstate/persistance` also works on React Native since there is no `localStorage` on Native devices.

If not, is there a possibility to make it work using for example the `AsyncStorage` on React Native ?

I am currently using this Package for my **ReactJS** Webapp and I find it very easy and great to use, so I would also use in for **React Native**.

**Comment by avkonst** [comment]
> I am about to start a new React Native project and I would like to know if the package @hookstate/persistance also works on React Native since there is no localStorage on Native devices.

No, it would not work as there is no localStorage as you said.

> is there a possibility to make it work using for example the AsyncStorage on React Native ?

Yes, quite easily. It is possible to add a plugin by copying from the existing persistence plugin. Here is the guide: https://hookstate.js.org/docs/writing-plugin

> I am currently using this Package for my ReactJS Webapp and I find it very easy and great to use, so I would also use in for React Native.

Yes, the core package works with React Native just as well as with the web.

**Comment by avkonst** [comment]
If you end up publishing the persistence plugin for react native, please let me know, I will include it to the registry of plugins available.

**Comment by emmanuel-D** [comment]
All rights.
I will try it then 👍

**Comment by jwisbeck** [comment]
any plugins? I have found https://github.com/peter-olom/hookstate-persist but I am interested in the OP or if another plugin exists!
