### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by tianyu94** [avkonst/hookstate#195]
with vite.js

![Screenshot_20210612_113255](https://user-images.githubusercontent.com/37231629/121763902-15f4b100-cb72-11eb-84e1-f2f75316069f.png)

![Screenshot_20210612_113317](https://user-images.githubusercontent.com/37231629/121763904-18efa180-cb72-11eb-9b31-5019598de98a.png)

**Comment by avkonst** [comment]
I have not idea what vite.js is but I have found the issue on their side: https://github.com/vitejs/vite/issues/1973

**Comment by avkonst** [comment]
It is a configuration issue for your app bundler.

**Comment by avkonst** [comment]
Also see this solution for Vite: https://github.com/avkonst/hookstate/issues/118#issuecomment-759330757

**Comment by avkonst** [comment]
See https://github.com/avkonst/hookstate/issues/193

**Comment by avkonst** [comment]
https://github.com/avkonst/hookstate/pull/207

**Comment by zgandrew** [comment]
It looks like there need to add file env.d.ts with such entire:
`/// <reference types="vite/client" />`

Then use import.meta.env.VITE_APP_[VAR_NAME] instead of process.env.VITE_APP_[VAR_NAME]
