### ISSUE TITLE
How to set a global Asynchronous state, which can be accessed in multiple sub components?

### ISSUE THREAD

**Issue by jishnukoottala** [avkonst/hookstate#196]
### Q. How to set a global Asynchronous state?

[Here is the link to the codesandbox](https://codesandbox.io/s/condescending-grothendieck-x6jqh?file=/src/PostsAndComments/index.tsx)

 refer to the sandbox,  In `store/store.ts` I am trying to set a global asynchronous state, which i am then trying to access in `PostsAndComments/index.tsx`

By referring to the documentation mentioned [here](https://hookstate.js.org/docs/asynchronous-state), setting an  asynchronous state locally is fine, and working as expected, but what if I want to set this state globally and use it in different component? Help is very much appreciated.

Note: I am getting the following error, when trying to access the data property
`TypeError: _this.child(...).get is not a function`

Thanks in advance.

**Comment by avkonst** [comment]
HI, sorry I could not reproduce the error you are referring to. The sample in the sandbox works for me.

The example of how to use global state with async would be:

```tsx
import React, { useEffect } from "react";
import { createState, useState } from "@hookstate/core";
import { postAndCommentsState } from "../App";
import { usePostsAndComments } from "../store/store";

export type PostType = {
  id: string;
  userId: string;
  title: string;
  body: string;
};

const resourcePath = "https://jsonplaceholder.typicode.com/posts/";

export const fetchPosts = () => fetch(resourcePath).then((r) => r.json());
const postsStateGlobal = createState(fetchPosts);

export const PostsAndComments: React.FC = () => {
  const postsState = useState(postsStateGlobal);

  // const result = usePostsAndComments();
  // console.log(result);
  // if (result.error) {
  //   return <div> error</div>;
  // }
  // if (result.loading) {
  //   return <div> loading</div>;
  // }
  // return (
  //   <div>
  //     <h5> Posts...</h5>{" "}
  //   </div>
  // );

  // the following code works fine, but what if i need to set a global async state
  if (postsState.promised) {
    return <div> Laoding.......</div>;
  }
  if (postsState.error) {
    return <div> Error</div>;
  }

  return (
    <div>
      <button onClick={() => postsStateGlobal.set(fetchPosts)}>
        Set global state
      </button>{" "}
      {postsState.value.map((item: PostType) => (
        <div> {item.title}</div>
      ))}
    </div>
  );
};

```

**Comment by avkonst** [comment]
A workaround in you application would be to export a getter function instead:

```
const postsStateGlobal = createState(fetchPosts);
export function getPostsState() {
    return postsStateGlobal;

}
```
