### ISSUE TITLE
Combining parts of global states?

### ISSUE THREAD

**Issue by zetaurum** [avkonst/hookstate#199]
Hello and thank you for such a great lib.

What is safest way to combine only parts of multiple global states in one hook?
Is following correct?

```js
const global01 = createState({
  par1: false,
  par2: true,
  data: [1, 2, 3]
});

const global02 = createState({
  par2: false,
  par4: true,
  data: [1, 2, 3],
  dataOther: {
    arr: []
  }
});

export default function useSomeHook() {
  const s1 = useState(global01);
  const s2 = useState(global02);

  const sss = useState({
    isReady: s1.par1,
    data: s2.data
  });

  return {
    state: sss
  };
}

```

**Comment by avkonst** [comment]
Hi. No, this would not be right. You are better to expose custom setter and getter for isReady and data fields of your combined state. See here for an example of wrapping 1 state. You can wrap 2 states in a similar way: https://hookstate.js.org/docs/exporting-state

**Comment by avkonst** [comment]
No, do it this way (for example: demo of two styles of exporting the state 1) as custom setter and getter and 2) as original Hookstate state):

```tsx
export default function useSomeHook() {
  const s1 = useState(global01);
  const s2 = useState(global02);

  return {
    get isReady() { return s1.par1.get() },
    markReady() { s1.par1.set(true); }
    get data() { return s2.data; } // pass all data as State method with all Hookstate state features.
  };
}
```

**Comment by heynext** [comment]
expose custom setter and getter is a little complex if there are lots of fields. is here any way to make it work as follows:
```
const state = createState({
  a: 1,
  ...
});

export default function useCustomState() {
  ...

  return {
    state: useState(state),
  };
}
```

**Comment by avkonst** [comment]
@heynext wrapping useState in another hook is a way to go. You code snippet seems ok. What is not working there?

**Comment by avkonst** [comment]
For the thread followers. Combining multiple global states in one hook is possible via this way (continuing the example from the above)

```
export default function useSomeHook() {
  const s1 = useState(global01);
  const s2 = useState(global02);

  const sss = {
    isReady: s1.par1,
    data: s2.data
  };

  return sss;
}
```

**Comment by avkonst** [comment]
Please reopen if still unclear
