### ISSUE TITLE
Infinite useEffect while setting global state after a data fetch

### ISSUE THREAD

**Issue by aahmad4** [avkonst/hookstate#200]
First of all, thank you for making such a great library.

I was attempting to set a global state variable after a data fetch in a useEffect. I then put that global state variable in my dependency array to avoid a re-render, but it's still continuously re-rendering. I'm assuming that there are some differences in the proxy or such each time which is causing this behavior? How would you suggest I work around this so that the useEffect only re-runs when the actual data within that state variable changes. Thanks!

 ```store.js```
```js
import { createState } from '@hookstate/core';

const userDetailsFromStorage = localStorage.getItem('userDetails')
  ? JSON.parse(localStorage.getItem('userDetails'))
  : null;

const store = createState({
  userDetails: userDetailsFromStorage,
  questions: [],
});

export default store;
```

```DashboardScreen.jsx```
```jsx
import { useState as useHookState } from '@hookstate/core';
import store from '../store';

export default function DashboardScreen({ history }) {
  const { userDetails, questions } = useHookState(store);

  useEffect(() => {
    if (userDetails.get()) {
      const fetchQuestions = async () => {
        const { data } = await axios.get(
          `/api/questions/${userDetails.get().id}`
        );

        questions.set(data.questions);
      };

      fetchQuestions();
    } else {
      history.push('/');
    }
  }, [history, userDetails, questions]);
  
  return <p>ui stuff</p>;
}
  ```

**Comment by avkonst** [comment]
userDetails and questions would be new Proxy objects of your state values on each rerender. Your intention to run the effect callback once, so remove userDetails and questions from the dependency list: ` [history, userDetails, questions]`

The ESLint warnings which you might get, can be ignored.

**Comment by avkonst** [comment]
See also: https://github.com/avkonst/hookstate/issues/140

**Comment by aahmad4** [comment]
Thank you! Works fine now :)
