### ISSUE TITLE
If nested state of a global state is mounted to useState, this is not traced accordingly and state update causes undesirable rerendering

### ISSUE THREAD

**Issue by lonkaars** [avkonst/hookstate#201]
When I use `createState` to create a new state with an object, all components using other properties than the one updated rerender:

minimal example (using next.js):
```tsx
import { createState, useHookstate } from '@hookstate/core';

var globalState = createState({
	a: 0,
	b: 0
});

setInterval(() => {
	globalState.a.set(globalState.a.value + 1);
}, 1000);

function TestA() {
	console.log("render a");
	var test = useHookstate(globalState.a);
	return <span>{test.get()}</span>;
}

function TestB() {
	console.log("render b");
	var test = useHookstate(globalState.b);
	return <span>{test.get()}</span>;
}

export default function Test() {
	console.log("render test")
	return <>
		<TestA/>
		<TestB/>
	</>;
}
```
output:
![image](https://user-images.githubusercontent.com/32883851/122955461-6b09a180-d380-11eb-8fce-044d268de285.png)

in this example, component `TestB` gets re-rendered along with `TestA` even though property `b` of the global state is never changed. I can fix this behavior by changing the global state to this:

```tsx
var globalState = {
	a: createState(0),
	b: createState(0)
};
```

But now it's much harder to get the complete state as a 'clean' JSON object.

I'm not sure if this is intended behavior, or if this is a bug.

**Comment by avkonst** [comment]
Replace `useHookstate(globalState.a)` by `useHookstate(globalState).a`.
PS: I will keep this ticket in the backlog and investigate if the code can be improved to handle this scenario too.

**Comment by lonkaars** [comment]
I was setting a property in my state object inside a requestAnimationFrame loop so that made the ui very slow, but it's fixed now! Thanks!
