### ISSUE TITLE
Hookstate useState is called outside of render function (WAS: Hookstate breaks with SWR)

### ISSUE THREAD

**Issue by dioptre** [avkonst/hookstate#206]
SWR is a query caching utility for nextjs (made by the same people) @ https://swr.vercel.app/

If I useState(hookstateobject) during the call to the fetcher it initially returns the right result, but subsequent calls return nothing and don't run.

```
import {useAuthTokenState} from '../components/Login/AuthTokenState';

const fetcher = url => {
authTokenState = useAuthTokenState() //<----Works first time, fails here second time if you click away and back again during cache refresh
fetch(url, {headers: "Authorization: Bearer" + authTokenState.get()).then(r => r.json())
}

function App () {
  const { data, error } = useSWR('/api/data', fetcher)
  // ...
}
```

I get the following error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

If I replace useAuthTokenState with the underlying object "state", (ex. ```import {state} from '../components/Login/AuthTokenState';```) it works, but I'm not sure this pattern is ok for:
```
export const state = createState<User>(initialState);

export function useAuthTokenState() {
    return useState(state)
}
```

**Comment by avkonst** [comment]
According to react rules of hooks, hook functions should be called within component functions but not on events, callbacks, etc..
This is not a hookstate error, you will get the same result with React.useState.

You need to save token like an object, like your later example, and subscribe on changes to the token and propagate change to the state using State.set method.

Also, token is likely needed on network events, and API calls. So, I doubt you need to mount it with useState hook as you can just get the value of token when you do API call, and change of a token presumably does not influence what is rendered. But there is no detail about your app, so can not comment further.

**Comment by avkonst** [comment]
Feel free to ask follow up questions or reopen the ticket if you feel like my answer is not right.

**Comment by dioptre** [comment]
Thanks! So is it ok to just use the "state" object directly as I ended up doing it?

**Comment by avkonst** [comment]
Yes. Check out code samples in the docs for global state usecase...
