### ISSUE TITLE
Initial checkpoint. 

### ISSUE THREAD

**Issue by from-nibly** [avkonst/hookstate#208]
I'm building out a form plugin for hookstate. Most of the components are available through initial, and validation plugins. 

One thing I would like to have is the ability to "cancel" editing a form. Doing this would be awesome with the the initial plugin. Except if you edit, modify, save, edit, cancel; it will revert to the original initial state not the state since it last saved. (Hopefully that made sense)

Any problems with adding a checkpoint() (or otherwise named) method which would set the "initial" state to the current state? 

And maybe even a revert() that would set the current state to the initial state?

Both of these would be additions to the initial plugin. 

Or is there a way to achieve this already?

**Comment by avkonst** [comment]
There is no such a capability in existing plugin. I can see it being useful and faced similar needs in the past.

You can add `set()` method to the `Initial` plugin, which would do what `checkpoint()` you suggested. Waiting for PR.

Not sure about `revert()`. Feel free to propose and I will have a look.

**Comment by from-nibly** [comment]
KK will do shortly

**Comment by avkonst** [comment]
Will be addressed in scope of https://github.com/avkonst/hookstate/issues/208
