### ISSUE TITLE
Broadcast Plugin: Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by thachp** [avkonst/hookstate#210]
The occurrence of this bug is sporadic...

Repros:
In Page1 .... attach a broadcast name: sample.
In Page2 .... attach the same broadcast name: sample.
In Page1.. include an iframe to src=/page2.

Access Page1 through a web browser (Chrome).  The error below would sometimes occur, but if you refresh it goes away.

Sample codes here:
https://codesandbox.io/s/naughty-napier-19wo2

![image](https://user-images.githubusercontent.com/1495371/124544430-f270ff00-dddb-11eb-8e7f-6f85d92c55af.png)

My temp solution is to wrap the attach method around a try-catch statement.

    try {
        state.attach(Broadcasted("omn:pagebuilder"));
    } catch (e) {
        //
    }

**Comment by avkonst** [comment]
Thanks for reproducer:

Quick look:

issue at line 222 of compiled code: 
![image](https://user-images.githubusercontent.com/3971413/124831462-57d91180-dfcf-11eb-9189-1b10445fddda.png)

which suggest this.broadcastRef is undefined. It has got 4 references: 1 in constructor and 3 usages in instance methods. 1 in constructor is definitely initialized to non null value. This is a puzzle requiring a bit more time to debug.

**Comment by avkonst** [comment]
It does not happen on attach for me... it is in the different place in your reproducer. Do you have an idea why?

**Comment by avkonst** [comment]
Ok. It seems like onLeader callback is invoked immediately once subscribes before this function returns a channel property to the broadcasted plugin:

![image](https://user-images.githubusercontent.com/3971413/124832578-f7e36a80-dfd0-11eb-9e5f-080d8c15c039.png)

**Comment by avkonst** [comment]
ok. The fix is to flatten nested properties behind `this.broadcastRef` into properties of the plugin instance. This way `this.broadcastRef.channel` would become `this.channel` and it would be defined prior to `SystemLeaderSubscription.subscribe(onLeader)` call. Would you be able to put a PR for this?

**Comment by thachp** [comment]
Yes, I can submit a pr. But, it'll probably take me a few days where else someone much smarter than me would take 15 mins.  

Thanks for the quick response.

**Comment by thachp** [comment]
@avkonst  This bug is tricky to troubleshot ... I've gotten nowhere.  On codesandbox, I copied  plugins/Broadcasted.ts to  /utils/broadcasted.ts   The error somehow went away after changing the import.  

` import { Broadcasted } from "../utils/broadcasted"; `

 I'm open to someone else to take over the bug.

https://codesandbox.io/s/naughty-napier-19wo2?file=/utils/broadcasted.ts:8915-8927

**Comment by thachp** [comment]
Update on this bug, I ended up adding? null check to  line 264 and  301-ish

 // optional chaining, stop if broadcastRef is null
this.broadcastRef?.channel.postMessage(message);

// on destroy method I added a check
    onDestroy() {
        this.isDestroyed = true;
        if (this.broadcastRef) {
            unsubscribeBroadcastChannel(this.broadcastRef);
        }
    }

**Comment by avkonst** [comment]
this check will prevent from distributing the initial state. Do not worry, I will fix this bug myself. I have preliminary described above how it needs to be fixed. I am just extremely busy now with another thing.

**Comment by avkonst** [comment]
broadcasted plugin has been reworked for hoostate-4 where this bug was fixed. The release and documentation updates will be done shortly.
