### ISSUE TITLE
calling setState( none ) on a ScopedState (element in array) will turn scopedState into promised == true indefinitely

### ISSUE THREAD

**Issue by SuperStupar** [avkonst/hookstate#212]
`employeeState.employees.map((item, index) => (
          <TableRow
            data={item}
          ></TableRow>`
in TableRow component: 
`const dataRowState = useState(dataRow);`
calling `dataRowState.setState(none)`
sets dataRowState.promised to true indefinitely. 
employeeState is a global Broadcasted state

**Comment by avkonst** [comment]
I have attempted to write a reproducer and it seems the use case you described works fine. Please reopen providing more information.
