### ISSUE TITLE
Lodash isEmpty now working as expected with hookstate state

### ISSUE THREAD

**Issue by akshayraina-github** [avkonst/hookstate#213]
First of all thanks for providing such an awesome state management library.
I am facing one problem
I try to use lodash isEmpty to check if my global state object is empty( {} ).
But it was not able to detect that.
e.g
globalUser's default value is {}

if(isEmpty(globalUser.get()))
This condition is getting true even if the globalUser is an empty object.
Any way if this is not working. What is the best way to check for empty global state. (Object.entries ?)
Thank you

**Comment by avkonst** [comment]
What is your definition of empty object? The one which does not have props?

**Comment by akshayraina-github** [comment]
Yes right sir, 
e.g const student = {};

**Comment by avkonst** [comment]
Then, you can use `globalUser.keys.length === 0` to check if an object does not have properties.
