### ISSUE TITLE
How can I handle special keywords?

### ISSUE THREAD

**Issue by weasteam** [avkonst/hookstate#214]
I got error in my code and it turns out it is because I used a keyword `value`.

```
I have a json file:
properties: {
    label: {
        title: "Label",
        type: "string",
    },
    value: {
        title: "Value",
        type: "string",
    }
}

data = useState(properties);
```

It will report error if I do:
```
data["value"].keys
```

How to resolve this problem?

**Comment by avkonst** [comment]
See this: https://hookstate.js.org/docs/nested-state#nested-state-method

**Comment by weasteam** [comment]
Thanks @avkonst 

It worked with `data.nested("value").keys`.
