### ISSUE TITLE
Add Downgraded to values of non-standard JS types automatically (WAS: Proxy state handling files)

### ISSUE THREAD

**Issue by mxdi9i7** [avkonst/hookstate#215]
I have a form state that handles the following fields: 
```
interface PostForm {
  title: string;
  body: string;
  category: string;
  subCategory: string;
  phone: string;
  files?: File[];
}

 const formState = useHookstate<PostForm>({
    title: '',
    body: '',
    category: '',
    subCategory: '',
    phone: '',
    files: []
  });
```
The `files` field expects some file objects from HTML file input. Then I would use it to append in a loop to a `FormData` object. However, I'm not able to grab the `files` field value directly from  `formState.value.files` because it's in a Proxy state, when I try to do `JSON.parse(JSON.stringify(formState.value.files))` it gives me an empty object when I'm sure there's value inside `files` before the parse. I'm wonder what's the proper way to parse the file object from this hookstate?

**Comment by arbob** [comment]
having the same problem with my app. A simple get() was working fine but now it gives me proxy object.

**Comment by avkonst** [comment]
Hi, state values have to be pure JSON encodable values, see more:  https://hookstate.js.org/docs/nested-state/#limitations-for-state-values
You can use Downgraded plugin to workaround this limitation and store other non-JSON serializable data to the state. THe Downgraded plugin disable state usage tracking for a property, which may result in extra undesired rerenders. The difference is here: https://hookstate.js.org/docs/performance-intro

**Comment by arbob** [comment]
Ok. However, it says here that `A state value should be a JS primitive, like string/number/etc., or null/undefined or a JS object/array containing other JS primitive properties, objects or arrays.` 
My state is an `array` with `strings` in it. Now, according to the docs, it should work as it is without giving me the `proxy` object, correct? Example code below:
`const store = createState({
  firstPerson: [],
  secondPerson: []
})`
Now, when calling this state using 
`const { firstPerson } = useState(store);
console.log(firstPerson.get());`
It should give me a plain array, but instead it's giving me a proxy.

**Comment by avkonst** [comment]
I thought your files are File objects. So my previous answer not applicable.
Hookstate State object returns Proxy for nested objects for tracking state usage. So your currently observed behavior is correct: `firstPerson.get()` will be a proxy. This proxy of an array should have correct behavior of an Array, including functions like map, filter, length, etc..

**Comment by avkonst** [comment]
Returning back to your original initial question. If your `files` array includes entries, the following: `JSON.stringify(formState.value.files)` should serialize these to an array of JSON representation of entries, strings as far as I understood in your case.

**Comment by arbob** [comment]
Is there another way to get plain array state other than using `downgraded` or `JSON.stringify`? As you said `downgraded` may result in extra undesired rerenders which I don't want.

**Comment by avkonst** [comment]
Once you get the full array state (using downgraded or json.stringify), it means the full array is marked as used. When it is updated, the component using it, will be rerendered. If you get the plain state value and it is not marked as used, you may not get enough rerenders. This is the dangerous zone, but have a look into Untracked plugin as described here: https://hookstate.js.org/docs/extensions-overview#special-extensions

**Comment by arbob** [comment]
Need to see how the final implementation looks like before commenting. However, as you said it here https://github.com/avkonst/hookstate/issues/238#issuecomment-934883972, giving the `getstate` a name is more intuitive, like `state.value.get()` instead of `state.origin.get()`. 

P.S. l'm in love with this library and use it in all of my production apps. :)

**Comment by avkonst** [comment]
Will get address in #106
