### ISSUE TITLE
Effectively insert new element into anywhere in the array

### ISSUE THREAD

**Issue by AnhTuan-AiT** [avkonst/hookstate#216]
Hi, I have a global state which structured like the following:
```JS
export const notificationState = createState({
  open: false,
  notifications: undefined,
  numUnRead: 0,
});
```
Here, value of notifications is an array contain notification objects which I fetch from server.

I use Server-Sent-Event to send new notification to client. 

Now, the question is how do I effectively insert this notification into anywhere in the array, may be first, may be second position,...? I found nothing in the documentation relevant to the use case I'm having. Is there a way to do it efficiently other than updating the whole array

**Comment by avkonst** [comment]
Please check out this doc: https://hookstate.js.org/docs/nested-state#partial-updates-and-deletions-1

**Comment by AnhTuan-AiT** [comment]
I read this section in the doc before I posted this question. 

I played with the code in the doc, when I append an element to the array, components that use other elements in the array are not rendered. 

But if I want to insert a new element at the beginning of the array, is there a way for components that use other elements in the array to not be rendered. That would be great If you can provide sample code to do that

**Comment by avkonst** [comment]
Sorry. It seems like your second paragraph says what it works like you need
it to be as per the 3rd paragraph. Is not it?

**Comment by AnhTuan-AiT** [comment]
The content of the 2nd paragraph is about what I know and understand about hookstate, about its features and how it works, through reading the doc and playing with sample code, I need you to confirm if what I understand is correct or not, if any point is incorrect, can you give me feedback?

The third paragraph is just a summary, briefly rewrite the content of the second paragraph.

**Comment by avkonst** [comment]
What you said os correct. Adding an element to an array changes the state
of the entire array so places where other elements are used will rerender
too as it is impossible to trace / detect how elements get selected from an
array in the first instance. Unfortunately very little can be done about it
as it is highly dependent on react behaviour.

**Comment by AnhTuan-AiT** [comment]
OK. Thank you for the useful information you bring and the quick response <3
