### ISSUE TITLE
calling set with new object where one property is an array doesn't work

### ISSUE THREAD

**Issue by from-nibly** [avkonst/hookstate#218]
I have a state value that represents the response from a backend that is paginated.

the object looks like this

```json
{
  "data": [...],
  "totalCount": 1,
  "page": 0,
  "size": 20
}
```

when I call set with

```ts
state.set({ ...resp.data,});
```
It's updating totalCount, page, and size, but not the data array.

Not all of my responses are paginated so I would like to avoid setting the data array explicitly.

**Comment by from-nibly** [comment]
hmm maybe it's not always even partially updating the data?

I'm logging the result using something like this


```ts
state.set(resp);
console.log('look at me', state, resp);
```

and it's printing two different proxy objects.

**Comment by from-nibly** [comment]
Also of note. It looks like the value is updating

```ts
state.set(resp);
console.log('look at me', state, resp, state.value);
```
is showing that `resp`, and `state.value` are the same but `state` is the old value.

**Comment by avkonst** [comment]
Hi,

If your `resp` is Proxy, it is likely coming from a 3rd party library wrapping it in a proxy. Is it Apollo client? You would better unwrap it from their proxy before setting as a state value.

Next, how do you know that `state.value` is new and `state` is old? What does it mean old?

Finally, I would like to get a reproducer. I can know what is happing in your applications code based on the little description above.

**Comment by from-nibly** [comment]
I'll see if I can build something to reproduce this.

To your first question: It's just an axios response data object. So shouldn't be any weird proxy / non standard data types. I miss spoke earlier when I said it was two different proxy objects, one is a proxy and the other is just a regular object.

To your second question: in the console.log statement above I'm printing both the state and the state.value out at the same time. and they have different values. I know the state value is old because I'm adding a uuid to the data going in and keeping track of it through the logs.

**Comment by avkonst** [comment]
Please, reopen the ticket when you have a reproducer or more information for me to act on this.
