### ISSUE TITLE
Just want to share how much I love this library and how much time it has saved me

### ISSUE THREAD

**Issue by dioptre** [avkonst/hookstate#220]
Investigated a lot of new state libraries and thought this was the best. This honestly has made my work profoundly better and easier.

Thank you

**Comment by avkonst** [comment]
Hi, I am very glad to hear it. Thank you very much for letting me know. If you could share and spread few words about the library, maybe a blog, it will be a great help for the project.

**Comment by avkonst** [comment]
Closing with a little blog post: https://dev.to/avkonst/a-github-issue-report-which-makes-you-happy-1ff6
