### ISSUE TITLE
State array not updating.

### ISSUE THREAD

**Issue by kumardennis** [avkonst/hookstate#222]
`   cacheState.set((cacheList) =>
      cacheList.filter((item) => item.uuid !== uuid)
    );`

is what I am trying to remove one element and update. Am i missing something ?

**Comment by kumardennis** [comment]
Also, when i try 
`    const newArr = shoppingListCache.filter((item) => item.uuid !== uuid);

    cacheState.set(newArr);`

I get error `×
RangeError: Maximum call stack size exceeded`

**Comment by kumardennis** [comment]
FYI, this should update another component which uses this state

**Comment by avkonst** [comment]
I do not see what might be wrong. Looks like operations with state are reasonable. If you would like us to advise further, please submit a reproducer in a repository or some playground. Unfortunately it is impossible to know what causes the problem for you having only the information you provided

**Comment by kumardennis** [comment]
Aha, i was lazy loading the other component, and it was sort of dependent on localStorage as well, so everytime it loaded it refreshed the state with localstorage. Anyway great tool! And thanks for replying so quick!
