### ISSUE TITLE
Support setting/getting undefined paths

### ISSUE THREAD

**Issue by parisholley** [avkonst/hookstate#224]
Use Case:

There is a form object (say, DTO for REST or GraphQL parameter), that has nested optional arguments:

```typescript
interface Argument {
  root: string;
  nested?: {child: string}
}
```

Currently, in order for hook state to support writing to nested objects which do not exist yet, you have to put empty objects in the state:

```typescript
const state = useState({root: 'foobar', nested: {} as any});
```

If you do not insert an empty object, code like this will break:

```typescript

const scoped = useState(state);

// nested = undefined error
scoped.nested.child.set('wee');
```

Currently my project has these empty objects defined everywhere and this is something that can easily bite you at runtime depending on how things are setup. 

Is it feasible for the library to support constructing missing object paths?

**Comment by avkonst** [comment]
There are few points here:

1. By the initial design, Hookstate copies JS behaviour in there. For example, the following plain JS would fail:

```js
let state = { root: 'foobar' }
state.nested.child = 'wee'; // nested is undefined here
```

2. The requirement to init parent props before setting nested makes it explicit. I prefer explicit over implicit. I am not convinced that Hookstate should change it.
2. If we change it as you propose, the following will lead to hard to catch bugs in applications: `state.nested.child.access.unknown.prop.by.mistake.and.so.on.set(...)` would make an auto constructed object which might be not what users wanted if it was not a mistake and was constructed explicitly.
3. Even, if we decide to change it, it would be non-backward compatible change as applications may need to differentiate between null and set object (even if it an empty object)

It can not be a plugable behavior either as it is not something what plugins can change without extending core hookstate api.

**Comment by parisholley** [comment]
1. Correct, though in the scope of state management/hookstate, there is no idiomatic way to express the following:

```typescript
let state = { root: 'foobar' }
if(!state.nested){
  state.nested = {};
}
state.nested.child = 'wee';
```

If you were using a traditional reducer pattern state system, the above would be possible (and could be hidden from the consumer).

2/3. I don't disagree, given that the API already has "explicit" path "extensions" (eg: `ornull`), something like `state.nested.safe.child` or `state.nested('nested', true).child` or `state.safe('nested').child` could make this opt-in behavior.

4. i think the proposal in 3 would be backwards-compatible

> It can not be a plugable behavior either

If 2/3 is not a solution, would we extend core to support this behavior using existing plugins or is this a new paradigm?

**Comment by avkonst** [comment]
Interesting ideas.

ok. extending nested(...) (or providing a new equivalent api) which would set the default value on undefined, would be possible. One question: when would this 'set the default value on undefined' trigger actual rerender (ie. notify subscribers about state change)?

**Comment by parisholley** [comment]
given that the .nested() call would happen during render, having it fire-off a re-render would probably not be ideal (unless hookstate already has a concept of delaying state changes until after render).

in the case of subscribers, i assume you mean where a parent component is listening for `state.get()` and a child component would call `state.safe('nested')`, interesting point. in terms of my use case, it isn't needed, because a null/undefined value would not change behavior (even though the key exists). but someone else may care about the existence of keys, regardless of values (and that difference is technically a change that would warrant a re-render).

in practice, i suppose rendering the parent is fine, as most cases where you would use nested like this, it isn't likely a parent is going to subscribe to the entire sub-object (i'd consider that a smell)

**Comment by avkonst** [comment]
Yes, parent should not watch child for "in-future" set event.

**Comment by avkonst** [comment]
I wonder if the following https://medium.com/my-coding-life/extension-method-in-typescript-66d801488589 (search for Extending third-party module) would help you to add an extension method to `StateMethods` interface without changing hookstate core?

```ts

// ./extensions.ts file:
import * as moment from 'moment';
declare module 'moment' {
  export interface Moment {
    toTaiwaneseYear(): number;
  }
}

(moment.fn as any).toTaiwaneseYear = function () {
  const _self = this as moment.Moment;
  return _self.year() - 1911;
}

// test it: 
import * as moment from 'moment';
import './extensions';
const m = moment();
console.log(m.toTaiwaneseYear()); //107
```

**Comment by parisholley** [comment]
certainly could do that as a workaround, but in general, i think this should be core as the library as it stands isn't really suitable for complex form work, and this is a step towards making it cleaner for those use cases (i've been using my validation/form plugin on production for a few apps, so i'll be issuing a PR for that at some point).

**Comment by avkonst** [comment]
Well, it is suitable, it just requires you to be explicit with initializing/building your state value. Could you please share your code of the extension method when / if you figure it out?

**Comment by avkonst** [comment]
did you come up with the extension methods?

**Comment by avkonst** [comment]
Hi, i did not mean to extend nested method. I was asking about adding an
extension method outside of the core like in the example from the blog

**Comment by avkonst** [comment]
Yes, this was my suggestion.
Thinking more about your proposal to add new method which would auto-set undefined property to an empty object. I think it is not sound. Few reasons below:

1. property read has a side effect: which is object mutation as well as re-rendering
2. It is unclear how it would guarantee strong type safety. Consider the example:
```
interface A {
    a_prop: B?;
}
interface B {
    b_prop: string
}

let state = useState<A>({})
// let's say here it magically converts undefined to an object
// so the following should be typed as State<B>,
// but instead a real inferred type will be State<B | undefined>
// and the real value will be State<{}>.
let nestedState = state.a_prop;
```

**Comment by parisholley** [comment]
1. my goal is less about mutating the state as you read, but to allow the proxy to nest without breaking. in my scenario, the types look more like (no undefined):

```typescript
interface A {
    a_prop: B;
}
interface B {
    b_prop: C
}
interface C {
    c_prop: string
}
```

in my case, I want to represent a "future state", the object I eventually want built, which passes validation and can be sent to the server. through code, I want to be able to build a form, without having a bunch of temporal state "sub objects", that have to be built in its entirety first before it can be added to the overall state object. UI example is having  one large model object editable across multiple tabs, etc.

so somewhere, I want to be able to do:

```jsx
<Input state={state.a_prop.b_prop.c_prop} onChange={() => state.a_prop.b_prop.c_prop.set('foo')} />
```

where `state.a_prop.b_prop.c_prop.get()` can safely return undefined, and then upon set, build the object graph.

2. regardless of what library or methodology you use, type safety of the final model will never reflect the "form model". in the case of redux, your similarly going to have an object in a "bad" state until the user fills out the form, a validation framework is what provides your "middle ground". you do bring up a good point though, that the standard `useState()`paradigm may not be the right approach. perhaps something like `usePartialState()` where the entire object graph is converted to:

```typescript
interface A {
    a_prop?: Partial<B>;
}
interface B {
    b_prop?: Partial<C>
}
interface C {
    c_prop?: string
}
``````

that way it is obvious to the user what the intent is and then the proxy is more like a `PartialState<A>` or `PartialStateMethods<A>`

**Comment by avkonst** [comment]
Well, if we add PartialState concept, it would make it type safe. But this addition is a huge change to the library.

**Comment by parisholley** [comment]
i'd say arguably a good change :) transient form state is such a common use case in the majority of apps. if we can agree on an architecture, i'm happy to do the work

**Comment by avkonst** [comment]
First of all I would like to understand how we address "property read has a side effect: which is object mutation as well as re-rendering". I understand your goal is "my goal is less about mutating the state as you read, but to allow the proxy to nest without breaking." but it does not help to the problem 1 I described above. Reading nested state on undefined was an error by design. Changing it is non backward compatible, but it is also unclear what the correct behavior should be. I can think of only setting the state to `{}` on read of undefined child

**Comment by parisholley** [comment]
perhaps it would help to talk about this outside of how the library is currently implemented.

for sake of conversation, i think in terms of `data state` (what user initialized with) and `library state` (hookstate internals).

in my mind, the underlying design could behave as follows:

```typescript
const proxy = useState({ foo: { bar: { baz: '123' } } });
```

simply using the proxy via standard get accessors does not mutate the data state, but instead returns a new proxy for every accessor, appending the path along the way, eg:

```typescript
proxy.foo.bar.bum.bay
```

may be represented as 

```
Proxy(
  path: ['foo'],
  get(),
  set()
)
```

```
Proxy(
  path: ['foo','bar'],
  get(),
  set()
)
```

```
Proxy(
  path: ['foo','bar', 'bum'],
  get(),
  set()
)
```

```
Proxy(
  path: ['foo','bar', 'bum', 'bay'],
  get(),
  set()
)
```

at this point, if i were to do

```typescript
proxy.foo.bar.bum.bay.get()
```

I would expect to get back `undefined`, and if I were to do

```typescript
proxy.foo.bar.bum.bay.set('test')
```

i would expect it to traverse the path, creating objects along the way, until it can satisfy the set. given that hook state only supports primitives, don't have to worry about if it is a map or some other special object.

a complexity with this approach would be introduced because when `get()` is called on an undefined path, while simple enough to return undefined, it does need to be able to response/re-render when that path comes to life. in this case, I would expect listeners to get registered along the way:

```
proxy = Proxy(
  path: ['foo'],
  get(),
  set()
)
```

```
proxy = Proxy(
  path: ['foo','bar'],
  get(),
  set()
)
```

```
proxy = Proxy(
  path: ['foo','bar', 'bum'],
  get(),
  set()
)

root.register(proxy, ['foo','bar', 'bum'])
```

```
proxy = Proxy(
  path: ['foo','bar', 'bum', 'bay'],
  get(),
  set()
)

root.register(proxy, ['foo','bar', 'bum', 'bay'])
```

that way, upon set, the library state can notify any listeners, unregister them, and everything behaves as normal. given that sets should only happen during user interaction, the performance implications of it should be minimal. 

the current [onnull](https://hookstate.js.org/docs/nullable-state/#dealing-with-nullable-state) approach is limited in that it is only useful if the state being modified is a flat object. your only choices today to work within the current implementation is:

* ignore type safety and put an invalid object in state so that hookstate doesn't see undefined paths
* introduce side-effects in your rendering (whether it be some new api get method or useEffect with a set state), which is not a good solution
* introduce lazy-evaluation (what i describe above) for getting/setting

while lazy-evaluation would introduce a different behavior for undefined values, i think in practice it is backward compatible. without this feature, if someone tried to do what I am proposing, they would be presented with runtime errors and have to design around it (without the library). I can't think of a situation where someone may have built their components around how hookstate handles undefined values today.

**Comment by avkonst** [comment]
Controversial: I have an app and deal with undefined paths: on render I check using `ornull`, on set I just create a path inserting an object first before setting a property of an object.
Anyway, I can potentially add a toggle flag to trigger the behavior you want. I can also expose get and set with the desired behavior of the StateMethodImpl, but those would not be visible on the State type. It will give you a foundation to build usePartialState plugin outside of core and try it in apps. Once we confirm that it delivers value, we will think how to expose new set and get behavior officially.

**Comment by parisholley** [comment]
I wouldn't say that is controversial, just painful :)

fair enough, i'm still battle testing my validation stuff so don't mind adding another thing

**Comment by avkonst** [comment]
Planning support for extension methods in Hookstate-4.

**Comment by parisholley** [comment]
@avkonst looks like you got a lot going in v4, let me know if i can help

**Comment by avkonst** [comment]
Hookstate 4 allows to add extension methods. So it is possible to add an extension method which does get and constructs the object on get if it is undefined. Documentation for extensions API is pending. Extension methods are fully type safe, so, it is possible to remove undefined from returned types and so on.
