### ISSUE TITLE
@hookstore/persistence stores undefined

### ISSUE THREAD

**Issue by nyankers** [avkonst/hookstate#227]
When storing a state that's `undefined`, the Persistence plugin will store this `undefined` as the string `"undefined"` which fails on future loads.

Something like this can recreate the issue:
```
const state = createState(undefined);
state.attach(Persistence("test"));
```

Here's a code sandbox: https://codesandbox.io/s/sweet-bardeen-hhybx?file=/src/App.js

You'll have to refresh the page with the above example of course.

**Comment by avkonst** [comment]
Hi, thanks for submitting. Would you be able to contribute a fix for it? I guess the plugin should not save value to localstorage if it is given undefined to save.

**Comment by nyankers** [comment]
I'm not sure what the "correct" behavior should be, e.g. whether the plugin should not save `undefined` or whether it should be able to load `undefined` (or if state being set to `undefined` itself is an error). All I know is that failing later on is not good.

As for contributing a fix, I might be able to tomorrow or so, depending on the above.

**Comment by avkonst** [comment]
Maybe just do not save and clear existing state in localstorage if it is
provided as undefined.

**Comment by avkonst** [comment]
Latest localstored plugin allows to inject custom storage engine, where an application can provide a handling for this corner case.
