### ISSUE TITLE
vue__WEBPACK_IMPORTED_MODULE_4__.default is undefined

### ISSUE THREAD

**Issue by kishanvaishnav** [avkonst/hookstate#229]
vue__WEBPACK_IMPORTED_MODULE_4__.default is undefined

i am facing this issue install vue-carousel
how is solve this

**Comment by avkonst** [comment]
Hi, sorry this is not a Hookstate issue. If you believe it is, please create a reproducer repository clearly showing the issue and reopen the ticket. Thanks.
