### ISSUE TITLE
How to store file objects?

### ISSUE THREAD

**Issue by weasteam** [avkonst/hookstate#236]
I searched but I did not find any answers.

When a user selects multiple files, I stored them in the state and then upload them one by one. When I use get() method to read the file and associate it with `file` attribute during the POST. The uploading failed. My further investigation indicated the variable returned from the get() is different from the original File object.

Any ideas on how to store file objects?

**Comment by avkonst** [comment]
Please reopen the issue if it does not answer your question

**Comment by weasteam** [comment]
thanks, that helps.
