### ISSUE TITLE
RangeError: Maximum call stack size exceeded (native stack depth) when setting object on merge

### ISSUE THREAD

**Issue by sammysium** [avkonst/hookstate#239]
I am just setting up the library and want to set the following in my state:

      `   o.merge({"activatedGroup": {}, "activatedRoute": "Config", "activatedSeason": {}, "activatedSector": {}, "activatedSite": {}});`

it throws error:
```
 WARN  Possible Unhandled Promise Rejection (id: 0):
RangeError: Maximum call stack size exceeded (native stack depth)
RangeError: Maximum call stack size exceeded (native stack depth)

```
From this https://hookstate.js.org/docs/typedoc-hookstate-core/#merge, merge can take an object. How can I do this?

**Comment by avkonst** [comment]
Could you please prepare a reproducer? It is hard to say what is not right using only the description.

**Comment by avkonst** [comment]
Hi guys. Sorry I need a reproducer app published for this. I can not tell what is going on here.

**Comment by sourabhchotiads** [comment]
@avkonst hello, i have managed to fix the max call stack issue by chunking the whole object into smaller objects to set and update but now i am facing a strange issue, when i fill all the form data and move to next page than i have a button there to go back to previous page and when i click on that link, it shows me _this.child(...).get is not a function but when i refresh the page one time than every thing works fine, can you tell me what i am doing wrong here.

my code is this 

`useEffect(() => {
    if (
      typeof state.get().bookingConfirm !== "undefined" &&
      state.get().bookingConfirm.status == 1
    ) {
      router.push("/500");
    }

    if (state.get().agentEmail) setAgentEmail({ ...state.get().agentEmail });

    if (Object.keys(state.get().secondPassenger).length > 0) {
      setSelectedAddress(
        JSON.parse(JSON.stringify(state.get().selectedAddress))
      );
    }

    if (
      typeof state.get().lookupAddress !== "undefined" ||
      state.get().lookupAddress.length > 0
    ) {
      setLookupAddress(JSON.parse(JSON.stringify(state.get().lookupAddress)));
    }

    if (showForm === 1 && Object.keys(state.get().leadPassenger).length > 0) {
      setInputs(JSON.parse(JSON.stringify(state.get().leadPassenger)));
      setAddressToggle(true);
    } else if (
      showForm === 2 &&
      Object.keys(state.get().secondPassenger).length > 0
    ) {
      setInputs(JSON.parse(JSON.stringify(state.get().secondPassenger)));
      setIsSameAddress(isSameAddress);
    }
  }, []);`
  
  and this is my local storage 
  
https://user-images.githubusercontent.com/86597939/137494039-10e7891b-58da-4510-96ff-2bb2b27e4165.png

Sorry i am not able to publish an demo app right now

**Comment by avkonst** [comment]
this could be associated with page autoreload and incorrect state capture / restore during page reload. Again, I can not say anything more without the reproducer.

**Comment by avkonst** [comment]
please reopen if outstanding questions remain
