### ISSUE TITLE
Project Roadmap 

### ISSUE THREAD

**Issue by shimorojune** [avkonst/hookstate#242]
I have been a long term user of hookstate and was wondering if there was some way to get started on contributing to the project. 

I was thinking if there was any possibility of hosting a roadmap or something that could help people like me understand what is in the works so that we could try and pitch in with PRs.

**Comment by shimorojune** [comment]
I have faced that frustrating issue of dependency lists for `useEffect` and `useCallback`, peered through the issues here, and saw that the best solution was to essentially suppress the eslint warning, which kind of sucks when we have to keep doing that for every instance that problem arises (which is many, when you update state on page loads and stuff).

I'd be really interested in trying to fix this one. The code seems well documented but still would take some time to get up to speed. How would you suggest getting started on it?

**Comment by avkonst** [comment]
See the implementation proposal details here: https://github.com/avkonst/hookstate/issues/215#issuecomment-948043020
