### ISSUE TITLE
React Hooks: Callbacks with Hookstate possible?

### ISSUE THREAD

**Issue by malte94** [avkonst/hookstate#247]
What I am really missing compared to Class components are the callbacks. Yes, you can use "useEffect()", but with growing states this syntax starts looking a bit messy.

Is that possible with Hookstate? If not, would be a cool Feature Request I think.

```
  changeCopyState() {
    this.setState({ copied: true }, () => {
      setTimeout(() => this.setState({ copied: false }), 1500);
    });
  }
```

**Comment by avkonst** [comment]
Could you please describe the problem you are trying to solve? And please
provide better description of what feature you require? Unfortunately i am
not able to understand it from the small code snippet you provided.

**Comment by tonisostrat** [comment]
@avkonst, I think what he's talking about is the second, optional argument that can be passed to React's internal `setState` method:

> The second parameter to setState() is an optional callback function that will be executed once setState is completed and the component is re-rendered. Generally we recommend using componentDidUpdate() for such logic instead.

**Comment by avkonst** [comment]
Thanks for the clarification. Unfortunately it is impossible to hook into
the moment after a component is re-rendered. It is React limitation. React
does not give any control to hook into 'after re-render complete' event. If
you want to execute a callback after a state is updated you can do it via a
plugin: https://hookstate.js.org/docs/writing-plugin

**Comment by avkonst** [comment]
@tonisostrat thanks for clarifying. setState is not exposed in the React.useState. So can not do much about it.
