### ISSUE TITLE
Reserved Words Issue

### ISSUE THREAD

**Issue by jgozner** [avkonst/hookstate#249]
Hello!

I'm trying to access a property of an object that uses that reserved word **keys**. It only fails when I use hookstate, it works in plain JS. 

```
import { createState } from '@hookstate/core';

//Fails
var testState = createState({
  keys:[1,2,3],
  parts:[5,6,7]
})

console.log(testState['keys'].value) //undefined
console.log(testState['parts'].value) // prints parts [5,6,7]

//Passes
var test = {
  keys:[1,2,3],
  parts:[5,6,7]
}

console.log(test['keys']) // prints keys [1,2,3]
console.log(test['parts']) // prints parts [5,6,7]
```
Working example: 

https://codesandbox.io/embed/hookstate-test-n1bvj?fontsize=14&hidenavigation=1&theme=dark

Any suggestions?

**Comment by avkonst** [comment]
use `testState.nested('keys').value` instead. It is in the docs

**Comment by jgozner** [comment]
I missed that completely. Thank you for your help.
