### ISSUE TITLE
Using state property in useCallback or useEffect deps trigger 103 error

### ISSUE THREAD

**Issue by mvandergrift** [avkonst/hookstate#253]
Not sure if there's anything that can be done about this, but the following code triggers a 103 exception due to the inclusion of the user.value.id property. 

```javascript
const loadData = useCallback(async () => {  
      if (!user.promised && user.value) {
        const userAccount = await getUserAccount(user.value.id);
        setUserAccount(userAccount);
      }  
  }, [user.promised, user.value.id]);
```

user is async global state and is working fine elsewhere. The 103 exception is being thrown without the loadData constant ever being called. I assume that this is due to useCallback evaluating the deps in the array when they bind?

**Comment by avkonst** [comment]
Hi, i am on annual leave offline. I will reply later.

**Comment by avkonst** [comment]
Yes, you are accessing user.value.id before it gets resolved from promise. You may try the following instead:
```
[user.promised || user.value.id]
```
