### ISSUE TITLE
Not Realtime change data Updated when .Set new value

### ISSUE THREAD

**Issue by bobwatcherx** [avkonst/hookstate#254]
i have problem my **global state not realtime update but i check my console BROWSER data is updated**

my code :
**app.jsx**
`import {nama,number} from './store'
import {useState} from 'react'
export default function App(){
  const [globnama] = useState(nama)
  const [globnumber] = useState(number)
    console.log(globnama.get())
   return(
    <div>
    {nama.get()}
    home {globnama.get()}
    <input onInput={(e)=>{
      nama.set(e.target.value)
      console.log(globnama.get())
    }}/>
    <button
    onClick={()=>{
      globnama.set("bayuar")
      console.log(globnama.get())

    }}
    >ganti</button>
    </div>)
}`

**my store js**
`import { createState, useState } from '@hookstate/core';
const nama = createState("jono")
const number = createState(0)

export {nama,number}`

**Comment by RunRanger** [comment]
You are using in store.js `createState` of @hookstate/core. But at App.jsx you are using `useState` from 'react'.
Use also the `useState` from @hookstate/core.

**Comment by avkonst** [comment]
Thanks @RunRanger  for answering the question.
Please reopen if still unclear.
