### ISSUE TITLE
Using Hookstate with react-native-maps results in HOOKSTATE-205

### ISSUE THREAD

**Issue by Livijn** [avkonst/hookstate#258]
I am getting this error when using hookstate with [`<Polyline>`](https://github.com/react-native-maps/react-native-maps/blob/master/lib/components/MapPolygon.js) from `react-native-maps`.

> Error: HOOKSTATE-205 [path: /points]. See https://hookstate.js.org/docs/exceptions#hookstate-205

State:
```js
const locationSubscriptionState = createState<State>({
  points: [],
});

export default function useLocationSubscription() {
  const state = useHookstate(locationSubscriptionState);

  return {
    get points() {
      return state.points.get();
    },
    get points() {
      return []; // <-- gives no error
    },
    get points() {
      return JSON.parse(JSON.stringify(state.points.get())); // <-- gives no error & works
    },
  }
}
```

Usage:
```js
const locationSubscription = useLocationSubscription();
//....
<Polyline coordinates={locationSubscription.points} />
```

Why is this happening?

**Comment by stefanoeb** [comment]
By default, objects are proxied to enable usage tracking.
That means that even tho you call `get()` on the `points` property, it's not a pure object and the maps library doesn't seem to like that.

To fix it, you can do some things:
1. stringify/parse just like you did
2. Use the `Downgraded` plugin like so: `state.points.attach(Downgraded)`. More info: https://hookstate.js.org/docs/performance-managed-rendering
3. Rebuild the proxied object inline: 
```js
const coords = state.points.get();
return {latitude: coords.latitude, longitude: coords.longitude}
```

There are some talks on making it easier to get the pure object without usage tracking, I also agree that's confusing for someone trying this lib out and I have confused it already myself a few times.

**Comment by stefanoeb** [comment]
Here's some talks about having a `raw` or `origin` property: https://github.com/avkonst/hookstate/issues/238

**Comment by Livijn** [comment]
Okay, yeah that explains it. I thought `get()` and `.value` gave me the raw object. Thanks! 🙂
