### ISSUE TITLE
Passing state from nested hooks

### ISSUE THREAD

**Issue by Livijn** [avkonst/hookstate#259]
I am experiencing strange behaviour when passing state from nested hooks. The state is not updated in the component that uses the parent hook. Here is my setup:

```js
export default function useApi() {
  const state = useHookstate({ loaders: 0 });

  // ...

  return {
    get isLoading() {
      return state.loaders.get() > 0;
    }
  }
}

const feedState = createState({ /* blabla */});
export default function useFeedState() {
  const state = useHookstate(feedState);
  const api = useApi();

  useEffect(() => {
    // this one DOES run
  }, [api.isLoading]);

  return {
    // none of these work:
    isLoading: api.isLoading,
    get isLoading() {
      return api.isLoading;
    },
    api,
  }
}

export default function FeedList() {
  const feedState = useFeedState();

  useEffect(() => {
    // this one DOES NOT run
  }, [feedState.isLoading]);

  return feedState.isLoading ? <Text>loading...</Text> : <Text>Not loading...</Text>
}
```

Right now, my solution is to add a `isLoading` property on the `useFeedState` and updating it with a `useEffect`. However is doesn't feel right to duplicate the state like that.

**Comment by avkonst** [comment]
when you say 'none of these work' you do not say what actually does not work... please describe the problem, what is the actual behavior, what is the expected behavior, and preferably submit a reproducer.
Thanks

**Comment by Livijn** [comment]
Maybe I was unclear, but this is what I stated: 
> The state is not updated in the component that uses the parent hook. 

So when I said "none of these work", I meant that they don't update the parent hook. I'll try to create a reproduction sample.

**Comment by dphuang2** [comment]
Not a hookstate problem. Getters are cached: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by avkonst** [comment]
@dphuang2 thanks.
