### ISSUE TITLE
[ Plugin Persistence ]: request to have whitelist or blacklist like redux-persist 

### ISSUE THREAD

**Issue by rimsila** [avkonst/hookstate#268]
@avkonst , I really love to use Hookstate as my first option than redux or recoil but for plugin persistence is not easy to use like redux-persist, I hope we can get some feature like redux persist such as whitelist etc.
also I have custom persistence plugin from lib persistence for Hookstate (react-native) it has whitelist feature. then I custom it to web for React Js  but  I'm not sure i'm using the right way or not.
here is my [custom plugin](https://github.com/next-dev-team/nextjs-next-boilerplate/blob/main/src/plugins/persistence.ts) could you have a look and give some feedback to me or you can improve your existing @hookstate/persistence .
 Thanks you.

**Comment by avkonst** [comment]
Hi, there are no rules for plugins to be right or wrong. If it works for you, it is good. The persistence logic omitting some fields is useful and can be either included to the existing plugin or you can simply bring your plugin as a standalone, separate. Either way.
Just, be aware Hookstate 4 is coming and will likely have more ergonomics and features for plugins, but it is under development at the moment.

**Comment by rimsila** [comment]
Thank you for your reply. I will close this issue and waiting for hookstate v4 thank you.

**Comment by avkonst** [comment]
I suggest you add your plugin to the list on the documentation website and refer from there to your repository
