### ISSUE TITLE
Is it possible to use proxy traps?

### ISSUE THREAD

**Issue by onattech** [avkonst/hookstate#272]
Hi, 
Is it possible to use proxy taps with hookstate, similar to the code below? 

```jsx
const salary = new Proxy({hoursWorked: 0, payout: 0}, {
    set:(o, _, value) => {
        o.hoursWorked = value
        o.payout = value * 10
    }
})

salary.hoursWorked = 8 // { hoursWorked: 8, payout: 80 } 

console.log(salary.payout) // 80

```

**Comment by stefanoeb** [comment]
Depending on what exactly you wanna do, you can also make a plugin to act as traps on the `.set` calls, as well as other "lifecycle" callbacks from a piece of state.
Here's the [docs about writing a plugin](https://hookstate.js.org/docs/writing-plugin)

**Comment by onattech** [comment]
Well, the example above is exactly what I want to do. Currently I wait for a change in 'hoursWorked' with the help of useEffect to update 'payout'. Wouldn't it better better to handle this internally with hookstate without the need of useEffect?

**Comment by avkonst** [comment]
Yes. You do not need to use useeffect. Handle it with hookstate lifecycle
callbacks

**Comment by onattech** [comment]
So, that means I need to write a plugin right?

**Comment by avkonst** [comment]
This is what I recommend. It is no more code than what you wrote above. You can probably use proxies too, but I have not tried and do not know all of the possible side effects from it.

**Comment by onattech** [comment]
Ok, I will go with a plugin. Thank you.

**Comment by onattech** [comment]
I have written the plugin and would like to share in case someone else needs something similar

```jsx
const SalaryPluginId = Symbol('SalaryPlugin');
function SalaryPlugin() {
    return {
        id: SalaryPluginId,
        init: () => {
            return {
                onSet: (data) => {
                    return data.value.weeklySalary = data.value.hourlyWage * 40;
                },
            };
        },
    };
}

const salary = createState({ hourlyWage: null, weeklySalary: null });
salary.attach(SalaryPlugin);
salary.set({ hourlyWage: 10 });

console.log(JSON.stringify(salary.get())); // {"hourlyWage":10,"weeklySalary":400}
```

**Comment by avkonst** [comment]
excellent, this is how you do it

**Comment by avkonst** [comment]
Probably possible but i have not tried and do not recommend it. You are
better to add new hookstate plugin which listens to onSet event and does
similar neighbor property value adjustments. It will be also more efficient
than proxy.
