### ISSUE TITLE
Invalid hook call - External functions

### ISSUE THREAD

**Issue by iboxgithub** [avkonst/hookstate#275]
Hi, 

I am using global state in my app and everything works great except when I try to clean up my code and externalise some functions. I have a State.js that is pretty classic
```
import { createState, useState } from "@hookstate/core";
const dataState = createState({
  test: false,
});
export const useGlobalState = () => {
  const data = useState(dataState);
  return {
    get: () => data.value,
    setTest: (_test) => {
      data.test.set(_test);
    }
  };
};
```

Then in Screen1.js, the function f1() works but not f2()... 
```
import {
  ext1
} from "./ExtFunctions";
import { useGlobalState } from "./State";

export default function Screen1() {
   const state = useGlobalState();
   const f1 = () => {console.log(state.get().test)}
   const f2 = () => {ext1(state)}
}
```

f2() uses an external function, please check below to see the function in ExtFunctions.js...
```
export const ext1 = (_state) => {
   console.log(_state.get().test);
   return;
};
```

..and this is the error I get, anyone would know how to fix this? I check this [link](https://reactjs.org/warnings/invalid-hook-call-warning.html#:~:text=Hooks%20can%20only%20be%20called,breaking%20the%20Rules%20of%20Hooks.) but didn't manage to make it work 

> [Unhandled promise rejection: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:]

**Comment by rimsila** [comment]
> Hi,
> 
> I am using global state in my app and everything works great except when I try to clean up my code and externalise some functions. I have a State.js that is pretty classic
> 
> ```
> import { createState, useState } from "@hookstate/core";
> const dataState = createState({
>   test: false,
> });
> export const useGlobalState = () => {
>   const data = useState(dataState);
>   return {
>     get: () => data.value,
>     setTest: (_test) => {
>       data.test.set(_test);
>     }
>   };
> };
> ```
> 
> Then in Screen1.js, the function f1() works but not f2()...
> 
> ```
> import {
>   ext1
> } from "./ExtFunctions";
> import { useGlobalState } from "./State";
> 
> export default function Screen1() {
>    const state = useGlobalState();
>    const f1 = () => {console.log(state.get().test)}
>    const f2 = () => {ext1(state)}
> }
> ```
> 
> f2() uses an external function, please check below to see the function in ExtFunctions.js...
> 
> ```
> export const ext1 = (_state) => {
>    console.log(_state.get().test);
>    return;
> };
> ```
> 
> ..and this is the error I get, anyone would know how to fix this? I check this [link](https://reactjs.org/warnings/invalid-hook-call-warning.html#:~:text=Hooks%20can%20only%20be%20called,breaking%20the%20Rules%20of%20Hooks.) but didn't manage to make it work
> 
> > [Unhandled promise rejection: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:]

I think your code is already working.

here is the test:
 https://codesandbox.io/s/hookstate-forked-0j7zgl?file=/src/App.js

**Comment by iboxgithub** [comment]
> > Hi,
> > I am using global state in my app and everything works great except when I try to clean up my code and externalise some functions. I have a State.js that is pretty classic
> > ```
> > import { createState, useState } from "@hookstate/core";
> > const dataState = createState({
> >   test: false,
> > });
> > export const useGlobalState = () => {
> >   const data = useState(dataState);
> >   return {
> >     get: () => data.value,
> >     setTest: (_test) => {
> >       data.test.set(_test);
> >     }
> >   };
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then in Screen1.js, the function f1() works but not f2()...
> > ```
> > import {
> >   ext1
> > } from "./ExtFunctions";
> > import { useGlobalState } from "./State";
> > 
> > export default function Screen1() {
> >    const state = useGlobalState();
> >    const f1 = () => {console.log(state.get().test)}
> >    const f2 = () => {ext1(state)}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > f2() uses an external function, please check below to see the function in ExtFunctions.js...
> > ```
> > export const ext1 = (_state) => {
> >    console.log(_state.get().test);
> >    return;
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ..and this is the error I get, anyone would know how to fix this? I check this [link](https://reactjs.org/warnings/invalid-hook-call-warning.html#:~:text=Hooks%20can%20only%20be%20called,breaking%20the%20Rules%20of%20Hooks.) but didn't manage to make it work
> > > [Unhandled promise rejection: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:]
> 
> I think your code is already working.
> 
> here is the test: https://codesandbox.io/s/hookstate-forked-0j7zgl?file=/src/App.js

@rimsila  thanks for your answer (sorry I was afk): I actually found where my issue is: with objects. Can you please check this repo:
https://codesandbox.io/s/hookstate-forked-lxk34x?file=/src/App.js
You will see that f1() works but not f2() whereas the only difference is that 1 calls globalState for a String, the other for an Object --> what am I missing here?

@avkonst sorry for not tagging as a question, my apologies

**Comment by iboxgithub** [comment]
ok so thanks to @rimsila I found that wrapping in an object helps (`console.log({..._state.get().test});`)
Nevertheless I still have an issue, not related to Hook call, as I can only make this code work on the Web ([link CS](https://codesandbox.io/s/hookstate-forked-lxk34x?file=/src/App.js)) but **not** in React Native ([link Expo](https://snack.expo.dev/@iboxgithub/demostate))
-> **_state.get() is not a function**

would you have an idea on why I have this issue @avkonst @rimsila ?

**Comment by rimsila** [comment]
@iboxgithub I found you have call a function has one param then you assign 2params to it. also for spread only for obj not text.
here is the new edit: https://snack.expo.dev/frBtEPFWj

**Comment by iboxgithub** [comment]
thanks a lot @rimsila it now works!
if I may, I have one last thing that I don't understand...and I am not able to replicate it in my Snack:
I keep on having the warning: **[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_state.get')]** whereas everything seems to work (cf screenshot below) any idea what could cause this?
Also, the warning is triggered twice which I also don't get...
below an extract of my ExtFunctions.js
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/5391993/163982436-8ad04a49-e628-4ecb-bf3d-0a862c38f9e2.png">

and here is the JSX extract of my component where I use the PlayOrPause function:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/5391993/163983450-0abd4ccc-984e-41ff-8471-f2c70c9664ad.png">

**Comment by rimsila** [comment]
> thanks a lot @rimsila it now works! if I may, I have one last thing that I don't understand...and I am not able to replicate it in my Snack: I keep on having the warning: **[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_state.get')]** whereas everything seems to work (cf screenshot below) any idea what could cause this? Also, the warning is triggered twice which I also don't get... below an extract of my ExtFunctions.js <img alt="image" width="1125" src="https://user-images.githubusercontent.com/5391993/163982436-8ad04a49-e628-4ecb-bf3d-0a862c38f9e2.png">
> 
> and here is the JSX extract of my component where I use the PlayOrPause function: <img alt="image" width="456" src="https://user-images.githubusercontent.com/5391993/163983450-0abd4ccc-984e-41ff-8471-f2c70c9664ad.png">

I don't know about it too. but I think my suggestion you should use normal custom hook then return data and logic want you want no need to use externalFunc. for me I use custom hook it's easy one
https://github.com/next-dev-team/rn-next-boilerplate-universal/blob/master/libs/store/src/lib/home/useHomeStore.ts

**Comment by avkonst** [comment]
I think a lot of your problems will get away if you switch to Typescript from pure JS if you have not already. I hope this question is cleared. I am closing the issue now.
