### ISSUE TITLE
setting state based on Asynchronous requests getting a Hookstate-106 exception

### ISSUE THREAD

**Issue by akivastr** [avkonst/hookstate#277]
I have an application wherein components are making asynchronous requests for data in a `useEffect` and then state is being set with the data. If the user navigates away from the page before the promise is resolved, the app crashes with a 106 exception, as state is being set after component unmount. How can I handle this scenario?

**Comment by avkonst** [comment]
two options for you: 1) detect unmount and cancel your async chain (here is some example: https://devtrium.com/posts/async-functions-useeffect) or 2) use https://hookstate.js.org/docs/asynchronous-state

**Comment by akivastr** [comment]
@avkonst thanks for your response. I would like to clarify that I am setting local state, not global state. Also, react doesn't throw any errors or warnings when you do the same using react state. For consistency we wanted to exclusively use hookstate instead of react state within the application. Is that the wrong approach or is there a better workaround for this specific issue?

**Comment by avkonst** [comment]
"Also, react doesn't throw any errors or warnings when you do the same using react state." React logs an error to the console log if you set a state for unmounted component. I would think the Hookstate does the same.. when you say: " If the user navigates away from the page before the promise is resolved, the app crashes with a 106 exception" what do you mean crashes?
