### ISSUE TITLE
Can't retrieve a state properly - Snack example provided

### ISSUE THREAD

**Issue by iboxgithub** [avkonst/hookstate#279]
Hi,

as you can see on this Snack: https://snack.expo.dev/@iboxgithub/demostate  I am not able to get the state of "test" in my ext1 function called from Screen1.js -> could you tell me what is wrong in my code?

thanks for your help

PS: I am not able to put a label myself on this issue but it should be: Question

**Comment by jigartankhupp** [comment]
@iboxgithub the issue has been in your createState functions,
if you commented out the tracks from your state.js file then you will be able to update the state without getting **"Maximum call stack size exceeded" error (KO 1)**
soundQueue: {
    // tracks: [{id: 0, title: 'title0'},{id: 1, title: 'title1'}],
    currentTrackIndex: 0,
    isPlaying: false,
  }

**Comment by iboxgithub** [comment]
why would the array cause this error though?

**Comment by avkonst** [comment]
Is this question cleared?

**Comment by avkonst** [comment]
Please reopen if not
