### ISSUE TITLE
A new version with just updated dependencies? And maybe an update to @hookstate/devtools?

### ISSUE THREAD

**Issue by kentlarsson** [avkonst/hookstate#280]
Hi! Thank you very much for this library! So far I love it!

I was wondering if it would be possible to get a new version with just updated dependencies? Like, the dependabot PR:s?

It's starting to be quite a while ago a new version was released. As a user that is a bit worrying.

Also, when using `@hookstate/devtools` we nowadays get  `npm WARN deprecated redux-devtools-extension@2.13.8: Package moved to @redux-devtools/extension.` when running `npm install`.

**Comment by kentlarsson** [comment]
(I don't seem to be able to tag it as a question, sorry if I missed something)

**Comment by avkonst** [comment]
Hey, I am working on Hookstate 4 where all this will be fixed and will include a lot more exciting features. It just takes time as I am extraordinary busy now... but it will arrive soonish

**Comment by kentlarsson** [comment]
Cool, thank you for the quick reply! It felt semi-all-right to check if a new version is on it's way, as I really appreciate what you do and don't want to "pressure" for anything. I'll be on the lookout! Have a nice weekend! :-)
