### ISSUE TITLE
Add Subscribable extenstion (WAS: Add a feature to subscribe for changes in state from outside any component)

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#282]
I want to perform some business logic (nothing ui related) when a state changes. Right now only way to subscribe is to do it inside a component using the useHookstate hook. I believe we should have a way to subscribe outside components also.

If you have used stores in Svelte, they allow us to subscribe to the store from anywhere.

**Comment by avkonst** [comment]
Please read the docs carefully. Especially sections 'global state' and
'writing a plugin' which describe what you want to achieve.

**Comment by nateshmbhat** [comment]
@avkonst the documentation says that : 

> The state is created by [createState](https://hookstate.js.org/docs/typedoc-hookstate-core#createstate). The first argument is the initial state value. The result value is an instance of [State](https://hookstate.js.org/docs/typedoc-hookstate-core#state), which can be used directly to get and set the state value outside of a React component.

What i want is not to just `get` or `set` the state from outside a component. What i want is a way to `subscribe` to changes in a state (or nested state) so that every time when that state gets updated, my callback function could be called.

This is similar to `store` subscription in svelte which is extremely useful.

Here's an example scenario. Whenever the app language changes in the global app state, i want to push the new app language value to a backend service. This kind of use case is common and it doesn't need someone to design and implement a plugin to be able to do this. (writing a plugin is considered as advanced usage and for this simple usecase, it doesn't need to require a plugin to be implemented imo)

**Comment by avkonst** [comment]
New extension will be added to Hookstate-4

**Comment by avkonst** [comment]
the extension has been implemented for Hookstate-4. Here is how to use it: https://hookstate.js.org/docs/extensions-subscribable

**Comment by nateshmbhat** [comment]
The example in the documentation doesn't show how to subscribe for the
state from outside the component and looks like ur passing the subscribable
extention into the usehookstate hook which again can only be used inside of
a component.

Let's say I have a service class that wants to subscribe for global state
changes. Since its not a component I can't do it right now.

**Comment by avkonst** [comment]
Call 'hookstate' function instead of useHookstate. It has the same
signature and features and can be called to create states from outside of
components.
