### ISSUE TITLE
Add documentation for `.fulfilled` for asynchronous state

### ISSUE THREAD

**Issue by rjclaasen** [avkonst/hookstate#283]
Thanks for this great tool! It's been a significant help.

I just checked, but it turns out that Asynchronous state supports a Promise's `.fulfilled` method[^1], even though that doesn't seem to be documented anywhere[^2][^3].

I personally assumed for quite a while that Hookstate did not support it, seeing as it isn't listed on the asynchronous state page[^4]. After struggling with a while to find a solution that would function similarly, I just tried to brute force see if it worked, and it did! 🥳 

Seeing as there is no actual code supporting the `.pending` Promise method either[^5], perhaps the documentation could be rewritten to imply that setting a Hookstate to a promise allows you to treat that state itself as a promise? I haven't dug deep enough in this codebase to know whether that is actually the case.

Thanks a lot for all of your work! Hookstate has been amazing for me & my team in building lightweight and flexible state management systems.

[^1]: Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#description
[^2]: https://hookstate.js.org/search?q=fulfilled
[^3]: https://github.com/avkonst/hookstate/search?q=fulfilled
[^4]: https://hookstate.js.org/docs/asynchronous-state
[^5]: https://github.com/avkonst/hookstate/search?q=pending&type=code

**Comment by avkonst** [comment]
Interesting... I did not expect a State object to work as a Promise successfully. Could you please share with me how you use Hookstate in this context?

**Comment by rjclaasen** [comment]
The goal in general was to attach a state to a JSON request so that I could reflect its state in the UI.

Short excerpt of my code:

```jsx
import React from "react";
import axios from "axios";
import Button from "react-bootstrap/Button";
import { useState } from "@hookstate/core";
// Some more kinda irrelevant imports. `invitationPath` is also imported & returns a string.

const ResendInviteButton = (props) => {
  const fetchState = useState();
  const accessibleState = !(fetchState.promised || fetchState.error);

  const resendInvitation = () => {
    fetchState.set(axios.patch(invitationPath(props.invitationId)));
  };

  return (
    <Button
      onClick={resendInvitation}
      disabled={accessibleState && fetchState.fulfilled}
    >
      Resend invitation
    </Button>
  );
};
```

This disables the button during the request. It does not become re-enabled if the request is succesful, but it does become re-enabled if the request failed, allowing the user to retry.

<details>
<summary>Detailed excerpt of my code</summary>

```jsx
const ResendInviteButton = (props) => {
  const fetchState = useState();
  const accessibleState = !(fetchState.promised || fetchState.error);

  const resendInvitation = () => {
    fetchState.set(axios.patch(invitationPath(props.invitationId)));
  };

  const iconClasses = (() => {
    if (fetchState.promised) return "fas fa-spinner fa-spin";
    if (accessibleState && fetchState.fulfilled) return "far fa-paper-plane";
    return "fas fa-paper-plane";
  })();

  const translationSubpath = (() => {
    if (accessibleState && fetchState.fulfilled) return "invite_success";
    if (!fetchState.promised && fetchState.error) return "invite_failed";
    return "resend_invite";
  })();

  return (
    <Button 
      onClick={resendInvitation}
      disabled={accessibleState && fetchState.fulfilled}
    >
      <i className={iconClasses} />
      {I18n.t(`javascripts.application.${translationSubpath}`)}
    </Button>
  );
};
```

Goals:
- Disable the button during the request
- Disable the button if the request is successful
- Show request todo/pending/done state in the button's icon.
- If request failed, change button text to reflect that & re-enable button.

</details>
