### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by robinzachmann** [avkonst/hookstate#284]
When using `hookstate v3.0.13` with React 18, I'm always getting a `HOOKSTATE-106` error, when using `state.set()` or `state.merge()` on a local state. 

Is there plans to support React 18 in the near future?

Related issue: #278

**Comment by avkonst** [comment]
yes, Hookstate 4 will be with react 18. However, I know that Hookstate 3 also worked with React 18. Maybe some things changed recently?

**Comment by avkonst** [comment]
checked and works with Hookstate 4 rc3
