### ISSUE TITLE
provide a way to remove or detach a plugin.

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#294]
Right now there is no way to remove or detach a plugin once added. There could be various usecases where one would want to detach a plugin based on some business logic.

**Comment by avkonst** [comment]
thanks for the ticket, I did not have a case for it, but yes it can be required

**Comment by avkonst** [comment]
Hookstate 4: extensions are provided at the time of state construction and can not be removed. However, extensions can add an extension method to disable itself, so it is possible for an extension to have the following API:
```
let state = useState("hello", () => MyExtension())
// assuming MyExtension has implementation for disableMyExtension method:
state.disableMyExtension() // extension needs to implement this method to disable itself
```
