### ISSUE TITLE
State is not showing up in Redux extension

### ISSUE THREAD

**Issue by janekkkk** [avkonst/hookstate#297]
I'm basically initializing the devtools in index.tsx and afterwards create a hook with global state. This is working perfectly, however it's not showing up in the [Redux DevTools extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) for Chromium browsers. 

I'm not sure if this is a bug, or I'm just using HookState incorrectly. Any help is greatly appreciated! 

The [demo](https://hookstate.js.org/demo-todolist/) is working for me by the way. 

Versions:
- @hookstate/core: 3.0.13
- @hookstate/devtools: 3.0.2

index.tsx
``` 
import React from 'react'
import { render } from 'react-dom'
import { APP_ID } from '@/shared/utils/constants'
import { App } from '@/core/App/App'
import '@hookstate/devtools' // Initialize the devtools <-----------

function initApp(): void {
  render(<App />, document.getElementById(APP_ID))
}

initApp()
```

useValuationVersion.hook.ts
```
import { createState, useState } from '@hookstate/core'

const valuationVersionStore = createState({
  valuationVersion: 0,
})

export const useValuationVersion = () => {
  const state = useState(valuationVersionStore)

  return {
    valuationVersion: state.valuationVersion.get(),
    setValuationVersion: (newValuationVersion: number) => {
      state.valuationVersion.set(newValuationVersion)
    },
  }
}
```

**Comment by avkonst** [comment]
Could you please check if it is fixed in Hookstate-4.0.0-rc12? We worked on improving it dev tools support in the version 4 recently.

**Comment by avkonst** [comment]
Please, reopen if it still does not work.

**Comment by janekkkk** [comment]
How do I use the devtools with Hookstate 4? No longer in a separate module? https://www.npmjs.com/package/@hookstate/devtools seems to be at 3.0.2

**Comment by avkonst** [comment]
Latest devtools 3.x works with the latest hookstate 4 release candidate.

**Comment by janekkkk** [comment]
I'm afraid it does not work yet. 
Versions: 
- "@hookstate/core": "^4.0.0-rc13",
- "@hookstate/devtools": "^3.0.1",

**Comment by janekkkk** [comment]
It does work in the demo, as I've said in the start of this thread. So it might be something that I'm doing wrong.

**Comment by avkonst** [comment]
Hi, do you try to see the local state in devtools?
Do you see the message in devtools that the local state is unmonitored?

**Comment by janekkkk** [comment]
I only see the @@init see the screen below
<img width="605" alt="Screenshot 2022-06-16 at 15 44 01" src="https://user-images.githubusercontent.com/8581521/184866459-7f25b8be-4ed9-415f-8e35-8efa794fa085.png">

**Comment by avkonst** [comment]
this is because it is a local state and local states are not traaced by default. it needs to be activated (see docs)... I will improve it in the Hookstate 4

**Comment by janekkkk** [comment]
Alright, then I'll close this issue.
