### ISSUE TITLE
Allow useStateLink to set an object value with cyclic dependencies

### ISSUE THREAD

**Issue by avkonst** [avkonst/hookstate#3]

**Comment by 18601673727** [comment]
Hi, given following data structure:
```json
   { 
      "id": 1, 
      "name": "a", 
      "children": [ 
        { "id": 2, "name": "a-a", "children": [ ... ] } 
      ] 
   }
```
console.log(exampleState.value) gives:
```
Proxy {   // expected, Proxy Object
  { 
      "id": 1, 
      "name": "a", 
      "children": [ 
        // Plain Object here, unexpected
        { "id": 2, "name": "a-a", "children": [ ... ] } 
      ] 
   }
}
```
So my question is: how to set recursive Proxy properly? Or this is the right issue we're trying to resolve?

Have tried to call `useStateLink` inside the loop but React gives "Rendered more hooks than during the previous render" error.

Thank you!

**Comment by avkonst** [comment]
Here is the example how to access state link of nested objects. https://hookstate.netlify.com/local-complex-from-documentation 
The key is to use 'nested' property of state link. 

The result of the console log is correct, expected.

Regarding the react error.  Usestatelink is a react hook, so you should follow react hook rules. The error react showed you is because you violated react hooks usage rule in your experiment.

This issue is open for the scenario when a property value of an object refers the object itself. It is not related to your questions.

**Comment by 18601673727** [comment]
Take the link you shared as example, how do we suppose to implement "Add sub task" to a `Task` itself?

**Comment by avkonst** [comment]
'tsskLink.nested.subtask.set(...)'. If in typescript, subtask property should be defined on the task type. In plain is, no other changes are needed. Have a look the documentation about nested property and path property.

**Comment by avkonst** [comment]
If you want to get the the subtask value, do this 'taskLink.nested.subtask.value' or this 'taskLink.value.subtask' . Both are identical. Also you can use 'get()' instead of 'value'

**Comment by 18601673727** [comment]
Hi @avkonst Sorry for my poor English, you seems don't understand what I was trying to say, but anyway could you please make [the code here](https://stackblitz.com/edit/react-ts-vmmqhn) works? This's based upon the example code from your documentation and my intentions, thanks in advance!

**Comment by avkonst** [comment]
I have added new example for you: https://hookstate.netlify.com/local-complex-tree-structure
It shows how to edit tree structured data use the state hook. Does it answer your question?

**Comment by 18601673727** [comment]
It does perfectly 👍

**Comment by avkonst** [comment]
Closing this one as a question. The original has been moved  to the new issue to keep it clean.

**Comment by avkonst** [comment]
I am glad it worked for you. Please help this project to grow by spreading few words about it in some posts / blogs. Thanks.

**Comment by avkonst** [comment]
@18601673727, I am glad it worked for you. Please help this project to grow by spreading few words about it in some posts / blogs. Thanks.

**Comment by 18601673727** [comment]
@avkonst Yea, for sure!
