### ISSUE TITLE
Extract a map (array) of all keys in a given state

### ISSUE THREAD

**Issue by vbuch** [avkonst/hookstate#302]
Hi there,
I have one more of those silly questions. I have a state of unknown or not well known shape. It has different properties here and there. How would you @avkonst go about generating an array of all the keys that this state contains. Obviously, one way is to get the whole .value from the topmost and base it on that. But then, imagine, you want to display all the values in table cells. Imagine:

State: {level1: {level2: 'something'}, moreLevel1: 'something else'}
Output:
<table>
<tr><th>level1.level2</th><td>someting</td></tr>
<tr><th>moreLevel1</th><td>someting else</td></tr>
<table>

So, yes, the challenge is extracting all the keys that lead up to a value. In other words flatenning a state.
Going recursively is hard because at the deepest level you will still get a Proxy and typeof checks won't work. I was looking at ways of using getUntracked but am so far failing to achieve it.

Thanks in advance for your time.

**Comment by avkonst** [comment]
There is method or property State.keys. It might help. You will need to use it with recursion to flatten out the paths.

**Comment by vbuch** [comment]
Yeah. Thanks. The trick is that the topmost component that does the flattening will force the rerendering of everything when it accesses all those keys.

**Comment by avkonst** [comment]
"Sounds like a change to a value deep inside won't trigger the rerendering of where this is used." - You need to get the value twice - once for the purpose of getting keys and flattening it, using untracked get, but then adding new keys will not trigger rerender. Next you need to use the values with tracking (i.e. normal get()) for the purpose of displaying in your table. If you do not want the rerendering of the parent component (table component), but want only rerender of the cells which changed, then you need to use scoped state. Check the docs about the scoped state.

**Comment by vbuch** [comment]
Here's roughly where I left it on Friday: https://codepen.io/vbuch/pen/PoRwOwr?editors=0011
The FlattenedPlugin is obviously far from perfect. All seemed to work at some point...

**Comment by avkonst** [comment]
I did not look closely, but I have added a line for you to activate scoped state:
![image](https://user-images.githubusercontent.com/3971413/178120654-b2da480c-a56e-459f-91b4-e5d86987d87b.png)
Check if it makes what you want to achieve. Please reopen if there are still questions remaining.
