### ISSUE TITLE
Access a value in state by its path

### ISSUE THREAD

**Issue by vbuch** [avkonst/hookstate#303]
Is there a way to access a value in state by its path? Was trying to find my way to that through the source and I see that Store has the ability, but I cannot access it anywhere after only having `const state = createState({a: {b: c: {1}}})`

**Comment by avkonst** [comment]
Yes, access by path is an internal method and is really an implementation detail. With Hoostate-4 you can add your own extension method named like nestedByPath([prop1, prop2]), which would drill down the state traversing the array.

**Comment by avkonst** [comment]
Please reopen if not answered
