### ISSUE TITLE
Document how to add extension method setWithContext (WAS: Feature request: Allow me to pass meta data to plugins.)

### ISSUE THREAD

**Issue by doncuomo** [avkonst/hookstate#309]
Hi, have been using hookstate for a while now and it seems pretty cool. We are running into a problem which I think could most easily be solved by allowing us to pass some meta data to plugins. I'll try to explain what we are doing and I'd like to hear your thoughts.

We would like to be able to update the store without updating everything to the server. The easiest way (I think) would be with meta data so we could set something like: skip_backend_save: true. That way we could have a grip on when updating to the server and when not.

### **What are you doing?!:**

We are currently working on pushing our changes to other users on a page. The setup we choose is in short this:

1. User answers a question
2. Plugin detects answer and pushes to server
3. Server saved and broadcasts to other users via websockets (Rails actioncable)
4. Other users receive new data, we update store.
5. Store detects changes, back to 2. 

5 is where things go south for us and where some meta data would really help us out. Then we could just update the stores with a 'skip_backend_save' flag. Something like this: answer.set(data, meta) would be enough.

We have found a 'kinda hacky' way around it for now. But we would like to know how you feel about this idea.

**Comment by OtherCroissant** [comment]
Really need this too to make use of the plugin functionality.

**Comment by avkonst** [comment]
Hi, thanks for the request. I had a similar need in my past project and solved it using either of 2 methods:
1. assign symbol property to a value of a state, limitation - a value should be an object. Assigning symbol property does not impact tracking and rerendering. These are simply ignored by the hookstate by can be used by the plugins
2. build a global variable - array/stack of context variables, and a function which would push a variable when called and pop when finished. The function needs to accept a custom callback (user's code), which would call it between push and pop. User's code in the callback can access the global variable of context variables

Alternatively, you can wait for the Hookstate-4 extension which will allow to associate metadata. Subscribe to: https://github.com/avkonst/hookstate/issues/34

**Comment by doncuomo** [comment]
Hi, thanks for the update. I will check it out once I have time. I'm heading on vacation soon :>

**Comment by avkonst** [comment]
Here is the documentation how to write an extension. The example shows how to add setWithContext method https://hookstate.js.org/docs/writing-extension
