### ISSUE TITLE
What does `Inf` in `StateInf` refer to?

### ISSUE THREAD

**Issue by ppwfx** [avkonst/hookstate#31]
What does `Inf` in `StateInf` refer to?

**Comment by avkonst** [comment]
It is **State Access Interface**. This is documented here: https://github.com/avkonst/hookstate#stateinf

**Comment by ppwfx** [comment]
Perfect, cheers, thanks for the clarification. I finally found the time to give it a try, I'm loving it so far! Thanks a lot!

**Comment by avkonst** [comment]
Maybe it should have better name. I am thinking to align names in version 2. I have not decided how StateInf, createStateLink, useStateLink and StateLink should be named. I thought to rename it as the following: StateInf => State, createStateLink => createState, useStateLink => useState, and keep StateLink. But it has got the downside that useState may collide with `React.useState`. Although it is possible to make useStateLink returning a value compatible with `React.useState` return type. In this case useStateLink could just replace `React.useState` without side effects (except it will have render optimisation). How do you think we should name the things?

**Comment by avkonst** [comment]
If you like it, I appreciate if you could spread few words about it to help the project to grow. Thanks!

**Comment by ppwfx** [comment]
In regards to naming in general, `Clean Code` has a pretty nice chapter on naming (2cents)

Other than that, I would avoid naming collisions. Makes it harder to read (ah in terms of hard to read, the code examples are pretty hard to read, as they don't have syntax highlighting, maybe just have a docs folders with .mds) Maybe you could also see it like this: State is component scoped and Links are what's interconnecting components. You could have `useLink` and `createLink` or similar to draw a clear line. I guess it's also easier to market as I think your goal is to become the next redux, which I'd really like to see happen. I really like the zero boilerplate way you enabled!

In regards to spreading the word, we are working on a couple of open-source projects that'll be released soon. I'm very happy to highlight `hookstate` as a dependency
