### ISSUE TITLE
How to setup/configure/install Persistence from '@hookstate/persistence'

### ISSUE THREAD

**Issue by twinedo** [avkonst/hookstate#316]
I've hookstate.ts like this :
`import {Persistence} from '@hookstate/persistence';`
`import {createState, useState, none} from '@hookstate/core';`
`import {Persistence} from '@hookstate/persistence';`

`const hookstate = {`
`     create: createState,`
`  use: useState,`
`  effect: useEffect,`
`  persistence: Persistence,`
`  none: none,`
`};`

`export default hookstate;`

is it enough to configure Persistence feature or did I miss something?
please help

Thank you

**Comment by avkonst** [comment]
hi, sorry, docs are in the transitionary state... they will get updated. I will close the ticket once it is updated for hookstate-4.

**Comment by avkonst** [comment]
persistence plugin has been deprecated. Please use `@hookstate/localstored` instead. Here is the example: https://hookstate.js.org/docs/extensions-localstored
