### ISSUE TITLE
Is it possible to store a react component in a global state and render it in another component?

### ISSUE THREAD

**Issue by AmirHo3einJS** [avkonst/hookstate#317]
Hello, I'm trying to store a react component in a global state but when I want to render it in another component I get this error:

![image](https://user-images.githubusercontent.com/101206088/181227641-7a1e18dc-a658-4b6f-a903-a8eb0d3b0045.png)

How can I solve this problem?

**Comment by AmirHo3einJS** [comment]
> Hello, I'm trying to store a react component in a global state but when I want to render it in another component I get this error:
> 
> ![image](https://user-images.githubusercontent.com/101206088/181227641-7a1e18dc-a658-4b6f-a903-a8eb0d3b0045.png)
> 
> How can I solve this problem?

I found the answer myself. You must use the .get() method with noproxy option

**Comment by avkonst** [comment]
The answer is correct, but Hookstate-4 adds noproxy automatically when deals with custom classes objects. What is the result of `State.get({ noproxy: true }).constructor?.name` for your state data?

**Comment by AmirHo3einJS** [comment]
> 

The result is `Object`

**Comment by avkonst** [comment]
Ok. Then yes, the only way is to use noproxy flag.
