### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by weekien** [avkonst/hookstate#32]
This library seems to be a promising one and clean to use but the documentation seem to me still lacking. I have no idea what happen underneath and if ok to  use multiple usestatelink ,or any rules to be taken on when using this library like must put usetstatelink on top of the functional component , cannot  put another userstatelink object into another usestatelink etc. more details guide will be more helpful.

**Comment by avkonst** [comment]
Agree. Will work on this in near future.

**Comment by avkonst** [comment]
WIP:
- 1.7.0 has got typedoc.
- integrating it to docusaurus with embedded live code samples

**Comment by avkonst** [comment]
Have a look the updated docs: https://hookstate.js.org/docs/getting-started

There are some placeholder pages, which will be completed later. There are other tickets to track it.
