### ISSUE TITLE
localstored from @hookstate/localstored for React Native

### ISSUE THREAD

**Issue by twinedo** [avkonst/hookstate#320]
i want to create global state with persist (@hookstate/localstored) in React Native
could someone give me reference??

i just create global state for authentication flow, but everytime I close and open the page, it return to initialState.
i think it should be store at persist or local storage in React Native.

**Comment by avkonst** [comment]
As far as I remember localstorage is not available in React Native. So, a new extension (or implementation at the app level) is needed to save the state to another type of storage.

**Comment by nateshmbhat** [comment]
you can accept optional interface from the user which has the same methods as localstorage from user.

**Comment by avkonst** [comment]
true. I will make this enhancement

**Comment by nateshmbhat** [comment]
Ohh that's unfortunate. If we don't have any direct fix for this, may be we can add the fix u gave 🤔.

I loved how typesafe hookstate 3 was automatically. Will miss that :(

**Comment by avkonst** [comment]
Is it a comment to a different issue?

**Comment by avkonst** [comment]
Could you please elaborate a bit more what you miss from hookstate 3?

**Comment by nateshmbhat** [comment]
> Is it a comment to a different issue?

Oops sorry, commented on a different issue. Am talking about the type completions I used to get in hookstate 3 for initial state and set.

**Comment by avkonst** [comment]
The latest localstored extension allows to provide storage engine to read and save data. An application can use it to utilize alternatives to localstorage.
