### ISSUE TITLE
Feature: isHookState utility

### ISSUE THREAD

**Issue by parisholley** [avkonst/hookstate#325]
It is common for me to have a prop support different wrapped types, eg: `D | (() => D) | State<D>`. currently I have a utility method like so:

```typescript
export default function isHookState<D>(obj: D | (() => D) | State<D>): obj is State<D> {
  if (obj instanceof Function) {
    return false;
  }

  if (obj && typeof obj['get'] === 'function') {
    return true;
  }

  return false;
}
```

it would be great to have some type of framework symbol appended to states that we can check against

**Comment by avkonst** [comment]
Make sense. I will do it. State is already marked by a symbol, so easy
ticket

**Comment by avkonst** [comment]
coming in the next hookstate-4 release 
![image](https://user-images.githubusercontent.com/3971413/208322570-797eb2f0-aa8c-4b60-8f4e-2fa48657d7fb.png)
