### ISSUE TITLE
Feature: give `none` an explicit type

### ISSUE THREAD

**Issue by parisholley** [avkonst/hookstate#326]
Because `none` has an `any` type, using eslint with the rule `@typescript-eslint/no-unsafe-argument` will complain everywhere it is used. perhaps we update api with a `state.clear()` or just use a dummy global class instance

**Comment by avkonst** [comment]
yes, makes sense

**Comment by avkonst** [comment]
You can add an extension method `clear()` to a state, if you would like to hide the usage of none.
