### ISSUE TITLE
Can i use Map data structure?

### ISSUE THREAD

**Issue by ermaliii** [avkonst/hookstate#329]
Hello, thanks for the work on this library, it's very intuitive and easy to use.

I was wondering if I can use Map or Set data structure and if so will it impact the performance in any way?

Thanks

**Comment by avkonst** [comment]
with hookstate 4 you can, but it will not track usage of Map/Set at a granular level... using any field from Map/Set will be equivalent to using all from rerendering performance

**Comment by avkonst** [comment]
please reopen if there are more follow up questions.
