### ISSUE TITLE
How to unsubscribe to a state once we subscribe to it ? 

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#333]
https://hookstate.js.org/docs/extensions-subscribable
In the docs page, you mention how to subscribe to state, there is no mention of how to stop subscribing or how to unsubscribe there.

**Comment by avkonst** [comment]
subscribe function returns a function, which should be called when you want to unsubscribe. Notice useEffect uses the unsubscribe callback returned by the subscribe function.

**Comment by nateshmbhat** [comment]
Thanks for the clarification !
It would be good if you also mention in the docs that we can monitor for state outside of component by using subscribable plugin directly with hookstate function.

**Comment by avkonst** [comment]
this is assumed that global state has access to the same extensions as the locally created state... but ok, I will mention it..

**Comment by nateshmbhat** [comment]
Hey thanks for the quick support ! Hookstate 4 basically covers every use case we came across in our project and its api is absolutely wonderful. Thanks for making such a great library for the community ❤️ 🙏🏻 
Cheers ❇️ ✨

**Comment by nateshmbhat** [comment]
**Subscribe Function not found !**
Getting error that subscribe function not found when using subscribable plugin.
```
import {hookstate} from '@hookstate/core';
import {subscribable} from '@hookstate/subscribable';

export const AppState = hookstate<AppStateType>(
  {
    isBottomTabBarVisible: true,
  },
  subscribable(),
);

AppState.subscribe( (v)=>console.log('value changed to : ' , v);
```


Typescript throws the following error for the above code.
```
Property 'subscribe' does not exist on type 'State<UserProfileType, {}>'.ts(2339)
```

**Comment by avkonst** [comment]
Thanks. Please consider to help the project by spreading few words about it.
