### ISSUE TITLE
How to use multiple extensions on a state ? 

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#334]
I want to use localstored extension on a state and also subscribe to log changes in that state. How to add multiple extensions to a state ?

**Comment by avkonst** [comment]
Use extend function. There is an example online for one of the extensions combined with many other extensions

**Comment by nateshmbhat** [comment]
I used the extend function but coudn't figure out how to specify the types
in the generic parameters for the hookstate function combining all the
interfaces of all extensions.

**Comment by avkonst** [comment]
Do not specify generic paratemers for hookstate function. Specify it one by one for extend function. See example here: https://hookstate.js.org/docs/extensions-snapshotable

**Comment by avkonst** [comment]
Docs for extensions are pending updates. It is v4 feature and I have not finished with docs and overall battle testing, hence it is only RC version for now.
