### ISSUE TITLE
In the localstored plugin, what happens if the value that you are storing is a "none" value

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#335]
when we are serializing objects, what is the result of JSON.stringify(none) where "none" is from hookstate.

if we delete a property which was stored in the state before, does it get deleted also in the localstorage when we are using the localstored plugin ?

**Comment by avkonst** [comment]
None for root state turns state into a promised state. None for nested
state removes the property from an object. I believe the plugin will see
nothing of it.

**Comment by nateshmbhat** [comment]
When we set the value of a state to be a promise.

Does the value remain the old value till the promise is resolved or
rejected ?

If someone sets the state to a promise and accesses the value of the state
before the promise is resolved, what value will they get?

**Comment by nateshmbhat** [comment]
Probably this is another thing worth mentioning in the docs.

**Comment by avkonst** [comment]
Does the value remain the old value till the promise is resolved or
rejected ?
No, getting the value while promised with raise an exception

**Comment by avkonst** [comment]
this is documented here: https://hookstate.js.org/docs/asynchronous-state
