### ISSUE TITLE
state.value / state.get() are not typesafe

### ISSUE THREAD

**Issue by speigg** [avkonst/hookstate#339]
```ts
const state = hookstate({answer: 1})

function computeTheAnswer(value:{answer:number}) {
  value.answer = 42
}

// no typescript errors, but hookstate will throw an error because the value was mutated directly
computeTheAnswer(state.value) 
```

The problem is essentially that `state.value` is typed as mutable, but throws an error if mutated; It seems that `state.value` is functionally a read-only value and should probably be typed that way if that is the intention. This way, the last line above will cause typescript errors, and it would be necessary to make the value mutable before passing it in (e.g., by calling `state.get({noproxy:true})`). 

**Suggestion:** 

`state.value and state.get()` should return a value that is wrapped in DeepReadonly<> type; `state.get({noproxy:true})` should return the original type. 

Alternatively, `state.value` should be mutable, and not throw errors when mutated.

**Comment by nateshmbhat** [comment]
same issue :/

**Comment by avkonst** [comment]
Agree about adding deep readonly. Will make it happened.
I disagree that noproxy should be allowed to be edited. This kind of changes for unwrapped by a proxy value are not tracked by hookstate and so can result in missed rerenders.
And so I disagree about .value and .get to return different result.

**Comment by avkonst** [comment]
coming in the final hookstate-4
