### ISSUE TITLE
add a function to check if the state object is a root state or not

### ISSUE THREAD

**Issue by nateshmbhat** [avkonst/hookstate#340]
checking if a state is root or not came handy in many places in my app when i was writing some generic functions that accepts a state object.

**Comment by avkonst** [comment]
Hi, 
I suggest you use this logic to get the answer you need:
`let isRoot = State.path.length === 0`
and wrap it into an extension method/property https://hookstate.js.org/docs/writing-extension and give this method/property whatever name you like (for example isRoot), so you can use it like:
`let isRoot = State.isRoot`

**Comment by avkonst** [comment]
Please reopen the ticket if it does not address your issue.

**Comment by nateshmbhat** [comment]
I got the logic for checking if it's a root state or not. But just thought
it will be a useful method to add to the state.
