### ISSUE TITLE
Is there a wayt to use createState with localstored?

### ISSUE THREAD

**Issue by rsofista** [avkonst/hookstate#347]
The example with `localstored` here https://hookstate.js.org/docs/extensions-localstored/ only shows with `useHookstate` and `createStore` doesn't have a second parameter like `useHookstate`.

Is it possible?

```
import { createState } from '@hookstate/core'
import { localstored } from '@hookstate/localstored'

export const storeUser = createState<User | null>(
	null,
	localstored({
		key: 'user',
	})
)
```

**Comment by avkonst** [comment]
yes, use `hookstate` function. createState will get removed soonish once the V4 becomes battle tested and stable
