### ISSUE TITLE
https://hookstate.js.org/demo-todolist is 404

### ISSUE THREAD

**Issue by Ofer-Gal** [avkonst/hookstate#350]
The link for the demo is broken

**Comment by avkonst** [comment]
The demo is now here: https://hookstate.js.org/docs/getting-started
Could you please let me know where is the link?

**Comment by avkonst** [comment]
thanks. I have fixed some... for some reason netlify redirects do not work anymore... Please keep this ticket open I will change the way the demo app is deployed.

**Comment by Ofer-Gal** [comment]
There are 2 more in https://hookstate.js.org/docs/scoped-state/ under 

> It is efficient
[huge form performance demo](https://hookstate.js.org/docs/scoped-state/performance-large-state).
and 
[huge very dynamic table performance demo](https://hookstate.js.org/docs/scoped-state/performance-frequent-updates).

Also later down 
[recursive state](https://hookstate.js.org/docs/scoped-state/recursive-state).
[performance related topic](https://hookstate.js.org/docs/scoped-state/performance-intro).

**Comment by avkonst** [comment]
fixed now
