### ISSUE TITLE
Compile errors todolist

### ISSUE THREAD

**Issue by Ofer-Gal** [avkonst/hookstate#351]
I just got your demo code from https://github.com/avkonst/hookstate/tree/master/docs/demos/todolist

ran Yarn
then yarn start
and got all these errors.
I have node v16.17.0 is this the problem? 

errors:

Compiled with problems:X

ERROR in ./src/components/SettingsState.ts 6:22-31

export 'hookstate' (imported as 'hookstate') was not found in '@hookstate/core' (possible exports: DevTools, DevToolsID, Downgraded, StateFragment, createState, none, postpone, useHookstate, useState)

ERROR in ./src/components/TasksState.ts 6:14-23

export 'hookstate' (imported as 'hookstate') was not found in '@hookstate/core' (possible exports: DevTools, DevToolsID, Downgraded, StateFragment, createState, none, postpone, useHookstate, useState)

ERROR in ./src/components/TasksViewer.tsx 224:9-16

export 'suspend' (imported as 'suspend') was not found in '@hookstate/core' (possible exports: DevTools, DevToolsID, Downgraded, StateFragment, createState, none, postpone, useHookstate, useState)

ERROR in ./src/index.tsx 10:0-9

export 'configure' (imported as 'configure') was not found in '@hookstate/core' (possible exports: DevTools, DevToolsID, Downgraded, StateFragment, createState, none, postpone, useHookstate, useState)

ERROR in src/components/SettingsState.ts:1:10

TS2305: Module '"@hookstate/core"' has no exported member 'hookstate'.
  > 1 | import { hookstate, useHookstate } from '@hookstate/core';
      |          ^^^^^^^^^
    2 |
    3 | const settingsState = hookstate({
    4 |     isEditableInline: true,

ERROR in src/components/SettingsState.ts:21:26

TS2339: Property 'isEditableInline' does not exist on type 'State<any>'.
  Property 'isEditableInline' does not exist on type 'StateMethods<any>'.
    19 |     return ({
    20 |         get isEditableInline() {
  > 21 |             return state.isEditableInline.get()
       |                          ^^^^^^^^^^^^^^^^
    22 |         },
    23 |         toggleEditableInline() {
    24 |             state.isEditableInline.set(p => !p)

ERROR in src/components/SettingsState.ts:24:19

TS2339: Property 'isEditableInline' does not exist on type 'State<any>'.
  Property 'isEditableInline' does not exist on type 'StateMethods<any>'.
    22 |         },
    23 |         toggleEditableInline() {
  > 24 |             state.isEditableInline.set(p => !p)
       |                   ^^^^^^^^^^^^^^^^
    25 |         },
    26 |         get isScopedUpdateEnabled() {
    27 |             return state.isScopedUpdateEnabled.get()

ERROR in src/components/SettingsState.ts:24:40

TS7006: Parameter 'p' implicitly has an 'any' type.
    22 |         },
    23 |         toggleEditableInline() {
  > 24 |             state.isEditableInline.set(p => !p)
       |                                        ^
    25 |         },
    26 |         get isScopedUpdateEnabled() {
    27 |             return state.isScopedUpdateEnabled.get()

ERROR in src/components/SettingsState.ts:27:26

TS2339: Property 'isScopedUpdateEnabled' does not exist on type 'State<any>'.
  Property 'isScopedUpdateEnabled' does not exist on type 'StateMethods<any>'.
    25 |         },
    26 |         get isScopedUpdateEnabled() {
  > 27 |             return state.isScopedUpdateEnabled.get()
       |                          ^^^^^^^^^^^^^^^^^^^^^
    28 |         },
    29 |         toggleScopedUpdate() {
    30 |             state.isScopedUpdateEnabled.set(p => !p)

ERROR in src/components/SettingsState.ts:30:19

TS2339: Property 'isScopedUpdateEnabled' does not exist on type 'State<any>'.
  Property 'isScopedUpdateEnabled' does not exist on type 'StateMethods<any>'.
    28 |         },
    29 |         toggleScopedUpdate() {
  > 30 |             state.isScopedUpdateEnabled.set(p => !p)
       |                   ^^^^^^^^^^^^^^^^^^^^^
    31 |         },
    32 |         get isHighlightUpdateEnabled() {
    33 |             return state.isHighlightUpdatesEnabled.get()

ERROR in src/components/SettingsState.ts:30:45

TS7006: Parameter 'p' implicitly has an 'any' type.
    28 |         },
    29 |         toggleScopedUpdate() {
  > 30 |             state.isScopedUpdateEnabled.set(p => !p)
       |                                             ^
    31 |         },
    32 |         get isHighlightUpdateEnabled() {
    33 |             return state.isHighlightUpdatesEnabled.get()

ERROR in src/components/SettingsState.ts:33:26

TS2339: Property 'isHighlightUpdatesEnabled' does not exist on type 'State<any>'.
  Property 'isHighlightUpdatesEnabled' does not exist on type 'StateMethods<any>'.
    31 |         },
    32 |         get isHighlightUpdateEnabled() {
  > 33 |             return state.isHighlightUpdatesEnabled.get()
       |                          ^^^^^^^^^^^^^^^^^^^^^^^^^
    34 |         },
    35 |         toggleHighlightUpdate() {
    36 |             state.isHighlightUpdatesEnabled.set(p => !p)

ERROR in src/components/SettingsState.ts:36:19

TS2339: Property 'isHighlightUpdatesEnabled' does not exist on type 'State<any>'.
  Property 'isHighlightUpdatesEnabled' does not exist on type 'StateMethods<any>'.
    34 |         },
    35 |         toggleHighlightUpdate() {
  > 36 |             state.isHighlightUpdatesEnabled.set(p => !p)
       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    37 |         }
    38 |     })
    39 | }

ERROR in src/components/SettingsState.ts:36:49

TS7006: Parameter 'p' implicitly has an 'any' type.
    34 |         },
    35 |         toggleHighlightUpdate() {
  > 36 |             state.isHighlightUpdatesEnabled.set(p => !p)
       |                                                 ^
    37 |         }
    38 |     })
    39 | }

ERROR in src/components/TasksState.ts:1:10

TS2305: Module '"@hookstate/core"' has no exported member 'hookstate'.
  > 1 | import { hookstate, useHookstate } from '@hookstate/core';
      |          ^^^^^^^^^
    2 |
    3 | export interface Task {
    4 |     id: string;

ERROR in src/components/TasksTotal.tsx:40:47

TS2339: Property 'length' does not exist on type 'State<any>'.
  Property 'length' does not exist on type 'StateMethods<any>'.
    38 |                 flexGrow: 2
    39 |             }}>
  > 40 |                 <div>Total tasks: {tasksState.length}</div>
       |                                               ^^^^^^
    41 |                 <div>Done: {tasksState.filter(i => i.done.value).length}</div>
    42 |                 <div>Remaining: {tasksState.filter(i => !i.done.value).length}</div>
    43 |             </div>

ERROR in src/components/TasksTotal.tsx:41:40

TS2339: Property 'filter' does not exist on type 'State<any>'.
  Property 'filter' does not exist on type 'StateMethods<any>'.
    39 |             }}>
    40 |                 <div>Total tasks: {tasksState.length}</div>
  > 41 |                 <div>Done: {tasksState.filter(i => i.done.value).length}</div>
       |                                        ^^^^^^
    42 |                 <div>Remaining: {tasksState.filter(i => !i.done.value).length}</div>
    43 |             </div>
    44 |         }

ERROR in src/components/TasksTotal.tsx:41:47

TS7006: Parameter 'i' implicitly has an 'any' type.
    39 |             }}>
    40 |                 <div>Total tasks: {tasksState.length}</div>
  > 41 |                 <div>Done: {tasksState.filter(i => i.done.value).length}</div>
       |                                               ^
    42 |                 <div>Remaining: {tasksState.filter(i => !i.done.value).length}</div>
    43 |             </div>
    44 |         }

ERROR in src/components/TasksTotal.tsx:42:45

TS2339: Property 'filter' does not exist on type 'State<any>'.
  Property 'filter' does not exist on type 'StateMethods<any>'.
    40 |                 <div>Total tasks: {tasksState.length}</div>
    41 |                 <div>Done: {tasksState.filter(i => i.done.value).length}</div>
  > 42 |                 <div>Remaining: {tasksState.filter(i => !i.done.value).length}</div>
       |                                             ^^^^^^
    43 |             </div>
    44 |         }
    45 |     </div>

ERROR in src/components/TasksTotal.tsx:42:52

TS7006: Parameter 'i' implicitly has an 'any' type.
    40 |                 <div>Total tasks: {tasksState.length}</div>
    41 |                 <div>Done: {tasksState.filter(i => i.done.value).length}</div>
  > 42 |                 <div>Remaining: {tasksState.filter(i => !i.done.value).length}</div>
       |                                                    ^
    43 |             </div>
    44 |         }
    45 |     </div>

ERROR in src/components/TasksViewer.tsx:3:31

TS2305: Module '"@hookstate/core"' has no exported member 'suspend'.
    1 | import React from 'react';
    2 | import { useTasksState, Task } from './TasksState';
  > 3 | import { State, useHookstate, suspend, none } from '@hookstate/core';
      |                               ^^^^^^^
    4 | import { useSettingsState } from './SettingsState';
    5 |
    6 | function TaskEditor(props: { task: State<Task> }) {

ERROR in src/components/TasksViewer.tsx:171:20

TS2339: Property 'map' does not exist on type 'State<any>'.
  Property 'map' does not exist on type 'StateMethods<any>'.
    169 |     
    170 |     return suspend(tasksState) || <div key="" style={{ textAlign: 'left', marginBottom: 50 }}>{
  > 171 |         tasksState.map((task, i) => <TaskEditorMomorized
        |                    ^^^
    172 |             key={task.id.value}
    173 |             task={task}
    174 |         />)

ERROR in src/components/TasksViewer.tsx:171:25

TS7006: Parameter 'task' implicitly has an 'any' type.
    169 |     
    170 |     return suspend(tasksState) || <div key="" style={{ textAlign: 'left', marginBottom: 50 }}>{
  > 171 |         tasksState.map((task, i) => <TaskEditorMomorized
        |                         ^^^^
    172 |             key={task.id.value}
    173 |             task={task}
    174 |         />)

ERROR in src/components/TasksViewer.tsx:171:31

TS7006: Parameter 'i' implicitly has an 'any' type.
    169 |     
    170 |     return suspend(tasksState) || <div key="" style={{ textAlign: 'left', marginBottom: 50 }}>{
  > 171 |         tasksState.map((task, i) => <TaskEditorMomorized
        |                               ^
    172 |             key={task.id.value}
    173 |             task={task}
    174 |         />)

ERROR in src/components/TasksViewer.tsx:183:39

TS2339: Property 'findIndex' does not exist on type 'State<any>'.
  Property 'findIndex' does not exist on type 'StateMethods<any>'.
    181 |                     let new_id = 1;
    182 |                     // eslint-disable-next-line no-loop-func
  > 183 |                     while (tasksState.findIndex(i => i.id.get() === new_id.toString()) !== -1) {
        |                                       ^^^^^^^^^
    184 |                         new_id += 1;
    185 |                     }
    186 |                     tasksState[tasksState.length].set({

ERROR in src/components/TasksViewer.tsx:183:49

TS7006: Parameter 'i' implicitly has an 'any' type.
    181 |                     let new_id = 1;
    182 |                     // eslint-disable-next-line no-loop-func
  > 183 |                     while (tasksState.findIndex(i => i.id.get() === new_id.toString()) !== -1) {
        |                                                 ^
    184 |                         new_id += 1;
    185 |                     }
    186 |                     tasksState[tasksState.length].set({

ERROR in src/components/TasksViewer.tsx:186:21

TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'State<any>'.
    184 |                         new_id += 1;
    185 |                     }
  > 186 |                     tasksState[tasksState.length].set({
        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    187 |                         id: new_id.toString(),
    188 |                         name: 'Untitled Task #' + (tasksState.length + 1),
    189 |                         done: false

ERROR in src/components/TasksViewer.tsx:186:43

TS2339: Property 'length' does not exist on type 'State<any>'.
  Property 'length' does not exist on type 'StateMethods<any>'.
    184 |                         new_id += 1;
    185 |                     }
  > 186 |                     tasksState[tasksState.length].set({
        |                                           ^^^^^^
    187 |                         id: new_id.toString(),
    188 |                         name: 'Untitled Task #' + (tasksState.length + 1),
    189 |                         done: false

ERROR in src/components/TasksViewer.tsx:188:63

TS2339: Property 'length' does not exist on type 'State<any>'.
  Property 'length' does not exist on type 'StateMethods<any>'.
    186 |                     tasksState[tasksState.length].set({
    187 |                         id: new_id.toString(),
  > 188 |                         name: 'Untitled Task #' + (tasksState.length + 1),
        |                                                               ^^^^^^
    189 |                         done: false
    190 |                     })
    191 |                 }}

ERROR in src/index.tsx:8:10

TS2305: Module '"@hookstate/core"' has no exported member 'configure'.
     6 |
     7 | // optional, defaults are almost always right
  >  8 | import { configure } from '@hookstate/core';
       |          ^^^^^^^^^
     9 | configure({
    10 |     interceptDependencyListsMode: "always",
    11 |     isDevelopmentMode: process.env.NODE_ENV === 'development'

**Comment by avkonst** [comment]
We use pnpm. Run `pnpm install` from the root of a repository, then run `pnpm nx start todolist`. The docs needs to be updated. Please leave the ticket open as a reminder to update the README file. Thanks for reportring.

**Comment by Ofer-Gal** [comment]
Ran` pnpm install`
got
 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @hookstate/core@* inside the workspace

**Comment by avkonst** [comment]
what is your pnpm version?

**Comment by Ofer-Gal** [comment]
The latest version

**Comment by avkonst** [comment]
Hi,

I use the pnpm 6.32.2 version. But will upgrade and fix the issues, if any.

**Comment by avkonst** [comment]
upgraded pnpm and fixed build issues
