### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by onattech** [avkonst/hookstate#352]
hi,
https://hookstate.js.org/docs/writing-plugin/ is broken.

![image](https://user-images.githubusercontent.com/53895969/195026563-0a9f8c66-111f-4a27-aba0-460d4dbd323a.png)

**Comment by avkonst** [comment]
Seems like search index is out of date. The right page now is here: https://hookstate.js.org/docs/writing-extension

**Comment by avkonst** [comment]
another one is in the extensions table: https://hookstate.js.org/docs/extensions-overview/devtools

**Comment by avkonst** [comment]
fixed now after algolia reindexing
