### ISSUE TITLE
Question: Lib Capitalization

### ISSUE THREAD

**Issue by incompletude** [avkonst/hookstate#353]
I find the lib and its minimalistic design promising, but the capitalization choices are kinda weird. 

Why is it `useHookstate` instead of `useHookState`, or  `localstored` instead of `localStored`, is there a reason for it?

**Comment by avkonst** [comment]
Hi, the Hookstate is the name of the library, as any other name it starts with Capital letter followed by lowercase letters. `localstored` is the name of npm package and it follows commonly recognized package naming convention where all letters are lowercase. Hope it answers your questions.
