### ISSUE TITLE
What's the current state of value limitations?

### ISSUE THREAD

**Issue by alexkuc** [avkonst/hookstate#354]
According to [docs](https://hookstate.js.org/docs/nested-state#limitations-for-state-values), only JS primitives are supported. 

However, according to [this](https://github.com/avkonst/hookstate/issues/106#issuecomment-1156487263), there is now automatic downgrading in place to support non-primitive values?

To be honest, I am a bit confused. Should we use non-primitive values? Or should we not? Or should we manually converted them to primitives?

I just tried a simple example with [luxon](https://github.com/moment/luxon) but it seemed to work? Did I miss or misunderstand something?

Sample code - https://codesandbox.io/s/jolly-jerry-8r7j2y?file=/src/App.tsx

**Comment by avkonst** [comment]
Hi,

Yes, Hookstate 4 supports complex objects. Anything what is more than an Object, will work including Date, Regex, Functions and instances of custom classes. The docs need to be updated. I am very overloaded now at work but I hope to find time soon to update the docs to match the coming stable Hookstate 4 release.

**Comment by alexkuc** [comment]
No worries, I completely understand your situation. Just wanted to double check. Closing issue as resolved.
