### ISSUE TITLE
Persistence failing on set method

### ISSUE THREAD

**Issue by ChaseMorgan2001** [avkonst/hookstate#355]
This call has been working across my whole project, but in one specific instance it throw this error. We are not sure if it has to do with persistence or if it actually occurs elsewhere. I can provide example data if needed.
```
s.submittals.set((p: any) => ({ ...p, sizeData: data }))
...
TypeError: Cannot read properties of undefined (reading 'toJSON')
    at index.ts:848:1
    at Array.forEach (<anonymous>)
    at Store.get (index.ts:847:1)
    at StateMethodsImpl.getUntracked (index.ts:1135:1)
    at StateMethodsImpl.get (index.ts:1171:1)
    at Object.get (index.ts:1421:1)
    at JSON.stringify (<anonymous>)
    at Object.onSet (Persistence.ts:20:1)
    at index.ts:1037:1
    at index.ts:978:1

**Comment by avkonst** [comment]
It seems like a State object has leaked into the state somehow, ie. some
nested fields in the value of your state are also State objects. What will
happen if you call: JSON.stringify(data) and
JSON.stringify(s.submittals.get())

**Comment by ChaseMorgan2001** [comment]
Ok so I ran both of these tests, and put the statements just before it calls s.submittals.set().

When I run JSON.stringify(data), it prints out the data object returned from my query, and it all looks correct to me.
Running JSON.stringify(s.submittals.get()) prints the whole state object, which also looks correct to me. 
From my tests, everything seems to work and all data is correct until it hits the s.submittals.set() statement and that is when it throws the error and won't hit any logs after this statement. Also, the structure of the data is exactly the same as in the instance where it works.

Example results returned by stringify(data):
Working: {"size":"value","weight":null,"motor":null,"rpm":null,"max_sound":null,"height":null,"width":null,"depth":null,"cage_depth":null,"cage_diameter":null,"fan_diameter":null,"airflow":null,"fuels":[{"id":5,"fuel":"Fuel Type 1","inlet_pressure_min":"value","inlet_pressure_max":"value"},{"id":6,"fuel":"Fuel Type 2","inlet_pressure_min":"value","inlet_pressure_max":"value"}],"voltages":[],"drop_tubes":[],"mounts":[],"radiant_heater":{"id":3,"input":intValue,"tube_length":intValue,"gas_connection":"value","min_tube_length":intValue,"min_utube_length":"value","electrical_rating":"value","combustion_air_inlet":intValue,"exhaust_flue":intValue},"unit_heater":{}}
Not Working: 
{"size":"value","weight":null,"motor":null,"rpm":null,"max_sound":null,"height":null,"width":null,"depth":null,"cage_depth":null,"cage_diameter":null,"fan_diameter":null,"airflow":null,"fuels":[{"id":7,"fuel":"Fuel Type 2","inlet_pressure_min":"value","inlet_pressure_max":"value"}],"voltages":[],"drop_tubes":[],"mounts":[],"radiant_heater":{"id":4,"input":intValue,"tube_length":intValue,"gas_connection":"value","min_tube_length":intValue,"min_utube_length":"value","electrical_rating":"value","combustion_air_inlet":intValue,"exhaust_flue":intValue},"unit_heater":{}}

Example returned by stringify(s.submittals.get()):
{"valid":false,"validated":false,"fan":{"id":1,"name":"name","category":"category","template":"template"},"productData":{"id":1,"name":"name","category":"category","template":"template","coverage_area":null,"water_capacity":null,"water_pressure":null,"addons":[{"id":47,"addon":"addon1"},{"id":50,"addon":"addon2"},{"id":51,"addon":"addon3"}],"warranty":[{"id":72,"type":"type ","period":"period"}],"links":[{"id":35,"label":"label","url":"url"}],"technicalNotes":[{"id":1,"note":"note1"},{"id":2,"note":"note2"},{"id":3,"note":"note3"},{"id":4,"note":"note4"},{"id":5,"note":"note5"}],"modules":[],"controllers":[],"features":[{"id":145,"feature":"feature1"},{"id":146,"feature":"feature2"},{"id":147,"feature":"feature3"},{"id":148,"feature":"feature4"},{"id":149,"feature":"feature5"},{"id":150,"feature":"feature6"},{"id":151,"feature":"feature7"},{"id":152,"feature":feature8"}],"appearances":[],"sizes":[{"id":1,"size":"size1"},{"id":2,"size":"size2"},{"id":3,"size":"size3"},{"id":4,"size":"size4"}]},"sizeData":{"size":"size3","weight":null,"motor":null,"rpm":null,"max_sound":null,"height":null,"width":null,"depth":null,"cage_depth":null,"cage_diameter":null,"fan_diameter":null,"airflow":null,"fuels":[{"id":5,"fuel":"fuel type 1","inlet_pressure_min":"value","inlet_pressure_max":"value"},{"id":6,"fuel":"fuel type 2","inlet_pressure_min":"value","inlet_pressure_max":"value"}],"voltages":[],"drop_tubes":[],"mounts":[],"radiant_heater":{"id":3,"input":intValue,"tube_length":intValue,"gas_connection":"value","min_tube_length":intValue,"min_utube_length":"value","electrical_rating":"value","combustion_air_inlet":intValue,"exhaust_flue":intValue},"unit_heater":{}},"mountData":{"id":-1,"mount_id":-1,"mount":""},"dropTubeData":{"id":-1,"tube_id":-1,"tube":""},"voltageData":{"id":-1,"voltage_id":-1,"voltage":""},"fuelData":{"id":6,"fuel":"fuel type 2","inlet_pressure_min":"value","inlet_pressure_max":"value"},"projectDetails":{"value":{"project":"","location":"","date":"11/10/2022","submitter":"","architect":"","engineer":"","contractor":"","tags":""}},"productDetails":{"value":{"quantity":"","size":null,"sizeId":4,"voltage":null,"model":"size4","controlQty":"","fuelType":"fuel type 2","tubeLength":null}},"colorDetails":{"value":{"hardwareFinish":null,"finish":null,"material":null}},"mountingHardware":{"value":{"extensionTube":null,"mount":null}},"controllerFeatures":{"value":{"controller":null,"singleMulti":"Single"}},"numAppOpts":1,"appearanceOpts":{"0":{"part":"None","color":null}},"numAdditions":1,"additions":{"0":{"addition":"None"}},"notes":"","numCols":4}

**Comment by avkonst** [comment]
I looked at this issue. The exception happens when you have a state object referring to a nested value which parent has been deleted. This method walks the state value starting from root by path (which is taken from the State object). Somewhere, you application deletes a nested state but has States still referring to it, which are used after.

![image](https://user-images.githubusercontent.com/3971413/208268307-a6b623e5-e460-4186-af94-1c1f54604911.png)

**Comment by avkonst** [comment]
Not an issue with Hookstate.
