### ISSUE TITLE
Untracked Documentation?

### ISSUE THREAD

**Issue by Mervsz** [avkonst/hookstate#356]
Hello, does anyone know how to use Untracked plugin. any documentation for it? there is no sample usage on your hookstate website [Link](https://hookstate.js.org/docs/performance-managed-rendering/)

**Comment by avkonst** [comment]
Hi, Documentation is pending updates for Hookstate 4. Untracked plugin will be deprecated. Hookstate 4 has `state.get({stealth: true})` method with will do the same.

**Comment by Mervsz** [comment]
But how does it work on v3? any sample usage of it? just needed for my application to update the state but not rerender it and in a while i want to force rerender it.

**Comment by avkonst** [comment]
Untracked(state).get()
