### ISSUE TITLE
Bug in merge

### ISSUE THREAD

**Issue by olliechick** [avkonst/hookstate#359]
When sorting the keys for doing a merge, they are sorted lexicographically (alphabetically), which means when this array is reversed to remove the items one-by-one, it could come across items that do not exist, e.g., in the screenshot, it deletes items 9, 8, 7, etc., up to 2, then tries to delete 19 but can't.

![image](https://user-images.githubusercontent.com/6047072/202950868-f8840309-d4db-47b6-a473-c6886c4d4990.png)

**Comment by avkonst** [comment]
coming in the final hookstate-4
