### ISSUE TITLE
Cannot convert null value to object

### ISSUE THREAD

**Issue by FranDepascuali** [avkonst/hookstate#360]
Hi!
I'm a heavy user of this lib, so thank you very much :)

I've got one question, I'm receiving a crash inside hookstate. 
I have a state that looks like this
```ts
interface StatsScreenState {
  ...
  searchStats: CollectionStats[] | null
  suggestionStats: CollectionStats[] | null
  ...
}
```

I set it this way
```ts
this.screenStatus$.searchStats.set(
      searchResults?.interestingResults || null,
    )
this.screenStatus$.suggestionStats.set(
      searchResults?.suggestedResults || null,
    )
```

Then I unwrap it this way on the component
```ts
  const {
    ...,
    searchStats,
    suggestionStats,
    ...
  } = useHookstate(viewModel.screenStatus$)
```

Like this it crashes.

If I change it to use noProxy, then it doesn't crash
```ts
  const {
    ...,
    searchStats,
    suggestionStats,
    ...
  } = useHookstate(viewModel.screenStatus$).get({ noproxy: true })
```

Seems to be related to nullable state

<img width="419" alt="image" src="https://user-images.githubusercontent.com/12101394/203116624-5334d453-f7af-44d7-a9e7-74e1144fd551.png">

Note: It may be similar to this issue
https://github.com/avkonst/hookstate/issues/238

**Comment by avkonst** [comment]
Does it crash if you replace variables assignment via destruction by assignment to a variable and individual properties access of it after?

**Comment by avkonst** [comment]
Hi, I have attempted to write a reproducer and the tests passes fine with object destructure. It seem like you state value is null and you are attempting to get children nested states, which is invalid operation when the parent state value is null. Please reopen if you can provide more information.
