### ISSUE TITLE
Destructure State object to proxy-free plain JavaScript object

### ISSUE THREAD

**Issue by korri123** [avkonst/hookstate#363]
Hey, thanks for this awesome library, makes working with state so much more intuitive. However I got one question.

Sometimes you need to create a pure copy of object

```typescript
interface Object {
  nestedObject: AnotherObject
}
function Component(props: {state: State<Object>}) {
  const plainObject = {...props.state.get()}
  console.log(plainObject)
  // {nestedObject: Proxy}
}
```
This can cause issues when assigning the "pure" object to a state
```js
state.set(plainObject)
// Error: HOOKSTATE-202
```

Hacky solution that that works:
```typescript
function destructureHookstate<T>(state: State<T>): T {
  return JSON.parse(JSON.stringify(state.get())) as T
}

state.set(destructureHookstate(otherState))
```

My question is, is there a better way to convert a state to a fully pure object?

**Comment by avkonst** [comment]
Better one is `state.get({ noproxy: true })`. However the error should not happen either. I will have a look into this, looks like a bug.

**Comment by korri123** [comment]
Thanks for looking into it. It seems not as simple as I initially described but here's a reproducible example:

```tsx
import React, {useEffect} from "react";
import {State, useHookstate} from "@hookstate/core";

interface ClinicMapCoordinates {
  x: number,
  y: number
}

interface Clinic {
  mapCoordinates: ClinicMapCoordinates | undefined
}

interface Institution {
  clinics: Clinic[],
}

export function AdminPage() {
  const institution = useHookstate<Institution>(
    {
      clinics: [
        {
          mapCoordinates: undefined,
        },
      ]
    });

  return <div>
    <InstitutionRow institution={institution}/>
  </div>;
}

function InstitutionRow(props: { institution: State<Institution> }) {
  const state = useHookstate(props.institution)
  return <UpdateInstitutionModal institution={{...state.get()}}/>
}

function UpdateInstitutionModal(props: {
  institution: Institution,
}) {
  const institution = useHookstate(props.institution)
  return <>{
    institution.clinics.map((clinic) =>
      <ClinicInputForm clinic={clinic}/>
    )
  }</>
}

function ClinicInputForm(props: {
  clinic: State<Clinic>,
}) {
  const clinic = useHookstate(props.clinic)
  useEffect(() => {
    clinic.mapCoordinates.set({x: 10, y: 10})
  }, [])
  return <></>
}
```
Should fail with HOOKSTATE-202

**Comment by avkonst** [comment]
ok. the error happens because you copy state value from one state into another state, which is prohibited. Using noproxy option to get the object will lead to other errors down the track because you well end up with a single object instance participating in 2 states. The solution is to do a clone of an object when you want to copy it as a value to another state. You can add `clone()` method to a state object using Clonable extensions of hookstate.

**Comment by korri123** [comment]
Thanks for looking into it, the nested instance being shared between states was what I thought as well. Sorry if I lead you down a wild goose chase for something else due to my poorly explained original post. I'll look into the clonable extension, which will probably achieve the same thing as the stringify/parse method but more efficient.
