### ISSUE TITLE
Array management hits call stack limit

### ISSUE THREAD

**Issue by gatomo-oficial** [avkonst/hookstate#373]
I want to get an array as an array, not as an `ImmutableObject` and the unique thing that I thought was map the "array" to get an array, but when I use any function that I can use with arrays it hits the call stack limit:
`RangeError: Maximum call stack size exceeded.`

This is my code:
```ts
// state.ts

const defaultData: RPC = {
	name: '',
	app_id: '',
        // ...
	buttons: [
		{ label: '', url: '' },
		{ label: '', url: '' }
	]
};

const state = {
	// ...
	formData: hookstate<RPC>(defaultData),
};

export default state;
```
```tsx
// Main.tsx

const data = useHookstate(state.formData);
// ...
<div onClick={() => console.log(data.get().buttons.map((e) => e.label))}> Button </div>
```

I'm doing something wrong or is a bug? Thanks

**Comment by richcrad** [comment]
I suspect it would work better to move the `get()` call to the `label` field:
```
<div onClick={() => console.log(data.buttons.map(e => e.label.get()))}> Button </div>
```

If you truly want to operate on the array without having it be State, you can do this:
```
const nonStateData = JSON.parse(JSON.stringify(state));
```
...and then do anything with `nonStateData`.
