### ISSUE TITLE
Array.splice() does not work as the docs suggest, at least according to TypeScript

### ISSUE THREAD

**Issue by richcrad** [avkonst/hookstate#376]
Hello! I'm loving hookstate. Thanks for the great work.

I found an issue with the TypeScript definitions (or maybe with the Docs for hookstate).

My state includes an array of objects (e.g., MyType). I tried inserting into the array using the technique from the [docs](https://hookstate.js.org/docs/nested-state#splicing-elements):
```
state.set(p => {
    p.splice(0, 0, newElement);
    return p;
})
```
This code DOES seem to work, however TypeScript gives this error:
```
Property 'splice' does not exist on type 'ImmutableArray<MyType>'. Did you mean 'slice'
```

Since `p` has the type `ImmutableArray<MyType>`, it seems to me that `splice` should NOT work, since `splice` modifies the array.

I don't know if I should be using this technique. Should the Docs be updated? Should the TypeScript definitions be updated? Please advise. Thanks!

**Comment by avkonst** [comment]
Can not reproduce. Wrote a test as well.
