### ISSUE TITLE
Migration from 3 to 4

### ISSUE THREAD

**Issue by solidsnail** [avkonst/hookstate#386]
Hello, first of all I wanna say congrats on the awesome store library.

While wanting to upgrade from 3 to 4, I stumbled upon a blocker which prevented me from doing so:
The type *ImmutableObject* that warps every value does not play well with typescript, accessing a nested value such as store.a.b.c
will infer this typing: `ImmutableObject<ImmutableObject<ImmutableObject<type of c here>>>>`
Is there a way to keep the raw typing value when accessing a property with either .get() or .value ?

Thanks in advance

**Comment by kuldip-simform** [comment]
@solidsnail  How did you achieve this? Can you please guide me?

**Comment by avkonst** [comment]
I am curious to know what is the problem with ImmutableObject ? You still
can access properties, it is just these are deep recursively read only.

**Comment by kuldip-simform** [comment]
It is TS that is causing Type errors, nothing major.

**Comment by avkonst** [comment]
I understand it is TS. It is why it exists. Could you share the details of your use case please? The state value is immutable for a reason (it can not be changed just by setting it, that is why TS checks it.
