### ISSUE TITLE
Localstored - optional initializer

### ISSUE THREAD

**Issue by piotrnowoslawski** [avkonst/hookstate#388]
There is no recent publication with a fix for optional initializer

https://github.com/avkonst/hookstate/pull/387

<img width="847" alt="Zrzut ekranu 2023-04-26 o 11 25 53" src="https://user-images.githubusercontent.com/37037656/234535561-7f1ca107-cf4f-43ab-abf3-e359bcd08acd.png">

**Comment by avkonst** [comment]
published now as 4.0.2
