### ISSUE TITLE
Nextjs: localstorage is not defined

### ISSUE THREAD

**Issue by nelwincatalogo** [avkonst/hookstate#401]
**Versions:**
"@hookstate/core": "^4.0.1",
"@hookstate/localstored": "^4.0.2",
"next": "13.5.3",

**Error:**
```
referenceerror: localstorage is not defined
```

**When the error occured?:** after running this command
```
yarn build
```

**Code:**
```
'use client';

import { extend, hookstate, useHookstate } from '@hookstate/core';
import { localstored } from '@hookstate/localstored';
import { devtools } from '@hookstate/devtools';

export const globalStatePersist = hookstate(
  {
    hello: false,
  },
  extend(localstored({ key: 'globalStatePersist' }), devtools({ key: 'globalStatePersist' }))
);

export const useGlobalStatePersist = () => useHookstate(globalStatePersist);
```

**Comment by avkonst** [comment]
@nelwincatalogo hi, I appreciate if you localize the problem a bit. I am very limited with time availability to debug it and understand the cause of it. It sound like nextjs tries to build server side and can not find a reference to a variable which is available only in a browser environment.

**Comment by nelwincatalogo** [comment]
![image](https://github.com/avkonst/hookstate/assets/45314780/24d0ab0e-6f9b-480e-86c0-f983e123d63e)

i guess the problem is in this line.. it should check if it is currently in a browser environment

**Comment by avkonst** [comment]
nice, could you please submit a PR? I think there is a similar check in other places already

**Comment by nelwincatalogo** [comment]
![image](https://github.com/avkonst/hookstate/assets/45314780/0cfd3aa8-56a7-4509-b01c-bf6e883b7d34)

Confirmed.. i copy the code and test it on my end and that's the culprit.. i'll submit a PR, after this one works

**Comment by nelwincatalogo** [comment]
Submitted a PR, ref #402
