### ISSUE TITLE
106 EXCEPTION 'Cannot Convert Undefined Value to Object' Error when setting and getting global store state in two seperate components

### ISSUE THREAD

**Issue by waleedshkt** [avkonst/hookstate#408]
I am simply setting a global state `aa` in one component with object containing nested arrays of objects. 
```
const store = createState({ a: { aa: [] }, b: [] });

Component 1 ---> store.a.aa.merge([{ q: 1, r: [{s: 2, f: 4}] }]);

Component 2 ---> store.a.aa[0].get(); // { q: 1, r: [{s: 2, f: 4}] } logs on first render but then throws above error
         
```

I then try to get the same state `aa` in another component, and pass it down as prop for getting added in onClick method. In the same component, I also add log `aa` which on first render of the component populates the updated state value correctly. 
But as soon as I click the button, the above stated error comes up with source showing as follows:

```
531   path.ForEach(function (p) {
532      result = result[p];
533   });

...node_modules/@hookstate/core/dist/index,js (532:28)
```

I do not understand the reason behind this behavior and how to avoid it?

To add: both components are lazy loaded using react `Suspense` and `lazy`,
Is this error then because of the this lazy loading?

**Comment by avkonst** [comment]
Hi, thanks for the report. And what happens to the the state on click? It kind of hard to get the reproducer from the description, although it is quite detailed. I appreciate if you could put a sample app reproducer. That will help to locate and fix the problem much faster.

**Comment by waleedshkt** [comment]
Thank you @avkonst for the response. 

It looks like I found a bug within my code. A silly mistake of setting and getting a state in callback!
So it was updating the store with local state and then resetting the local state in a setTimeout, and it re-evoked the callback and set the global store state (linked to local one somehow) `aa` to `undefined`. 

Never thought this will cause the issue. It just so happened to slip through the sight

All is good now. Thanks again
