### ISSUE TITLE
store consuming initial data from REST Apis dynamically and in Nested form 

### ISSUE THREAD

**Issue by sashikn** [avkonst/hookstate#41]
Does it support the 
`store consuming initial data from REST Apis dynamically and in Nested form `

**Comment by avkonst** [comment]
Hi, I am not sure what you mean by `Nested form`, but it does support loading the state from remote resources (asynchronously loaded states in general).

Here are few examples of the state hook with asynchronously loaded states:
- https://hookstate.js.org/local-async-state
- https://hookstate.js.org/demo-todolist/

Please, let me know if it answers your question. Docs for the StateLink.promised and StateLink.error API are not yet published, but available here in typedoc format: https://github.com/avkonst/hookstate/blob/master/src/UseStateLink.tsx#L164 and https://github.com/avkonst/hookstate/blob/master/src/UseStateLink.tsx#L171

**Comment by avkonst** [comment]
I am closing it. Reopen it, if my answer does not address your question.
