### ISSUE TITLE
`interceptReactHooks` fails to override already imported `useEffect` when running in module environment

### ISSUE THREAD

**Issue by HexaField** [avkonst/hookstate#412]
```ts
import { useEffect } from 'react'
import { hookstate } from '@hookstate/core'

console.log(useEffect) // this will be the old useEffect implementation
```

Switching over from mocha to vitest and CJS to ESM caused my tests to fail, but if I swap the order of the above imports, the tests pass fine. Generally it is a bad idea to override other dependencies, and in the case of ESM environments, it seems like the imports are reconciled different and can more easily fail.

**Comment by avkonst** [comment]
yes, it is... but there was no other way to deliver ergonomics with the rigid API of react... I think you can useHookstateEffect instead and it should not be dependent on the order of imports
