### ISSUE TITLE
Validation Plugin and "value" property problem

### ISSUE THREAD

**Issue by skeadr** [avkonst/hookstate#414]
Hello there. 

I'm currently facing an issue where I'm not sure if I should change my approach, my data structure, I missed someting, or if it's a bug.

One of my data structures contains keys with the name "value". That's working fine, as long as I don't try to validate it.

Here is an example code snippet.

```
import { useHookstate } from "@hookstate/core"
import { validation } from "@hookstate/validation"

export function Test() {
    const state = useHookstate({ value: "some value" }, validation())

    state.nested("value").validate((e) => e.length > 0, "May not be empty")

    return (
        <>
            <input value={state.nested("value").get()} onChange={(e) => state.nested("value").set(e.target.value)} />
            <button onClick={() => console.log(state.valid(), state.get())}>log validation</button>
        </>
    )
}
```
Or the `plugins/validation/src/unit.test.ts` change in your repo
```
let result = useHookstate({ a: [0, 1], b: [1, 1], value: 2 }, validation())
result.nested("value").validate(r => r === 2, "value should be 2")
```

Is this a conflict with the state.value? I didn't find any mention of this in the docs.

Kind regards, and a big thank you for this amazing lib!

**Comment by skeadr** [comment]
After a bit more digging in the source code I now see that my assumption about the state.value conflict is correct. Same goes for path, keys, ornull, promised, promise, error, get, set, merge, nested keys (taken from the switch statement in the nestedGetter function). 

Could that be fixed/changed somehow? Core seems to work with just using `state.nested(value)` instead of `state.value`. Not sure how the other plugins handle this situation.

If not, could it be added to the https://hookstate.js.org/docs/exceptions? That would make it more clear.

**Comment by avkonst** [comment]
Thanks for reporting. Yes, looks like it is a bug in the validation plugin implementation. I would not have time to debug it, but it looks like you done it almost all debugging. Could you please submit PR with a fix too?

**Comment by skeadr** [comment]
https://github.com/avkonst/hookstate/pull/415

It's basically a one liner. Not sure about side effects though. I added a test case and tests are okay at least.

**Comment by avkonst** [comment]
Thanks for PR. Merged

**Comment by skeadr** [comment]
What's the release cycle like? When would that change be available as a new version on npmjs.com?

**Comment by avkonst** [comment]
released now
