### ISSUE TITLE
Is there any api for set state callback function?

### ISSUE THREAD

**Issue by weekien** [avkonst/hookstate#43]
i have problem to call setting state A then set state B in sequence(B logic depends on state A) . As my understanding the state is change is aysnc . is there any api to have callback after setting state A as the react have?

**Comment by avkonst** [comment]
There is an API. Wil post the reference later. But what do you mean state
change is async? It should not be... Statelink.set applies the change
immediately...

**Comment by weekien** [comment]
I mean the state change is async.
https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous






Email id: chwk87@ <murugan.s@emson.com.sg>gmail.com

**Comment by avkonst** [comment]
This applies to the class based states, here is the actual state for the React.useState and Hookstate.useStateLink:

> Do Not Modify State Directly

Yes, do not do it. Hookstate will throw an exception if you do it. React.useState will silently update it but will not rerender.

> State Updates May Be Asynchronous

I do not think it is true for the hook. At least it is not true for Hookstate. Hookstate mutates the state synchronously. However, the rerender might be asynchronous and can be duplicate, etc, but the state value change is synchronous.

> State Updates are Merged

Not with the React.useState. Hookstate provides nested state updates mechanisms and StateLink.merge function.

> The Data Flows Down

Yes, it should be. Hookstate updates the parent components first. If a child component with a **scoped** state is affected too, it is not explicitly rerendered as it is invoked by the parent anyway.

**Comment by avkonst** [comment]
Anyway, here is how to subscribe to state updates. (I use createStateLink, but the same mechanism applies to the StateLink returned by the useStateLink function)

```tsx
const state = createStateLink(initialStateValue);

const MyStateWatchPluginId = Symbol('my-state-watch-plugin'); // should be global variable
state.with(() => ({
    id: MyStateWatchPluginId,
    create: () => ({
        onSet: (data) => {
              console.log('new state set', data.state);
              console.log('updated at', data.path);
              console.log('to a new value', data.value);
        }
    })
}))
```

Is it helpful?

**Comment by avkonst** [comment]
Here is how to have an identical clone B of a state A:
```tsx
const stateA = createStateLink(initialStateValue);
const stateB = createStateLink(stateA.value);

const MyStateClonePluginId = Symbol('my-state-clone-plugin'); // should be global variable
stateA.with(() => ({
    id: MyStateClonePluginId,
    create: () => {
        return ({
             onSet: (data) => {
                 stateB.set(data.state);
                 // Note 1: if you would like to have more fine grained updates you can locate the target property in stateB using data.path and set it to data.value
                 // Note 2: if you are dealing with property deletes or promised state, you will need to check if data.value and data.state property exist, for example:
                 // if (!('value' in data)) { console.log('property has been deleted at path', data.path) }
                 // if (!('state' in data)) { console.log('the state has been set to a promise') }
             }
        });
    }
}))
```

**Comment by avkonst** [comment]
Add to the new documentation.

**Comment by avkonst** [comment]
Moved to https://hookstate.js.org/docs/writing-plugin
