### ISSUE TITLE
Missing plugin dependencies

### ISSUE THREAD

**Issue by MainAero** [avkonst/hookstate#48]
Using the `Initial` plugin requires `lodash.clonedeep` and `lodash.isequal` which are are not included in the artifact neither set as  peer dependency. Results in build error.

**Comment by avkonst** [comment]
Hmm, this is strange. The plugin declares peer dependencies in package.json. Have a look: https://github.com/avkonst/hookstate/blob/master/plugins/Initial/package.json#L38

Any ideas why it is breaking for you?

**Comment by Pills2389** [comment]
Hi,
I had the same problem.
Had to install @types/lodash to fix it.

Hope it helps.

**Comment by avkonst** [comment]
If I add '@types/lodash' to peer dependencies for the plugin, will it fix the problem?

**Comment by avkonst** [comment]
Verified in 2.0.0
