### ISSUE TITLE
Devtools: relies on localStorage

### ISSUE THREAD

**Issue by starlabs007** [avkonst/hookstate#50]
I'm using hookstate in a react-native project and would like to be able to use the devtools.
However I get:
```
ReferenceError: localStorage is not defined
```
as `localStorage` doesn't exist in the react-native environment. Any chance to get devtools working with RN?

**Comment by avkonst** [comment]
Yes, it is possible but I need a bit of help from you. Local storate is used to set settings for enabling/disabling some stores being traced in devtools. I usually adjusted these settings using Chrome devtools and reloaded the app. What would be the alternative for RN?

**Comment by avkonst** [comment]
Can you pass some environment variables to the RN app? I could make the devtools reading the settings from either localstorage if available from the env variable?

**Comment by starlabs007** [comment]
It's "somewhat" possible to pass environment variables to the RN app, but not out-of-the-box from a normal RN fresh setup. You'd have to either install and setup a babel plugin or some other third party library.

What about passing in a configuration settings object to devtools from within the RN app?

**Comment by avkonst** [comment]
This is possible. I will have a look later. Busy now.

**Comment by avkonst** [comment]
Fixed on latest. Uses new API targeting version 2 of hookstate. The dev tools and the API v2 are documented here: https://hookstate.js.org/docs/devtools

I have not verified it with RN, because I do not have an environment. Let me know how it goes. If it still does not work, reopen the ticket.
