### ISSUE TITLE
setting value to deeply nested property

### ISSUE THREAD

**Issue by hyusetiawan** [avkonst/hookstate#53]
suppose I have an object with the following structure:
```
const global = createStateLink({
	user: {
		name: 'some user',
		hobbies: ['building', 'stuff'],
		address: {
			city: 'san jose',
		},
	},
})
```

in order for me to push into hobbies, I have:
`const gUser = useStateLink(global)`
and a button with onClick of:
`gUser.nested.user.nested?.hobbies.set((hobbies) => [...hobbies, 'stuff'])`
which is rather hard to read, due to `nested` extra path
is there a better way that is still strongly typed to do something along the lines of:
`gUser.user.hobbies.set(...`

Checking the example of tree state in the docs, it shows how to deal with nested properties but still with one `nested` level at a time

Also, in the guide for .set() it mentions a plugin called Mutate, but it's not listed in the plugin section nor in the docs

I am not sure how the reference is checked to trigger the re-render, but is it possible to just set the whole object? as in:
```
gUser.set((user) => {
   return {
      ...user,
      hobbies: [...user.hobbies, 'added'],
   }
})
```
will hookstate figure out what has changed? because in this case we technically the property name as well.

**Comment by avkonst** [comment]
> is there a better way that is still strongly typed to do something along the lines of:
gUser.user.hobbies.set(...

The very initial prototype version was something along these lines. There were problems with it: 1. Hookstate link properties collided with user's object properties. 2. It was not possible to use this approach for states with primitive values.

There is a possible improvement - technically it is possible to restore StateLink from a value object (would not work for primitive values). It is possible to develop `restoreStateLink` function, which would allow to do something like this:

`restoreStateLink(gUser.value.user.hobbies).set(...)`

But I am not convinced it is valuable improvement. What do you think?

**Comment by avkonst** [comment]
> Also, in the guide for .set() it mentions a plugin called Mutate, but it's not listed in the plugin section nor in the docs.

This plugin will be deprecated when I publish the updated docs for Hookstate. `merge` and `set` functions are so powerful, that Mutate is not needed anymore. You can read new docs in `https://github.com/avkonst/hookstate/tree/master/hookstate.js.org/docs2`. Just run `npm start` in this folder and check nested state section. It explains all clear, I think.

Let me know if newer docs are going in the right direction.

**Comment by avkonst** [comment]
> I am not sure how the reference is checked to trigger the re-render, but is it possible to just set the whole object?

It is possible

> will hookstate figure out what has changed?

No, it will not. It will assume the whole object is changed. There are 2 reasons. 1. this is a trade off for extreme performance. 2. it does not require Hookstate to invent object comparison function. 

Provided that you can set deeply nested properties by walking the state tree and setting individual properties, I believe this is not a disadvantage that Hookstate does not figure it out.

However, it is possible to add `set` method to StateLink which would accept the second argument, which would be a callback function for comparing state values recursively (using visitor pattern or alike). In this case, it would be possible to discover changed parts and re-render efficiently, but the state inspection would be slower. And it would be user's choice what to do. Would it be useful?

**Comment by hyusetiawan** [comment]
Is it possible to simplify the API to be more functional programming like? This is obviously a bigger change but the API would behave like so:
```
// func(subject, value)
set(gUser.address.city, 'san antonio');
set(gUser, {some user object})
merge(gUser, {new user object})
```
we can get the benefits of FP like function currying and I think it will simplify the dev ergonomics, as there is a clear separation between user space and hook state's space. 

Currently, the API feels awkward because it has this mutative nature of using `nested.property1.set()`, injecting functions into the user object but your comment:

> However, it is possible to add `set` method to StateLink which would accept the second argument, which would be a callback function for comparing state values recursively (using visitor pattern or alike). In this case, it would be possible to discover changed parts and re-render efficiently, but the state inspection would be slower. And it would be user's choice what to do. Would it be useful?

This sounds like an immutable approach, I am not sure if it fits with the hookstate's paradigm.

**Comment by avkonst** [comment]
`set(gUser.address.city, 'san antonio');` What would be the type of `gUser.address.city` in this example?

**Comment by avkonst** [comment]
what you want is coming in version 2.
see code samples here: https://hookstate.js.org/docs/nested-state
