### ISSUE TITLE
Add generic history/snapshotting plugin

### ISSUE THREAD

**Issue by Pills2389** [avkonst/hookstate#54]
Hi,

is there a way to get the previous state? Can't use usePrevious to get it, need an alternative.
The Initial plugin only gives the initial value, not the previous one.

Thank you

const usePrevious = (value) => {    
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
}

**Comment by avkonst** [comment]
I have included it to the development scope. It will come later. Unfortunately I am busy with other stuff at the moment. Thanks.

**Comment by Pills2389** [comment]
Thank you. It's a really nice alternative to useState or Redux

**Comment by rolivegab** [comment]
Hi!
I think i finished plugin implementation for solve this problem.
How can i submit it?
@avkonst

**Comment by avkonst** [comment]
I have seen your pull request.

**Comment by avkonst** [comment]
@hookstate/snapshotable extension for Hookstate-4 supports state snapshoting by multiple keys, getting prior snapshots, and rolling back the state to the previous snapshot by it's name. Documentation will get updated soon. For now checkout  https://github.com/avkonst/hookstate/blob/master/plugins/snapshotable/src/unit.test.ts for the example how to use the plugin.
