### ISSUE TITLE
[restored] Question: how to "hydrate" hookstate state on client side with SSR (#52)

### ISSUE THREAD

**Issue by avkonst** [avkonst/hookstate#55]
@joompit I am not sure why, but the issue 52 is gone. I understand nobody can delete the issues. I am trying to restore it now. Here is what I have got captured in my emails:

from: @joompit
I'm sorry if I didn't explain myself correctly. When I wrote "build store" I mean for example the following situation:

A) Server side we call an API (let's say an authentication API) and fill up the authentication store and use it for certain application logic.
B) Server sends the serialized redux data over the network along with the HTML markup.
C) Client side we wouldn't have to call the API to fill up the client side store once again since it was already done server side. It simply deserializes the redux data.

It's certainly not a problem to rebuild the store client side, but it would be more performant to be able to reuse server side in order to avoid calling multiple times the same API.

Maybe the way to go is doing something such as Next.js does with Redux which is serializing and deserializing the object structure (in this case, the hookstate)?

from @joompit
Exactly, that would be what I'm aiming for. There is a "plugin" for Next.js which does something like this for Redux: https://github.com/kirill-konshin/next-redux-wrapper (specific code for the plugin is on https://github.com/kirill-konshin/next-redux-wrapper/blob/master/packages/wrapper/src/index.tsx).

If I understand correctly, I believe that what I need to do is something along the lines of what you do with the Persistence plugin (https://github.com/avkonst/hookstate/blob/master/plugins/Persistence/src/Persistence.ts). On that plugin, you do both serialization/deserialization and rebuild the state from another source (in this case, localStorage).

I would only need to make sure to send these states serialized, and then on client-side make sure to set the state to that specific value.

I believe Hookstate is more versatile and way simpler than Redux, so I'll try to find a way to mimic this same functionality that is available for Redux to Hookstate in order to be able to continue using SSR for my apps and start using Hookstate as well! It might take me a while since I'm not that experienced, but I will try to do it.

**Comment by avkonst** [comment]
Let me know how it goes. If it is done with Redux it can be done with Hookstate.

**Comment by avkonst** [comment]
You can contribute a plugin to this repository under plugins directory, if you would like to.

**Comment by avkonst** [comment]
If you are stuck, ask questions here, I will try to help from the Hookstate point of view. I am not very much familiar with Next, though..

**Comment by avkonst** [comment]
Hi @joompit any progress on this one?

**Comment by xereda** [comment]
Any predictions for SSR support with Next.js?

**Comment by avkonst** [comment]
Hi, could you please post what is not working exactly? There were few fixes applied in the past and I know it worked with nextjs.
