### ISSUE TITLE
useEffect infinite loop

### ISSUE THREAD

**Issue by Pills2389** [avkonst/hookstate#56]
let's say I have 2 StateLinks, both have an array as initial value, if I use objects it was OK.

const stateA = useStateLink({val:[]})
const stateB = useStateLink({val:[]})

if I try to use useEffect and set stateB.nested.val.set(stateA.value.val) when stateA.value.val changes it will cause infinite renders.

**Comment by avkonst** [comment]
Interesting. Could you put more complete code snippet?

**Comment by avkonst** [comment]
Sorry, can not address the issue without the code sample.

**Comment by avkonst** [comment]
If it is still relevant, please provide the code sample and reopen the ticket. Thanks.
