### ISSUE TITLE
Transform and Async

### ISSUE THREAD

**Issue by yudao** [avkonst/hookstate#60]
Hi,

Firstly, great job! It's an awesome project for me, well done!

I want to use `transform` with useStateLink and fetch an API to load initial data from a server.

But I always get an error like this :
`StateLink is used incorrectly. Attempted 'read promised state' at ...`

I've read your answer to #41  and I've tested a lot sort of things. But the only way the promise works if the state link is accessible directly outside of his module like in your [TasksState ToDo example](https://github.com/avkonst/hookstate/blob/master/hookstate.js.org/demos/todolist/src/components/TasksState.ts) not when using transform for interfacing methods (a better way for me for visibility and comprehension across all our team) like in your [SettingsState ToDo example](https://github.com/avkonst/hookstate/blob/master/hookstate.js.org/demos/todolist/src/components/SettingsState.ts)

My goal is to use _**hookstate**_ to create CRUD store for my API endpoints. So call the API once on first load, mutate the store and in background POST, PUT, DELETE items of my stores when needed.

For information, i'm using [Amplify JS Cognito](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js) for authentification and [Amplify JS API](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js) for fetching my endpoints.

So I had to manage like this `useProjectsStore.js`:

```
import { createStateLink, useStateLink } from "@hookstate/core";
import { useAuth } from "../../hooks/useAuth";
import { API } from "aws-amplify";
import { useEffect } from "react";

export const useProjectsStore = () => {
  const {
    state: { user },
  } = useAuth();

  const fetch = async () => {
    const response = await API.get("DEFAULT", "/list/configs", {
      queryStringParameters: {
        group: user.signInUserSession.idToken.payload["cognito:groups"][0],
      },
    });
    state.access().add(response);
  };

  useEffect(() => {
    if (user) fetch();
  }, [user]);

  const state = createStateLink({ isLoading: true, projects: [] }, (s) => ({
    add(projects) {
      projects = Array.isArray(projects) ? projects : [projects];
      s.nested.projects.merge(projects);
    },
    index(idx) {
      return s.nested.projects.get()[idx];
    },
    get list() {
      return s.nested.projects.get();
    },
  }));

  return useStateLink(state);
};
```

and my component `test.js`: 

```import { Flex } from "../../atoms/Flex";
import { Divider } from "../../atoms/Divider";
import { Button } from "../../atoms/Button";

// My Cognito Reducer Hook for authentication
import { useUser } from "../../../contexts/userContext";

import { useProjectsStore } from "../../../hooks/models/useProjectsStore";

export default () => {
  const [user] = useUser();
  const projects = useProjectsStore(user);

  return (
    <Flex as="header" variant="layouts.header">
      <Flex variant="layouts.header.left">
        <Button
          variant="floating"
          icon="plus"
          onClick={() => projects.add("Project Added")}
        />
        <Divider isVertical={true} />
        <DropDown
          items={projects.list}
          item={projects.index(0)}
          anchor="BOTTOM_CENTER"
        />
      </Flex>
    </Flex>
  );
};
```

There, my store is initialised only if my user has changed and I can access to my initial data when empty and the data when fetched from my API.

But I think I'm wrong with this kind of "_arrangement_". I think you maybe help me to find a better and performant way to use your great library.

Thanks a lot!
Cheers,

Yu.

**Comment by yudao** [comment]
Hmmm, I've tested a little more and this call `state.access().add(response);` is well logged but my component doesn't render items again... I'm very confused about how call initial API with public interface (_transform)_...

**Comment by yudao** [comment]
Round 2 :)

I've managed like this now `useProjectsStore.js`:
```
import { createStateLink, useStateLink } from "@hookstate/core";
import { useAuth } from "../../hooks/useAuth";
import { API } from "aws-amplify";

let initialised = false;

const state = createStateLink([], (s) => ({
  add(projects) {
    s.merge(Array.isArray(projects) ? projects : [projects]);
  },
  index(idx) {
    return s.get()[idx];
  },
  get list() {
    return s.get();
  },
}));

export function useProjectsStore() {
  const {
    state: { user },
  } = useAuth();

  const fetch = async () => {
    const response = await API.get("DEFAULT", "/list/configs", {
      queryStringParameters: {
        group: user.signInUserSession.idToken.payload["cognito:groups"][0],
      },
    });
    const res = response.map((r) => r.config_name);
    state.access().add(res);
  };
  if (user && !initialised) {
    initialised = true;
    fetch();
  }

  return useStateLink(state);
}
```

and my component `test.js`:
```
import { Divider } from "../../atoms/Divider";
import { Button } from "../../atoms/Button";

import { useProjectsStore } from "../../../hooks/models/useProjectsStore";

export default () => {
    const projects = useProjectsStore();

  return (
    <Flex as="header" variant="layouts.header">
      <Flex variant="layouts.header.left">
        <Button
          variant="floating"
          icon="plus"
          onClick={() => projects.add("Project Added")}
        />
        <Divider isVertical={true} />
     <DropDown
          items={projects.list}
          item={projects.index(projects.list.length - 1)}
          anchor="BOTTOM_CENTER"
        />
      </Flex>
    </Flex>
  );
};
```
In this example I don't manage errors.

I'm not sure again of this way and specially the performance. I needed to use a local var to store if fetched or not on first time (and if the user exists cause the useUser hooks is async).

If you have tips or recommendations it will be grateful!

Thanks a lot, I know i'm talkative :p

Cheers,
Yu.

**Comment by avkonst** [comment]
Hey. Hookstate version 2 is coming soon. I am working on the documentation for this. I will cover you questions.

**Comment by yudao** [comment]
Top 👍 
I'm looking forward to this day ;)

**Comment by avkonst** [comment]
Please have a look into new website docs. In particular: https://hookstate.js.org/docs/asynchronous-state and https://hookstate.js.org/docs/exporting-state and updated https://hookstate.js.org/demo-todolist/

**Comment by avkonst** [comment]
Reopen if still unclear.

**Comment by yudao** [comment]
Hi @avkonst!

Thank you for all your work.

I can't achieve my goals because i'm a little bit confused about how to access values and when.

I want to have a mix between all your examples (Async + Exporting state with variables) and keep all my "business layer" into the store not in the components (they only access data and send to store for mutating).

This is a little test what I'm trying to do with the **hookstate** version _**2.0**_:
```
import { createState, useState, self } from "@hookstate/core";

import { useAuth } from "../hooks/useAuth";
import { fetchPromise } from "./fetch";

const state = createState(
  fetchPromise({
    user, // <==== 'user' is not defined  no-undef
    path: "/list/security_logs",
  })
)[self].map((s) => () => {
  return {
    get list() {
      return s[self].value;
    },
  };
});

const useSecurityStore = () => {
  const {
    state: { user }, //<=== How to pass user (async hook) to the createState to fetch my data?
  } = useAuth();

  return useState(state);
};

export { useSecurityStore };
```

Thanks for your time!

Cheers,
Yu.
