### ISSUE TITLE
Changes in the Hookstate 2.0

### ISSUE THREAD

**Issue by avkonst** [avkonst/hookstate#68]
Please, be aware about non-backward compatible changes with next major release of Hookstate.

https://hookstate.js.org/docs/migrating-to-v2

Ask any questions in comments for this issue.

**Comment by avkonst** [comment]
FYI @ppwfx , @rolivegab , @praisethemoon

**Comment by starlabs007** [comment]
It looks like `access()` is removed in the new api? If so what would be an avenue to access state data _**outside**_ of a React component?

In my use case I have services/managers that access & manipulate state, so they wouldn't be able to use `<StateFragment>` or any jsx for that matter. From the new docs, perhaps I can encapsulate some of this state work inside a custom interface? (as mentioned in "Exporting State" help).

BTW the new help docs are great. Been reading them to get some insight into the new api.

**Comment by rolivegab** [comment]
Loved the new sintax! I'll try it with a next project and give you feedback.

off topic: I know that maybe this isn't the place to it, but, are you accepting help on development of hookstate? if so, how can i contribute?

**Comment by avkonst** [comment]
@starlabs007 

It looks like access() is removed in the new api? If so what would be an avenue to access state data outside of a React component?

Just use the state instance returned from the `createState` function. Here is the example: https://hookstate.js.org/docs/global-state

**Comment by avkonst** [comment]
@rolivegab yes, you are welcome to contribute. What are you interested in? There is a ticket to create a plugin which would allow to access the previous state and potentially having an extension method to revert the state to the previous value. It can also trace a history of changes up to the configurable amount and allow to revert multiple state changes. Interested?

**Comment by avkonst** [comment]
@rolivegab you can also write some blogs to spread few words about Hookstate. You can put it here: https://hookstate.js.org/blog or anywhere you like

**Comment by avkonst** [comment]
Hookstate 2.0 is out. It was big job. Enjoy.
Any questions, just open a ticket.
