### ISSUE TITLE
`.set` not working according to the new API specifications 

### ISSUE THREAD

**Issue by haveanicedavid** [avkonst/hookstate#69]
Hi there! I'm loving your library, and am excited about the 2.0 release. 

I tried to update my app according to the 2.0 docs (specifically the pattern in your TODO example (SettingState.ts)
```
interface InitialState {
  pages: ByGunId<Page>
  pageTitles: string[]
}
const initialState: InitialState = {
  pages: {},
  pageTitles: [],
}

export const useGunState = createState(initialState)[self].map((s) => () => {
  const state = useState(s)
  return {
    testFunc() {
      state.pages.set('Not working')
    }
  }
```
... but Typescript won't compile. The TS error: 
```
This expression is not callable
 Type 'StateMixin<Page> & { [type details from my app] }' has no call signatures.ts(2349)
```

I'm running `"@hookstate/core": "^1.8.8",`. Also tried upgrading to 2.0, but get the same error.

Removing the `initialState` type changes the error, but it still won't work: 
`Property 'set' does not exist on type 'State<{}>'.`

The new API looks appealing so i'd love to start using ASAP, but am not really sure how to troubleshoot further at this point. Any suggestions? 

EDIT: 
I just realized that changing `state.pages.set` to `stage.pages[self].set` passes the compiler, so i'm closing the issue for now.

**Comment by avkonst** [comment]
Correct. [self] is required for accessing state methods of non primitive methods. It is documented here: https://hookstate.js.org/docs/nested-state

**Comment by avkonst** [comment]
@haveanicedavid if you are happy with the library, please, help the project to grow by spreading few words about it in a blog or something. Thanks
