### ISSUE TITLE
From 1.7 to 2.0 with javascript

### ISSUE THREAD

**Issue by mikaelmorvan** [avkonst/hookstate#70]
Hi,

I use your component a lot in my React dev currently in version 1.7 in javascript.
I'm starting a new project with the last version of hookstate and ... everything is broken :(

Can you enhance the doc please ;)

1) How can I use attach (for the Logger plugin) in javascript (no self property)
2) I understand that there's no more access() method and I can use the global state directly even outside a react component. Do you confirm ?
3) I understant that there's no more nested() method and I can access the properties directly. Do you confirm ?

Thanks for advance for your help
  Mikaël

**Comment by starlabs007** [comment]
@mikaelmorvan I haven't upgraded to 2.0 yet, but I did ask your (2) question in another issue. You can access global state:
> The state is created by createState. The first argument is the initial state value. The result value is an instance of State, which can be used directly to get and set the state value outside of a React component.

It's mentioned in https://hookstate.js.org/docs/global-state  but there's no example of using it outside of a component (probably why it's so easily overlooked). Perhaps the documentation can be updated to emphasis this more?

**Comment by mikaelmorvan** [comment]
@starlabs007 thanks for your reply
The 2) and 3) are ok, I understand and everything's working fine. I think the doc should be more precise to go from 1.7 to 2.0.

The 1) is still giving me headache, I'll wait for an answer before going further.

Mikaël

**Comment by avkonst** [comment]
> 1. How can I use attach (for the Logger plugin) in javascript (no self property)

```
import {createState, self} from '@hookstate/core'
const state = createState(....)[self].attach(Logger)
Logger(state).log()
```

I also advise you to move to DevTools instead of the Logger: https://hookstate.js.org/docs/devtools

**Comment by avkonst** [comment]
Regarding 2:

Yes, there is no more access property.

@starlabs007  The example for the global state has got the mutation outside of a react component. This line:

```tsx
setInterval(() => globalState.set(p => p + 1), 3000)
```

Not sure if it is clear, but I could not think of the better example.

**Comment by avkonst** [comment]
Regarding 3:

See this: https://hookstate.js.org/docs/nested-state

Overall the migration is easy.: Replace ".nested" by "". Replace ".set(" by "[self].set(", and so on for other methods: get, merge, etc.

**Comment by avkonst** [comment]
Here is the list of changes in relation to migration to version 2:

https://hookstate.js.org/docs/migrating-to-v2

**Comment by mikaelmorvan** [comment]
Hi @avkonst 

Thank you so much for the details. 
Self as an import !! I thought it was a specific typescript keyword :)

For the other stuff, everything is clear, thank you
  Mikaël

**Comment by avkonst** [comment]
@mikaelmorvan if you like the library, please consider to help the project by spreading few words about it - blogs, posts, etc..
