### ISSUE TITLE
[2.1] - Nested access with exported state

### ISSUE THREAD

**Issue by yudao** [avkonst/hookstate#71]
Hi!

I'm trying to achieve to initialise my state with an API call (I don't use Promise, cause I want to have  all my business layer directly on the store and not on my components to keep separately concepts) and access it from an exported interface. [I've successfully done this on version 1.7]( https://github.com/avkonst/hookstate/issues/60) but i'm trying to use the version 2.0:

```
import { useEffect } from "react";
import { createState, useState, self } from "@hookstate/core";

import { useAuth } from "../hooks/useAuth";
import { fetch } from "./fetch";

const state = createState({ items: [], isLoading: true, error: null })[
  self
].map((s) => () => {
  return {
    sync(user) {
      s[self].merge({ isLoading: true });
      fetch({
        user,
        path: "/list/security_logs",
        callback: (response) => {
          s[self].set({
            isLoading: false,
            items: response.data || [],
            error: response.error,
          });
          console.log("STATE", s[self].value); // <=== State is well populated
        },
      });
    },
    get list() {
      return s.items.get();  // <=== Can't get value
    },
    get isLoading() {
      return s.isLoading.get();  // <=== Can't get value
    },
  };
});

const useSecurityStore = () => {
  const {
    state: { user },
  } = useAuth();

  const securityLogs = useState(state);

  useEffect(() => {
    if (user) securityLogs[self].value.sync(user);
  }, [user]);

  return securityLogs;
};

export { useSecurityStore };
```

The problem, the interface functions GET and LIST return me empty Proxy or error or don't refresh in component even if I try `return s.isLoading.get()` or `return s[self].isLoading.get()`  or `return s[self].value.isLoading` or .... (I've try everything possible in my poor sense 😄).

I think I'm doing something wrong due to a misunderstanding of the self concept 😞.

Thank you for your help.

Cheers,
Yu.

**Comment by avkonst** [comment]
According to the docs `createState` returns a variable which may be used outside of a React component. And the `useState` returns a variable which must be used within a React component. You are using the result of createState in a React component, so there is no rerender.

The fixed version would be something along these lines:

```
const state = createState({ items: [], isLoading: true, error: null });

const useSecurityStore = () => {
  const {
    state: { user },
  } = useAuth();

  const securityLogs = useState(state)[self].map((s) => {
  return {
    sync(user) {
      s.isLoading.set(true);
      fetch({
        user,
        path: "/list/security_logs",
        callback: (response) => {
          s[self].set({
            isLoading: false,
            items: response.data || [],
            error: response.error,
          });
        },
      });
    },
    get list() {
      return s.items[self].get(); // self is mandatory here, because items is an object (non-primitive) type
    },
    get isLoading() {
      return s.isLoading[self].get();  // self is optional here, because isLoading is primitive type
    },
  };
});

  useEffect(() => {
    if (user) securityLogs[self].value.sync(user);
  }, [user]);

  return securityLogs;
};
```

PS: if you used typescript, all the errors would be caught at compile time.

**Comment by avkonst** [comment]
Also, be aware that you promise is not cancellable. If the component, which uses `useSecurityStore`, is unmounted before the promise is completed, you will likely get an exception.

**Comment by avkonst** [comment]
I have updated the example with exporting a state:

```tsx

import React from 'react';
import { createState, useState, self, State } from '@hookstate/core';

const globalState = createState(0);

const transform = (s: State<number>) => ({
    get: () => s[self].value,
    increment: () => s[self].set(p => p + 1)
})

const accessGlobalState = () => globalState[self].map(transform)
const useGlobalState = () => useState(globalState)[self].map(transform)

setInterval(() => accessGlobalState().increment(), 3000)

export const ExampleComponent = () => {
    const state = useGlobalState();
    return <p>
        <span><b>Counter value: {state.get()}</b> (watch +1 every 3 seconds) </span>
        <button onClick={() => state.increment()}>Increment</button>
    </p>
}


```

**Comment by avkonst** [comment]
Will be in the docs online shortly

**Comment by avkonst** [comment]
self concept is explained here: https://hookstate.js.org/docs/nested-state#accessing-and-mutating-nested-state

**Comment by yudao** [comment]
thanks a lot @avkonst!
All is fine and with that example I understood more the concept.
Sorry for the disturbing and great job!

Cheers.
Yu.
