### ISSUE TITLE
 Still struggling From 1.7 to 2.0

### ISSUE THREAD

**Issue by mikaelmorvan** [avkonst/hookstate#72]
Hi,

I have a major issue using hookstate.
I use hookstate to store data result from api request. These requests are plain javascript object or array of objects.
My problem with the 2.0 is that I can't access the nested javascript objects anymore.

Example:
I'm calling a "whoami" API that returns an object user: {username:"foo", lastname:"bar", ...}

Previously with 1.7 I was using
 myState.nested.user.set({username:"foo", lastname:"bar", ...}) to set the state content 
and then
 myState.nested.user.get().username to get the username field.

Now with 2.0 when I use myState.user.username and hookstate fails with Error: HOOKSTATE-107 [path: /user/username]

It's a real problem for me if I can't access javascript object in Hookstate. Any solution ? any advise ?

One last problem I encountered is knowing a state is null or set.
With 1.7 I was using such code
const myUser = myState.nested.user.get();
and in my react html
{myUser? myUser.lastname : ''}

With the 2.0 this code doesn't work any more.

I've worked the last 4 hour trying to imagine a solution but nothing is working for now.
Thanks again for your help

Mikaël

**Comment by avkonst** [comment]
`myState.nested.user.set({username:"foo", lastname:"bar", ...})` would be `myState.user[self].set({username:"foo", lastname:"bar", ...})`

**Comment by avkonst** [comment]
`myState.nested.user.get().username` would be `myState.user[self].get().username` or better: `myState.user.username.get()`

**Comment by avkonst** [comment]
`const myUser = myState.nested.user.get(); { myUser? myUser.lastname : ''}` would be `const myUser = myState.user[self].get(); { myUser? myUser.lastname : ''}`

**Comment by avkonst** [comment]
PS: if you used typescript, all the errors would be highlighted by the compiler for you and VS Code would assist with the correct path.

**Comment by mikaelmorvan** [comment]
It works !!!

Thanks @avkonst 

And for typescript, it's only a mater of habit, I've been playing with javascript for 15+ years now and it's difficult to start with another web language.
I also play with Golang, Java and other backend languages so I guess I'll play with typescript one day :)

**Comment by avkonst** [comment]
Javascript is horrible language. Typescript is OK fix for it. If there was
no Typescript, I would not even consider to touch frontend devs. As for
backends there are a lot nicer options than golang or java. Use rust
instead of golang, and scala instead of java. I never looked back once I
tried these languages.

**Comment by mikaelmorvan** [comment]
Again with 15+ years of Java and 5+ years of Golang, the habits are hard to change and the existing codebase can't be change easily.
Rust why not, but the existing golang librarys are so awsome that It'll be hard to change.
