### ISSUE TITLE
[Question] How to use map on v2 

### ISSUE THREAD

**Issue by fortezhuo** [avkonst/hookstate#77]
Hi,

I still learn hookstate v2 and create example based on  https://github.com/avkonst/hookstate/blob/master/docs/demos/todolist/src/components/SettingsState.ts

```
export interface StateApp {
  auth: any
  error: any
}

const appState = createState<StateApp>({ auth: {}, error: {} })

export const useAppState = appState[self].map((s) => () => {
  const state = useState(s)

  return {
    get auth() {
      return state.auth.get()
    },
    setAuth(auth) {
      return state.auth.set(auth)
    },
  }
})
```

VSCode will trigger error : 
```
Property 'get' does not exist on type 'State<any>'.
Property 'get' does not exist on type 'StateMixin<any>'.
Property 'set' does not exist on type 'State<any>'.
Property 'set' does not exist on type 'StateMixin<any>'.
```

But if I replace like below script. It can compile and working properly

```
export interface StateApp {
  auth: string
  error: string
}

const appState = createState<StateApp>({ auth: "", error: "" })
```

So how can I define interface like any or object that can be null using this example ?

And I am confused read and find the API Documentation, and I suggest you to provide : 
- Search on Hookstate Documentation
- Improve the documentation like more example each method and elaborate the acronyms

For example : https://hookstate.js.org/docs/typedoc-hookstate-core#map I think the documentation will be great if you can provide more example how to use the method map and elaborate meaning of R, RL, RE, C on map<R, RL, RE, C>

**Comment by avkonst** [comment]
Replace `return state.auth.get()` by `return state.auth[self].get()`, where `self` is `import { self } from "@hookstate/core"`.

`state.auth[self].get()` works when auth is an object or primitive type. Shorter syntax `state.auth.get()` works only when `auth` is of primitive type, like string, number, boolean.

I will keep your ticket open to address your other requests but it might take a while

**Comment by avkonst** [comment]
If you are interested in wrapping and exporting a state, have a look this: https://hookstate.js.org/docs/exporting-state

**Comment by fortezhuo** [comment]
Thanks for your quick response.. I will take a look

**Comment by avkonst** [comment]
Version 3 has been released, where the confusing map method is removed. The update examples show how to deal with exporting a state and async states: https://hookstate.js.org/docs/exporting-state and https://hookstate.js.org/docs/asynchronous-state
