### ISSUE TITLE
Accessing a property with an hyphen (-)

### ISSUE THREAD

**Issue by mikaelmorvan** [avkonst/hookstate#82]
Hi,

I've got a json object comming from a server that has hyphen in some property names.
When I want to access these properties, I must use brackets like ["hyphen-property"] in pure js. 
With Hookstate, I don't know how to access them.
The myState["hyphen-property"].get() don't work. (Cannot read property 'get' of undefined)

Any idea ?
  Mikaël Morvan

**Comment by avkonst** [comment]
It should work. Could you please post more complete example?

**Comment by avkonst** [comment]
need more info. I have created a test, which proves it works.

**Comment by mikaelmorvan** [comment]
Hi,

Thanks for your time :)

What I have in my json (partial extract)

`{
  "creation": "1589869784206",
  "file": {
    "url": "http://myurl.com/str/rest/deployed/sazbfovu4/cr_fl_hdfs/fffffe8dd46066ea5a56cc5b0f1caac6",
    "guid": "fffffe8dd46066ea5a56cc5b0f1caac6",
    "path": "64d6ce3ca26578ab63a4856c435ce518/pgak8vm1r5p82drmaawb55fh/fffffe8dd46066ea5a56cc5b0f1caac6",
    "contentType": "image/jpeg"
  },
  "metadata": {
    "date": "1584469483000",
    "name": "IMG-20200317-WA0020.jpg",
    "size": "1439993",
    "thumb-100": {
      "guid": "fffffe8dd460529fb2247a3f4f5a099e",
      "url": "http://myurl.com/str/rest/deployed/sazbfovu4/cr_fl_hdfs/fffffe8dd460529fb2247a3f4f5a099e"
    },
    "thumb-200": {
      "guid": "fffffe8dd460527cb29786b50558a2d0",
      "url": "http://myurl.com/str/rest/deployed/sazbfovu4/cr_fl_hdfs/fffffe8dd460527cb29786b50558a2d0"
    },
    "thumb-300": {
      "guid": "fffffe8dd4605263e9929a6339544ba1",
      "url": "http://myurl.com/str/rest/deployed/sazbfovu4/cr_fl_hdfs/fffffe8dd4605263e9929a6339544ba1"
    },
    "thumb-400": {
      "guid": "fffffe8dd46052454bb7092723e20e94",
      "url": "http://myurl.com/str/rest/deployed/sazbfovu4/cr_fl_hdfs/fffffe8dd46052454bb7092723e20e94"
    },
    "thumb-500": {
      "guid": "fffffe8dd4605234b5b32012b4183b1b",
      "url": "http://myurl.com/str/rest/deployed/sazbfovu4/cr_fl_hdfs/fffffe8dd4605234b5b32012b4183b1b"
    }
  },
  "type": "image/jpeg"
}`

I use a global fileState for my file list and a scoped state to use my file in my component :
`fileState[self].set({
            list: normalized.entities.entries, // my file list
            folder: data.result.fileList.folder,
            folderList,
            fileList,
            roomList
          });`

In my parent component, I use the global file state :
`<Grid container spacing={4}>
            {
              fileState.fileList[self].keys ?
                fileState.fileList[self].keys.map(stateIndex =>
                  <FileItem key={stateIndex} itemState={fileState.fileList[stateIndex]} />
                )
                : ''
            }

          </Grid>`

And I my child component I use a scoped state
`const state = useState(props.itemState);
  const metadata = state.metadata[self].get();
`

And the state is used in the html like that 
`{metadata && metadata["thumb-300"] ?
                  <img className="card-img-top" src={metadata["thumb-300"].url} />
                  :
                  <FontAwesomeIcon
                    icon={['far', 'file']}
                    className="display-2 text-first mx-auto"
                  />
                }`

and ... it works this morning :(

must be a PEBCAK problem :)

Sorry for that, I spent lot of time yesterday on this problem and I thought it was a problem with hookstate.

Thanks for your time and the reactivity
Mikaël
