### ISSUE TITLE
state.get() property does not exist

### ISSUE THREAD

**Issue by haveanicedavid** [avkonst/hookstate#83]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/9052511/85914502-a61fd600-b7fb-11ea-9b48-9bf654ddcfc4.png">

```
 const pageState = hookState({})
 const page = pageState.get()
```

In the above image, hookstate's `useState` method is aliased to `hookState`. Calling `.get()` on a base state instance (as in the snippet) always returns this error. It works by using `pageState[self].get()`, however that's contrary to what the docs indicate. 

The same happens trying to call `.set()`

On hookstate 2.0.1. Happy to share any other relevant data

**Comment by haveanicedavid** [comment]
I realized you might have answered my question [in this issue](https://github.com/avkonst/hookstate/issues/79)

> Shorter syntax state.auth.get() works only when auth is of primitive type, like string, number, boolean.

But i'm leaving this open just to make sure i'm going about things the right way

**Comment by avkonst** [comment]
When your state is not a primitive value. Use longer form: pageState[self].get(). here is more info: https://hookstate.js.org/docs/nested-state#setting-new-state-value

**Comment by avkonst** [comment]
The requirement to use `[self]` will disappear in version 3.

**Comment by avkonst** [comment]
Hope it makes things clearer

**Comment by haveanicedavid** [comment]
It does. I'm loving the library - thanks!

**Comment by avkonst** [comment]
Spread few words about it in a blog post or a like. This will help it to grow. Thanks
