### ISSUE TITLE
Strange behaviour with nested arrays

### ISSUE THREAD

**Issue by mikaelmorvan** [avkonst/hookstate#84]
Hi,

I've got something strange happening. I can't delete an item of a nested array.

In my code, I'm trying to delete a chat item in an chat list.

My State is called chatState and is defined as 
```javascript
const initialStateChat = {
  content: [],
  page: {},
  isLoading: false,
  firstLoad: true
};
```
and
```javascript
const chatState = createState(initialStateChat);
```

Once filled, the state look lite
```
{
  content: [
    {
      ts: 1591799759710,
      guid: '///+jWFXPKIlBjSvpJvPoA==',
      data: {
        type: 'text',
        value: 's',
        from: {
          username: 'mikaelmorvan',
          userkey: 'gCFPLeD3LbMCeDvuI2sX7A',
          avatar: 'url'
        }
      }
    },
    {
      ts: 1591799759714,
      guid: '///+jWFXPJ4oyCjAwbrwQA==',
      data: {
        type: 'text',
        value: 'u',
        from: {
          username: 'mikaelmorvan',
          userkey: 'gCFPLeD3LbMCeDvuI2sX7A',
          avatar: 'url'
        }
      }
    },
```

What I do :
```javascript
chatState.content[self].keys.map( stateIndex => {
  if (chatState.content[stateIndex].guid.get() === data.result.guid) {
    console.log("trouve", stateIndex, data.result.guid);               
    chatState.content[self].merge({ stateIndex: none});
    }
})
```

The problem is that nothing happens.
If I hardcode the stateIndex value, it works
```javascript
chatState.content[self].keys.map( stateIndex => {
  if (chatState.content[stateIndex].guid.get() === data.result.guid) {
    console.log("trouve", stateIndex, data.result.guid);                
    chatState.content[self].merge({ 10: none}); // OK, the item is removed
    }
})
```
Have I missed something again ?

Mikaël

**Comment by avkonst** [comment]
What is the result of `typeof stateIndex`? What is the result of `Array.isArray(chatState.content)`

**Comment by mikaelmorvan** [comment]
typeof stateIndex: number

Array.isArray(chatState.content) : true

**Comment by avkonst** [comment]
In this context: `{ stateIndex: none}` stateIndex is a name of a property but not a property value.
You should use: `chatState.content[stateIndex][self].set(none)`

**Comment by mikaelmorvan** [comment]
It works !!

Thank for your help :)

But, I'm a bit confused, I'm working a lot with your super useful library and sometimes I don't understand why the [self] thing must be placed before or after a property. 
Your documentation is great but deals with simple samples. If you want I could extract lots of real life examples from my code to help others to deal with your library.

Mikaël

**Comment by avkonst** [comment]
`[self]` is a property of `State<>` object.
