### ISSUE TITLE
How to access state property by name as string in typescript?

### ISSUE THREAD

**Issue by westofpluto** [avkonst/hookstate#86]
Suppose i have a global state like this:

const globalState = createState({a: 1, b: 2});

Now I want to get access to either a or b using the string variable called "name". For example:

const name = 'a'
const aval = globalState[name];

This throws a compiler error. How can I access a property on an object by using the name of the property in a string?

**Comment by avkonst** [comment]
`globalState` is of type `State<{a: number, b: number}>`. It means the indexes should be of type `keyof {a: number, b: number}`, which unfolds to `'a' | 'b'`. You name variable is of type `string`, which is not assignable to type `'a' | 'b'`. Do the following to fix it:

```
const name: 'a' | 'b' = 'a'
```

More generic way would be:
```
type MyStateType = {a: number, b: number};
const globalState = createState<MysStateType>({a: 1, b: 2});
const name: keyof State<MyStateType> = 'a'; // or simply 'const name: keyof MyStateType' - which is a subset, but sufficient for your case
const aval = globalState[name];
```

**Comment by avkonst** [comment]
Reopen if the answer is unclear. Please note that version 3 is out. StateMethods have got `nested` method, which you can use for the usecase you asked about above.
