### ISSUE TITLE
Is abstraction layer possible?

### ISSUE THREAD

**Issue by westofpluto** [avkonst/hookstate#87]
I understand that if we have a state globalState like this:

const globalState = createState({a: "something", b: "whatever"})

then inside the react component, I would need to get and use the value of globalState.a like this:

    const state=useState(globalState);
    ...
    function somefunc() {
        return <p><input value={state.a.get()} onChange={e => state.a.set(e.target.value)}/></p>
    }

But support I want to create a separate DataStore class in a separate file (say DataStoreFile.ts) that contains methods that call useState and state.a.get() like this:

class DataStore {
     get_a_in_component() {
        const state=useState(globalState);
        return state.a.get();
    }
}
export const dataStore = new DataStore();

Then I would us this in the react component like this:

    import { dataStore } from './DataStoreFile';

    inside the component:
    function somefunc() {
        return <p><input value={dataStore.get_a_in_component()} onChange={e => state.a.set(e.target.value)}/></p>
    }

Does this work? Or is it the case that you must call useState and state.a.get() directly in the component in which it used, ie we cannot create an abstraction layer like the DataStore class in another file?

**Comment by avkonst** [comment]
useState is a react hook, so it should follow rules of hooks https://reactjs.org/docs/hooks-rules.html

Abstraction layer is easy. Here is the example how you can wrap hookstate by your custom hook. https://hookstate.js.org/docs/exporting-state

**Comment by avkonst** [comment]
Reopen if the answer is unclear
