### ISSUE TITLE
Set state from useEffect

### ISSUE THREAD

**Issue by dave10101010** [avkonst/hookstate#91]
I'm trying to update nested state from a subscription callback something like this.

```javascript 
const itemsState = useState(getItems);

useEffect(() => {
  if (!itemsState.promised) {
    const { unsubscribe } = client.subscribe((result) => {
        result.items.forEach(newItem => {
          const itemState = itemsState[newItem.id];
          if(itemState.updatedAt.get() !== newItem.updatedAt){
            itemState.merge({ updatedAt: newItem.updatedAt });
          }
        });
      })
    );

    return () => {
      unsubscribe();
    };
  }
}, [itemsState]);
```

However whenever it updates the state, it restarts the subscription because the itemsState is a dependency in the useEffect. If I were to use normal React useState I'd be able use setState in the callback and drop the itemsState dependency. What am I doing wrong ? How would I fix this using this library?

Thanks

**Comment by avkonst** [comment]
itemsState is a new object (state controller) for each rerender, so dependency should be different.

If you need to subscribe only after the getItems is resolved use this:

```tsx
const itemsState = useState(getItems);

useEffect(() => {
  if (!itemsState.promised) {
    const { unsubscribe } = client.subscribe((result) => {
        result.items.forEach(newItem => {
          const itemState = itemsState[newItem.id];
          if (itemState.updatedAt.get() !== newItem.updatedAt) {
            itemState.updatedAt.set(newItem.updatedAt);
          }
        });
      })
    );

    return () => {
      unsubscribe();
    };
  }
}, [itemsState.promised]); // subscribe once on resolved, unsubscribe once on unmount
```

if you can subscribe before getItems is resolved, use the following:

```tsx
const itemsState = useState(getItems);

useEffect(() => {
    const { unsubscribe } = client.subscribe((result) => {
  if (!itemsState.promised) {
        result.items.forEach(newItem => {
          const itemState = itemsState[newItem.id];
          if (itemState.updatedAt.get() !== newItem.updatedAt) {
            itemState.updatedAt.set(newItem.updatedAt);
          }
        });
  }
      })
    );

    return () => {
      unsubscribe();
    };
}, []); // subscribe once on mount, unsubscribe once on unmount
```

**Comment by dave10101010** [comment]
Thanks for the reply.

These solutions work. However I am using the eslint react hooks plugin included in create-react-app and I get this warning.

> React Hook useEffect has a missing dependency: 'itemsState'. Either include it or remove the dependency array.eslintreact-hooks/exhaustive-deps

The official docs say you shouldn't omit functions from the list of dependencies.
 [https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies](url)

Is there a safe way to fix this warning?

**Comment by avkonst** [comment]
Yes. You can suppress the warning for this line only using a special
comment.
