### ISSUE TITLE
How to get object value from state?

### ISSUE THREAD

**Issue by luccasmaso** [avkonst/hookstate#92]
I'm trying to find on docs how to get state values as plain object instead of Proxy. The following commands prints the same output as the image. How to get the content from the [[Target]]? Thanks!
```
console.log(state.get())
console.log(state.value)
```
<img width="630" alt="Screenshot 2020-08-11 at 12 29 47" src="https://user-images.githubusercontent.com/1427231/89916807-6efc5d00-dbce-11ea-8842-23af3f3565ca.png">

**Comment by avkonst** [comment]
Use the following:

```
state.attach(Downgraded).get()
```

Read about implications for downgraded here: https://hookstate.js.org/docs/performance-intro

**Comment by GalumphingCallooh** [comment]
Have you explored revocable proxies, wherein the proxy is only active while the state is being accessed? I've done some work there before, so I could look into it for a pull request if there was interest.

**Comment by avkonst** [comment]
Could you please elaborate a bit more what you mean?
I believe if an object is released as a proxy instance, it will stay as a proxy. Theoretically, it can be possible to extract the underlying object instance from the proxy instance, if there was a special api exposed by a library (hookstate in this example), which created the proxy object in the first place. `state.attach(Downgraded).get()` is effectively this sort of the API.

**Comment by GalumphingCallooh** [comment]
Hmm, good point, revocables aren't as useful as I thought here, and I struggle to find an instance where they would be. I just started looking at the codebase, and I'm a big fan of this approach to state management, currently digging around in it. Nice work.

**Comment by GalumphingCallooh** [comment]
Wait, wait I've just remembered why I suggested revocable in the first place and why they're useful: memory management. Revocable proxies no longer contain references to their underlying object, so it flags them for garbage collection.

**Comment by avkonst** [comment]
The object behind the proxy object is captured in 2 other places. It is released only when the original state stops referring to it. Rerender invalidates all previously issued proxies.

**Comment by TroyJoachim** [comment]
@avkonst 
The Downgraded plugin doesn't seem to be working.
![image](https://user-images.githubusercontent.com/45337760/108000954-04264700-6fa0-11eb-867e-10253684d1c9.png)
![image](https://user-images.githubusercontent.com/45337760/108001027-39cb3000-6fa0-11eb-8b3d-407f2e6b5db8.png)

Any suggestions?

**Comment by TroyJoachim** [comment]
Never mind, I just read this: https://github.com/avkonst/hookstate/issues/101
