### ISSUE TITLE
Scoped state from global state rerender when it should not 

### ISSUE THREAD

**Issue by dezmou** [avkonst/hookstate#93]
Hello, 

I am trying to understand the global state of hookstate, my goal is to have one file with a big state which contains all the properties needed by components but I don't want a component to rerender if a property that the component is not using change.

I thought the scoped states would be great but here is an example : 

```jsx
import React, { useEffect } from 'react';
import { useState, createState } from "@hookstate/core"

const state = createState({
  foo : "foo",
  bar : "bar"
})

setInterval(() => {
  state.foo.set(`foo_${Date.now()}`)
},200)

function App() {
  
  // Should be scoped to state.bar only
  const bar = useState(state.bar)

  // But this is also triggered when state.foo is changed
  useEffect(() => {
    console.log("useEffect Triggered !");
  })

  return (
    <div className="App">
      
      {/* if we remove this, then the useEffect is not triggered anymore */}
      {bar.get()}
    
    </div>
  );
}

export default App;


```

My app Component is not using the foo property but still the useEffect is triggered when foo is updated. 
Is there something I am missing ? 
Does the scoped state only work when the state is passed by props ? 

Thanks a lot ! 

Modez

**Comment by avkonst** [comment]
You example should work. I will double check the rerendering.

You also do not need the scoped state there to avoid the rerendering. The following should not trigger rerendering too:

```
const bar = useState(state).bar
```
Was it not clear from the docs? If not, we would better to update the docs.

**Comment by avkonst** [comment]
Ok. I checked it.

Use the following instead:

```
const bar = useState(state).bar // it subscribes to state, traces that the bar is only used
```

Scoped state is for minimising rerendering of a parent component. Here are more details: https://hookstate.js.org/docs/performance-intro

When you do `useState(state.bar)` it subscribes to the global state and does not trace that only the bar is used, because it happens before it is hooked. So it think that the entire state is used by this hook. However, your expectation about the behaviour was quite reasonable too. I will keep the ticket to have a look if hookstate can deliver on this expectation. Thanks for the ticket.

**Comment by dezmou** [comment]
It works ! Thanks ! 

I was a little confused since the examples tend to use props to pass children states to components.

Will reading the performance intro, I still don't understand another think : 

```jsx 

function Ex3_Parent_GlobalStateHooked() {
    const state = useState(globalState)
    return <>
        <Ex3_Child_PropsState_BUsed_Scoped_Downgraded state={state.B}/>
    </>
}
function Ex3_Child_PropsState_BUsed_Scoped_Downgraded(props: { state: State<number> }) {
    const state = useState(props.state)
    state.attach(Downgraded)
    return <p>{state.B.value}</p>
}

```

If I understand, we are giving to the child directly a `state<number>`, then why the child still need to access to `state.B.value` and not `state.value` ?

Thanks for all Audrey !

**Comment by avkonst** [comment]
This was a typo. I have fixed it now.

**Comment by dezmou** [comment]
It is all clear perfect now :)

**Comment by avkonst** [comment]
This was fixed in the latest 3.x version. Now you can use substate from a global state directly.
