### ISSUE TITLE
How to load apollo graphQL data

### ISSUE THREAD

**Issue by smooJitter** [avkonst/hookstate#98]
I'm trying to load user data from a graphql query, specifically react-apollo hooks.
it doesn't appear useEffect updates are captured.  The state.set({...}) doesn't seem to update;
It could be that I'm not processing useQuery() results appropriately.  Can you offer me help here?  I'm sure apollo and graphql users would appreciate and demonstrate how this use works. 

```js
import {useQuery} from 'react-apollo';

function getLoggedUser() {
  const {data, loading} = useQuery(queries.GET_ME);
  const {me} = data || {};
  return {me, loading};
}

```
Here's where I create the state
```js
function useUserState( ) {
  const {me, loading} = getLoggedUser();

  const state = createState({
      userName: '', 
      userTitle: '',
   });

  useEffect(() => {

    const init = () => {
      state.set({...me});
    };

    if (me) {
      init();
    }

  }, [me]);

  return useState(state);
}

```
This is what have in my render function.
```js
function renderUserState(){
   const  userState = useUserState()
   console.log( userState.get());   
}

// {useName:'', useTitle: ''}

```

**Comment by avkonst** [comment]
1. You have got new state on each render. It means as soon as the state is updated in the useEffect callback it is replaced by a new one. Try this:

```js
function useUserState( ) {
  const {me, loading} = getLoggedUser();

  const state = useState({
      userName: '', 
      userTitle: '',
   });

  useEffect(() => {

    const init = () => {
      state.set({...me});
    };

    if (me) {
      init();
    }

  }, [me]);

return state;
}
```

**Comment by avkonst** [comment]
2. getLoggedUser uses a hook inside, so it should be hook too, means it should be named useLoggedUser instead

**Comment by avkonst** [comment]
3. `me` is an object. Are you sure the same object is returned by getLoggedUser after data is loaded? I think it will be the same..

**Comment by avkonst** [comment]
4. useQuery uses useState inside too. So you have got 2 state hooks and one effect hook to sync states. There is better alternative: do not use apollo hooks, just use apollo client to execute queries (do not remember function). The client will return you the `Promise`, which you can map to the desired state value and initialize hookstate state directly with it. See async states with Hookstate: https://hookstate.js.org/docs/asynchronous-state

**Comment by avkonst** [comment]
Hope it answers your questions. I have use apollo client with Hookstate. It was successful. Although I found later there are lighter GraphQL clients, which do the queries only and do not manage the state - this is what I needed, because the state was managed by Hookstate.

**Comment by smooJitter** [comment]
Here are a few changes,  

```js
const useAwaitQuery = query => {
  const apolloClient = useApolloClient();
  return useCallback(
    options => {
      return apolloClient.query({
        ...options,
        query,
      });
    },
    [apolloClient, query]
  );
};
```
Now I create a global state as such
```js
async function useUserState() {
  const fetchCurrenUser = useAwaitQuery(queries.GET_ME);
  const {data} = await fetchCurrenUser();
  const {me} = data;
  return createState({...me});
```
Insider the render function

```js
function renderUser() {
  const userState = useUserState();
  const user = useState(userState);
  console.log('global state', userState);
  console.log('local state', user.firstName.get());
  return (...);
}
```
The global state userState logs a promise where I can see the graphql data;
The local state user logs a Proxy.
The local state user.firstName.get() fires an error. 

Looks like I am getting close.   I appreciate your help and this package.

**Comment by avkonst** [comment]
useAwaitQuery - is it a hook or just normal function which does http network call to the graphql server? If it is the later, then it should be something along these lines (and it should not be named as a hook, but it is another story):

```js
function renderUser() {
  const user = useState(() => {
    const fetchCurrenUser = useAwaitQuery(queries.GET_ME);
    const {data} = await fetchCurrenUser();
    const {me} = data;
    return {...me}     
  });
  if (user.promised) {
     console.log('still loading');
     return;
  }
  console.log('local state', user.firstName.get());
  return (...);
}
```

**Comment by parisholley** [comment]
One thing to remember, is apollo-client actually returns proxies (not raw JSON objects), so you will need to convert them to JSON before storing in hookstate (since it only supports primitive values)

```
  const state = useState(async () => {
    const result = await client.query({});

    // stringify to remove apollo proxy
    return JSON.parse(JSON.stringify(result.data));
  });

  if (state.promised) {
    return <p>Loading...</p>;
  }

  if (state.error) {
    return <p>Error :(</p>;
  }
```

**Comment by avkonst** [comment]
What is the type of result.data? I am sure it is an object already parsed from JSON response. I think I used this:

```
const state = useState(async () => {
    const result = await client.query({});
    return result.data;
  });
```

**Comment by parisholley** [comment]
it depends on your client configuration, for me, i use apollo-client with an in-memory cache, which means it returns proxies instead of raw JSON to support re-renders. Example error that occurs if you write the proxy into hookstate, and attempt to invoke some type of StateMethod call:

```Uncaught TypeError: 'get' on proxy: property '0' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')```

**Comment by avkonst** [comment]
Closed as seems the question is answered
