### ISSUE TITLE
Update docs how to associate meta-data with state values

### ISSUE THREAD

**Issue by GalumphingCallooh** [avkonst/hookstate#99]
Use-case:
As a hookstate dev user, I want to be able to attach arbitrary symbols to pieces of hookstate's state. I want to do this to represent some meta-data about my particular state info.

Current result of attempt:
Hookstate will throw state modification errors.

Desired result of attempt:
Hookstate allows for symbols to be attached to state. 

I'm new to the codebase, so this is my naive attempt:
https://github.com/avkonst/hookstate/compare/master...GalumphingCallooh:master

**Comment by avkonst** [comment]
I believe it is possible. I do it a lot in my projects. Just get a value
out of a state, and it is possible to get and set symbol properties.

**Comment by avkonst** [comment]
Improve documentation about this feature.

**Comment by avkonst** [comment]
Hookstate 4 will have explicit API to get/set metadata.

**Comment by avkonst** [comment]
https://github.com/avkonst/hookstate/issues/34
